Send user read receipts based on scroll position #86
project-robius/robrix pull request #124
Opened 2024-08-23 16:22 UTC by alanpoon

https://github.com/project-robius/robrix/issues/86

1. Send a regular [Read receipt](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/ruma/api/client/receipt/create_receipt/v3/enum.ReceiptType.html#variant.Read) is done inside draw_walk function
2. Send a [FullyRead receipt](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/ruma/api/client/receipt/create_receipt/v3/enum.ReceiptType.html#variant.FullyRead) is implemented inside when the user clicks the bottom half of the screen. 
<img width="321" alt="fully_read" src="https://github.com/user-attachments/assets/c7ada556-465c-43ad-9e42-5aee375615d6">

2024-08-23 17:52 UTC, kevinaboos requested changes
Hi @alanpoon, thanks so much for the contribution! I really appreciate you looking into this feature.

I've got a couple of questions/comments:
1. I'm not actually sure what the best policy is for determining whether a user has actually "read" a given message. Is your heuristic here a typical choice, that is, is it common to require a "click in the bottom half of the window" to signify that the user has read a message? I would think it'd be more common to base that on where the user has scrolled to, not where they click or tap. I'm also not sure if we should make it time-based, although I know i did mention that in the original issue #86, but I'm reconsidering now. Would love to hear your opinion there.
2. The `draw_walk()` routine should be as fast and as minimal as possible, so it's not the best place to do something like checking/calculating where a message is and then sending a user read receipt update. Ideally this should be done in a background task, but for the sake of ease, you could do it in the event handler upon a `PortalList::scrolled()` action, since you're already doing other logic in the event handler currently.

2024-08-23 17:52 UTC, kevinaboos commented on src/app.rs
> +use matrix_sdk::crypto::vodozemac::ecies::Message;
remove (?). seems accidental

2024-08-24 01:10 UTC, alanpoon commented
> Hi @alanpoon, thanks so much for the contribution! I really appreciate you looking into this feature.
> 
> I've got a couple of questions/comments:
> 
> 1. I'm not actually sure what the best policy is for determining whether a user has actually "read" a given message. Is your heuristic here a typical choice, that is, is it common to require a "click in the bottom half of the window" to signify that the user has read a message? I would think it'd be more common to base that on where the user has scrolled to, not where they click or tap. I'm also not sure if we should make it time-based, although I know i did mention that in the original issue [Send user read receipts based on scroll position #86](https://github.com/project-robius/robrix/issues/86), but I'm reconsidering now. Would love to hear your opinion there.
> 2. The `draw_walk()` routine should be as fast and as minimal as possible, so it's not the best place to do something like checking/calculating where a message is and then sending a user read receipt update. Ideally this should be done in a background task, but for the sake of ease, you could do it in the event handler upon a `PortalList::scrolled()` action, since you're already doing other logic in the event handler currently.

1. I am taking Element desktop app as a reference. It seems like it registers fully read event when user click on the message. To do so, I would need to compute the click box for the individual item in the scroll list. I couldn't implement this thus I implemented "click bottom half of the screen" and send the fully read event based on the index of content last drawn.
2. I will look into it.

2024-08-24 03:50 UTC, alanpoon commented on src/app.rs
> +use matrix_sdk::crypto::vodozemac::ecies::Message;
removed

2024-08-25 07:07 UTC, ZhangHanDong commented
#86

2024-08-26 17:46 UTC, kevinaboos commented
> 1. I am taking Element desktop app as a reference. It seems like it registers fully read event when user click on the message. To do so, I would need to compute the click box for the individual item in the scroll list. I couldn't implement this thus I implemented "click bottom half of the screen" and send the fully read event based on the index of content last drawn.

Thanks for the response! Personally I think that determining whether a user has read a given message should _not_ be based on click activity, but rather just the position of the timeline on screen. In the future, when we have a user preferences screen, we can make this configurable based on user choice. So, whatever option we choose here, let's make it easy to change and thus, cleanly encapsulate all the logic into one function.

2024-08-29 03:25 UTC, ZhangHanDong commented
I think the process should be like this:

The Timeline component sends appropriate read receipts when the user scrolls. It will send a Read receipt when the message first scrolls to the bottom of the view, send a FullyRead receipt when the message scrolls out of the top of the view, and also send a FullyRead receipt when the message has been displayed on screen for more than 5 seconds.

@kevinaboos  Is that correct?

2024-08-29 07:37 UTC, kevinaboos commented
Yep! To echo what I said in our chat:

> yes, that sounds generally correct! 
> 
> Note that for a first attempt,  we don't even have to make things that complicated -- we can just send only `FullyRead` receipts once the message is displayed on screen (for any amount of time).
> Then we can always refine the policy (or later, make it a user-configurable choice) to make the UX even better.

2024-08-30 10:26 UTC, alanpoon commented
> I think the process should be like this:
> 
> The Timeline component sends appropriate read receipts when the user scrolls. It will send a Read receipt when the message first scrolls to the bottom of the view, send a FullyRead receipt when the message scrolls out of the top of the view, and also send a FullyRead receipt when the message has been displayed on screen for more than 5 seconds.
> 
> @kevinaboos Is that correct?

I did some fix to add the logic to send FullyRead receipt when the message has been displayed on screen for more than 5 seconds. I removed the click logic for FullyRead receipt .

2024-09-03 09:57 UTC, ZhangHanDong commented on src/scheduler.rs
> +use lazy_static::lazy_static;
This should be replaceable by `lazylock` in Rust stable  1.80

https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html#lazycell-and-lazylock

This project should be able to keep up with the latest Rust version.

2024-09-03 19:32 UTC, kevinaboos requested changes
Hi @alanpoon, thanks again for continuing to work on this.

Overall, this approach is super complicated and a bit messy. Sending read receipts should be super simple and not require so much complexity, with background threads and lazy statics and all that stuff. 

I left some more detailed comments, so check those out for more.

2024-09-03 19:32 UTC, kevinaboos commented on Cargo.toml
> +reqwest = { path = "../reqwest"}
what's this for? doesn't seem necessary.

2024-09-03 19:32 UTC, kevinaboos commented on src/home/room_screen.rs
> +use std::{borrow::Cow, collections::BTreeMap, f64::consts::E, ops::{Deref, DerefMut, Range}, sync::{Arc, Mutex}, time::Duration};
what's `f64::consts::E` for?

2024-09-03 19:32 UTC, kevinaboos commented on src/home/room_screen.rs
> +    #[rust] prev_fullyread_last_timestamp:Option<MilliSecondsSinceUnixEpoch>,
all of the state required to handle read receipts should go in the `TimelineUiState` struct or another dedicated structure. This `Timeline` struct is a widget struct that should contain only the data needed for the widget to display content.

2024-09-03 19:32 UTC, kevinaboos commented on src/home/room_screen.rs
> +                }
this whole approach is way over-complicated. The Matrix SDK's function for sending read receipts will already de-duplicate multiple requests, so I don't think you need all this complexity.

Also, in terms of code structure, please move all of this logic to a separate function for handling/sending read receipts, rather than doing it inline in the event handler. It's impossible to read this way.

Also, Makepad provides a timer API and timer completion Events which can be used for handling 5-second timeouts, which will likely simplify things _substantially_ here.

2024-09-03 19:32 UTC, kevinaboos commented on src/scheduler.rs
> +use lazy_static::lazy_static;
I might be confused, but I don't see why any of this is necessary. Why do we need a dedicated background thread just to handle read receipts?

2024-09-03 19:32 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    SignalToUI::set_ui_signal();
setting a UI signal is only needed when some part of the UI needs to be updated & redrawn. Is that the case here? I didn't see any place in the `room_screen` file where you're checking for this or handling a read receipt being sent, so this seems unnecessary.

2024-09-03 19:32 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    SignalToUI::set_ui_signal();
see above comment.

2024-09-10 15:01 UTC, closed without merging

2024-09-16 01:52 UTC, alanpoon commented on src/home/room_screen.rs
> +                }
https://github.com/matrix-org/matrix-rust-sdk/issues/3997 here is what I get if i don't de-deduplicate myself
Here is the screenshot of charles proxy.
<img width="607" alt="Screenshot 2024-09-16 094604" src="https://github.com/user-attachments/assets/d8868841-cc00-4078-98de-6eae96a17fd2">

2024-09-16 15:40 UTC, alanpoon commented on src/home/room_screen.rs
> +                }
I checked, duplicate read receipt is allowed only occurring for Join room event. Let me filter this out