Complete the basic functions of the search bar
project-robius/robrix pull request #135
Opened 2024-09-03 12:48 UTC by tyreseluo

More content may be needed, only simple room list based filtering has been implemented so far, removal of icon and other content is under construction.

2024-09-03 20:02 UTC, kevinaboos requested changes
Hi @tyreseluo, thanks so much for submitting this PR!

I left some very detailed comments, but the summary of my review is that we should not store the list of rooms that match the search query term by duplicating the actual `RoomPreviewEntry`s.

2024-09-03 20:02 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    .collect();
you don't need to `.collect()` this into a vector if you're just going to iterate over it. You can just iterate over the iterator produced by `.chain()`.

2024-09-04 01:46 UTC, tyreseluo commented
Hi @kevinaboos, thank you very much for your comments, I will keep changing and exporting and keep improving myself. Until I am able to complete and think about this project independently. This question will be back to you here within the week. Thanks for your hard work.

2024-09-04 01:52 UTC, closed without merging

2024-09-04 02:00 UTC, kevinaboos commented
oh, you don't have to close the issue! I mean, you can close it if you want, or if you prefer to open a new issue that's fine too. But it just needs some moderate restructuring of the way that you store the rooms that match the search terms.

2024-09-04 02:09 UTC, tyreseluo commented
oh no! sorry, i made a mistake 😅.  I discard the changes, when i pull the latest code, I don't want to close it. I'd like to keep working on it. i will keep solve this issue!

2024-09-04 03:45 UTC, kevinaboos commented
No worries! I'll re-open it.

Let me know when you're ready for another review. Also, kindly avoid force pushing, as it removes my review comments.

2024-09-04 03:45 UTC, kevinaboos commented
Re-opening