Fixed issue-137: Gray out icons of not yet implemented features
project-robius/robrix pull request #144
Opened 2024-09-10 10:30 UTC by ZhangHanDong

Fixed : #137  Gray out icons of not yet implemented features

2024-09-10 12:01 UTC, ZhangHanDong commented
<img width="1275" alt="Screenshot 2024-09-10 at 19 58 57" src="https://github.com/user-attachments/assets/b1116f70-d196-4f76-99a5-1b68abd85e21">

2024-09-10 19:03 UTC, kevinaboos commented on login.toml
kindly restore this file

2024-09-10 19:08 UTC, kevinaboos commented on src/home/rooms_sidebar.rs
> +            }
Ideally, the visibility of the `latest_message` should either be a user preference (which we are working on implementing soon), or based on the width of the `rooms_list` pane itself. Hardcoding it as non-visible is ok as a temporary change for your local branch if you prefer it that way, but I don't think we should force that upon all users in the upstream `main`.

2024-09-11 02:20 UTC, joulei commented
Actually most of these issues were already fixed here https://github.com/project-robius/robrix/pull/138, maybe the todo list in the issue wasn't up to date (should've updated/closed when the PR was merged), we agreed on that sidebar size as narrow enough after those fixes.

Besides that, I also agree on graying-out the disabled items further, thanks for also including menu items and for the color naming 🙌🏽

2024-09-11 05:19 UTC, ZhangHanDong commented on login.toml
ok

2024-09-11 05:22 UTC, ZhangHanDong commented on src/home/rooms_list.rs
> +                flow: Down
This is to accommodate the narrowed width, moving the timestamp to display below the room name.

2024-09-11 05:23 UTC, ZhangHanDong commented on src/home/rooms_sidebar.rs
> +            }
ok

2024-09-11 17:19 UTC, kevinaboos requested changes
thanks, looks good now. Can you restore `login.toml`? After that, I can merge this in.

2024-09-12 02:24 UTC, ZhangHanDong commented
I have  restored the `login.toml`

2024-09-12 17:28 UTC, kevinaboos approved these changes
thanks, lgtm!

2024-09-12 17:29 UTC, merged