Send user read receipts based on scroll position #86
project-robius/robrix pull request #152
Opened 2024-09-19 13:00 UTC by alanpoon

Rework of https://github.com/project-robius/robrix/pull/124

1. Removed lazy_static
2. Replaced thread with makepad timer
3. Removed de-duplicate logic when sending read receipt
4. Removed un-neccessary SignalToUI
5. Moved fields into TimelineUiState

2024-09-20 01:57 UTC, alanpoon commented
PR for https://github.com/project-robius/robrix/issues/86

2024-09-20 07:18 UTC, kevinaboos requested changes
thanks for the PR! 

One request -- can you follow standard whitespace conventions, like a space after a comma? Without that, it's hard to read the code easily. 

I left a few detailed comments.

2024-09-20 07:18 UTC, kevinaboos commented on src/home/room_screen.rs
> +                                        }
The `submit_async_request()` procedure is fairly expensive (and somewhat "high latency"), as it requires pushing a request object onto a queue, and then waiting for tokio to schedule in a background async task to pop it off of the queue and handle it.

Thus, instead of calling that in a loop, you should create a single request that can contain multiple read receipts, and then call `submit_async_request` only once.

2024-09-20 07:18 UTC, kevinaboos commented on src/sliding_sync.rs
> +        message:String,
you don't need to include the entire text of the event message here, there's no reason for that.

2024-09-20 07:18 UTC, kevinaboos commented on src/sliding_sync.rs
> +        message:String,
you don't need to include the entire text of the event message here, there's no reason for that.

2024-09-20 07:18 UTC, kevinaboos commented on src/sliding_sync.rs
> +                        Err(_e) => error!("Failed to send message to room {room_id}: {_e:?}"),
the logic here is correct, but can you update the log/error statements to be specific to sending read receipts and not sending messages? (I assume that's a copy-paste artifact based on copying this code structure from the `SendMessage` variant)

2024-09-20 07:18 UTC, kevinaboos commented on src/home/room_screen.rs
> +    marked_fully_read_queue:HashMap<String,(OwnedRoomId,OwnedEventId)>,
Can you explain why a queue is necessary here? I don't quite understand the purpose of this...  also, it's not a queue, right? It's just a set of events. 

Instead of adding events to this `marked_fully_read_queue` and then iterating over it later, can't you just directly send the read receipt request from the point in the code where you're checking if the 5-second timer has elapsed? I'm confused by this two-part approach, which seems unnecessary. But I might be missing something, so please let me know what the purpose of this is.

2024-09-23 03:09 UTC, alanpoon commented on src/home/room_screen.rs
> +    fn send_user_read_receipts_based_on_scroll_pos(&mut self,cx:&mut Cx,actions:  &Vec<Box<dyn ActionTrait + Send>>){
fixed

2024-09-23 03:09 UTC, alanpoon commented on src/home/room_screen.rs
> +                    if *index != first_index{
fixed

2024-09-23 03:14 UTC, alanpoon commented on src/home/room_screen.rs
> +                            for r in tl_state.content_drawn_since_last_update.clone(){
Replaced with iterating over a range first_index and first_index + visible_items(). For loop is to give a timestamp to each message. So that I would know if the message has been displayed for more than 5 seconds to fulfill the condition for fully_read.

2024-09-23 03:15 UTC, alanpoon commented on src/home/room_screen.rs
> +                                        }
fixed- submit_async_request will now be called for the last event's read receipt.

2024-09-23 03:16 UTC, alanpoon commented on src/sliding_sync.rs
> +        message:String,
removed message

2024-09-23 03:16 UTC, alanpoon commented on src/sliding_sync.rs
> +                        Err(_e) => error!("Failed to send message to room {room_id}: {_e:?}"),
fixed

2024-09-23 03:21 UTC, alanpoon commented on src/home/room_screen.rs
> +    marked_fully_read_queue:HashMap<String,(OwnedRoomId,OwnedEventId)>,
I must have been confused with the requirement of implementing fully_read receipt when a message is scrolled out of view above the top of the timeline view together with e.g., when the message is displayed on screen for more than 5 or 10 seconds. I've implemented both; scrolled out of view after the message is displayed on screen for more than 5 or 10 seconds. Let me know which case you would like. I have also noted that element web implements fully-read when user clicks the pointed-up arrow to scroll the last fully read receipt position.

2024-10-01 05:07 UTC, kevinaboos approved these changes
I did some minor cleanup just to improve readability, so take a look at those minor changes to see what sort of code style and whitespace conventions we're looking for. The logic for tracking which events have been read is still needlessly complicated, and also rather inefficient, especially with the repeated population of big hashmaps and subsequent iteration over them. 
I still believe that all you really need to do is start a 5-second timeout timer whenever scrolling stops, and then after the timer has reached its timeout deadline, send the read receipts for the last visible event.

That being said, your approach technically works despite being overly complicated, so in the interest of time I'm going to accept and merge it in, and we'll save other improvements for the future. 

I left a few comments that mostly target C vs Rust coding styles and inefficiencies scattered throughout. 

Please submit another PR to clean things up in the future.

2024-10-01 05:07 UTC, kevinaboos commented on src/home/room_screen.rs
> +                                }
the operation of "iterating over hashmap entries and then optionally removing some of them" is covered by the `drain` and `retain` collections APIs, which are _much_ more efficient than the allocation-heavy code you've got here.

2024-10-01 05:07 UTC, kevinaboos commented on src/home/room_screen.rs
> +                                if !tl_state.read_event_hashmap.contains_key(&e.to_string()) {
the code pattern of "if map doesn't contain a key, then insert it" is better handled by the `Entry` API, which is much more efficient. 
https://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html#method.entry

2024-10-01 05:07 UTC, kevinaboos commented on src/home/room_screen.rs
> +                            for r in tl_state.content_drawn_since_last_update.clone(){
well this works, but it's still too complicated. See my top-level review comment.

2024-10-01 05:07 UTC, kevinaboos commented on src/home/room_screen.rs
> +    marked_fully_read_queue:HashMap<String,(OwnedRoomId,OwnedEventId)>,
either one is fine, there's no real need to define every possible policy here. For now let's just focus on the mechanism of determining whether a given criteria has been met and sending read receipts based on that criteria. We can add additional criteria later.

2024-10-01 05:24 UTC, merged

2024-10-03 15:51 UTC, alanpoon commented on src/home/room_screen.rs
> +                    for r in first_index .. (first_index + portal_list.visible_items() + 1) {
Ok, will be working on this soon