Add read receipt display
project-robius/robrix pull request #162
Opened 2024-09-26 11:38 UTC by alanpoon

https://github.com/project-robius/robrix/issues/153

1. With tooltip indicating number of seen - mouse over
<img width="272" alt="read_r_tooltip" src="https://github.com/user-attachments/assets/d02d972a-08a4-487b-9eda-b412213bff2f">

2. mouse out
<img width="276" alt="read_receipt" src="https://github.com/user-attachments/assets/d73a6ec3-447f-4f80-992e-71307109b42e">

- Currently only supports Avatar with username. I need some advice how to put in Avatar with image.
- Implemented max display of 4 avatars

2024-09-28 12:32 UTC, alanpoon commented
[WIP] Will try to change sequencer to follow GenUI's way of creating a list of widgets

2024-10-10 06:52 UTC, alanpoon commented
<img width="365" alt="avatar read_receipt" src="https://github.com/user-attachments/assets/f9b4820c-4805-48c3-92db-852dd4f3ee2c">

1. Modified set_avatar_and_get_username function to use &mut Avatar instead of AvatarRef
2. Modified set_avatar_and_get_username function to take in an option of Avatar User profile. Read_receipts do not provide user profile. So the User Profile is gotten from the Sender cache.
3. Added Caching for Avatar that is loaded with Image.

2024-10-31 19:02 UTC, kevinaboos requested changes
A great start, thanks! 

I suggested some minor API changes that will make things clearer and less error-prone. After those changes are made, it should be ready to merge.

2024-10-31 19:02 UTC, kevinaboos commented on src/home/room_screen.rs
> +            }
Also, redesigning this function as suggested above would also likely avoid the need to refactor `set_avatar_and_get_username`, but that's less important.

2024-11-04 15:02 UTC, alanpoon commented on src/home/room_read_receipt.rs
> +    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, Avatar> {
@kevinaboos https://github.com/project-robius/robrix/pull/162/files#r1825029789
I cannot return iterateMut over AvatarRef. I can only return a iterateMut over &mut Avatar.

``` self.avatar_set(id!(...)) ``` requires a list of ids, which I do not know how to set.
That's why I am using &mut Avatar.

2024-11-04 15:11 UTC, alanpoon commented on src/home/room_screen.rs
> +            }
> this seems like an error-prone and fragile way to implement this. Instead of separately setting the range and then exposing an iterator over the inner avatar button `Vec` (via `iter_mut()`), you should just expose a function called `set_avatars()` or something that directly accepts the `receipts` object here. Then, move all of this logic into that function.
> 
> That's much better code encapsulation and also reduces the likelihood of future developer misuse/misunderstanding of your `range` API. It also allows removing the `count` field, which as I stated in my other comment, doesn't seem necessary or useful.

I am trying to re-use function ``` set_avatar_and_get_username```. I think eventually, I will also need to explore exposing a mutable reference of children widgets so that the AvatarRow is more composable than ```set_avatars()```. If not, there's duplicate code inside AvatarRow widget and the one without the Row. I will try to remove the ```count```.

2024-11-04 15:16 UTC, alanpoon commented on src/home/room_screen.rs
> +            )
I am changing the argument "sender_user_id" to a more generic user:  "avatar_user_id". Previously, there is sender's profile when receiving the message. But since, read receipts only have user_ids and not have user profile, and I want to use pass their user_ids here.

2024-11-04 15:37 UTC, alanpoon commented on src/profile/user_profile_cache.rs
> +pub fn set_user_profile(
Read receipts do not contain user_profile. I am caching sender_profile first, so that I can reuse the profile for displaying avatar for the read receipt. Currently in this PR, there won't be image avatar for room members who did not send any message during that timeline even though they have image display picture.

2024-11-04 23:12 UTC, kevinaboos commented on src/home/room_screen.rs
> +            )
then kindly maintain formatting unless it is absolutely mandatory to change it. Feel free to submit formatting fixes as a separate PR.

2024-11-04 23:15 UTC, kevinaboos commented on src/profile/user_profile_cache.rs
> +pub fn set_user_profile(
I understand what you're doing; I'm asking why this is needed or desired. I'm also arguing that this function is unnecessary. 

If the read receipt content does not contain user profile info, then we should use the existing caching infrastructure for user profiles, which is exactly why I created it in the first place. You simply attempt to get the info from the cache; if it is not there, then the cache will fire off an async request to fetch that user profile info. Then, the next time you attempt to access it from the cache (e.g., upon a redraw), then it will be there.

2024-11-04 23:27 UTC, kevinaboos commented on src/home/room_read_receipt.rs
> +    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, Avatar> {
I understand what you're saying, but sorry, this isn't the correct way to use widgets AFAICT, at least from what I have learned about Makepad's intended design patterns.

Not sure why you're replying in a different comment (which makes our conversation hard to follow), but you seem to have missed my [primary argument here](https://github.com/project-robius/robrix/pull/162#discussion_r1825036251). To re-summarize:
* this function `iter_mut()` should not even be necessary at all. Remove it.
* The `count` field of `AvatarRow` should be removed.
* The `set_range()` function should be removed
* Optionally, `buttons` in `AvatarRow` could store a `Vec<AvatarRef>` instead of `Avatar` directly. 
* You should add a new function called something like `set_avatar_row()`, which basically does the following:
```rust
       fn set_avatar_row(&mut self, receipts_iter: &IndexMap<OwnedUserId, Receipt> {
            let seq = self.avatar_row(id!(avatar_row));
            if let Some(ref mut v)= seq.borrow_mut() {
                for avatar in &self.buttons ( // TODO: use .zip to combine these two iterators in a Rust-y way
                    if let Some((user, r)) = receipt_iter.next() {
                        set_avatar_and_get_username(cx, avatar, room_id, user, None, event_tl_item.event_id());
                    }
                }
            }
```

To more effectively re-use `set_avatar_and_get_username()`, we could implement it as a method on the actual `AvatarRef` and `Avatar` types, which means you could call it on both an instance/reference to either `Avatar` or `AvatarRef`.
Once we do that, the code above would look more like
```rust
avatar.set_avatar_and_get_username(cx, room_id, user, ...)
```

2024-11-04 23:28 UTC, kevinaboos commented on src/home/room_read_receipt.rs
> +    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, Avatar> {
if this isn't clear, just let me know and i could throw it together in code for you. It'd probably be faster & easier to do that than attempt to re-re-explain the design issues here.

2024-11-04 23:28 UTC, kevinaboos commented on src/home/room_screen.rs
> +            }
see my final response below.

2024-11-05 16:05 UTC, alanpoon commented on src/home/room_read_receipt.rs
> +    count: usize,
I will try to remove the ```count```. But the intention is that if there are 100 people seen it, and I don't want to draw / save all their avatars. I only want to draw about 5, but the mouse over needs to display 100 people seen it.

2024-11-06 15:11 UTC, alanpoon commented on src/home/room_screen.rs
> +            )
reverted format

2024-11-06 15:25 UTC, alanpoon commented on src/home/room_screen.rs
> +    avatar: &mut Avatar,
Changed back to AvatarRef

2024-11-07 05:47 UTC, alanpoon commented on src/home/room_read_receipt.rs
> +    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, Avatar> {
moved set_avatar_and_get_username function into shared::avatar.

2024-11-07 19:40 UTC, kevinaboos requested changes
Thanks for refactoring the code; it does look nicer now. 

I'm not sure how thoroughly you tested this, but I experience quite a few bugs or odd behaviors on my machine when testing it. 

First, the on-hover tooltip is frequently cut off, so let's reposition that differently.
<img width="152" alt="image" src="https://github.com/user-attachments/assets/862f63f5-9eaa-4f67-94f7-26cc3f4dddce">

Second, the tooltip also doesn't disappear properly when you hover out of the avatar row: 
<img width="242" alt="image" src="https://github.com/user-attachments/assets/af37db7c-1fe4-4dc5-a4d3-a1c73b4edc0c">


Third, the log is absolutely _filled_ with these messages:
```
src/sliding_sync.rs:433:21 - Sending get user profile request: ...
```
which indicates that you're not correctly using the user profile cache, as I see tons of duplicate requests. If you use the cache correctly (and do not re-draw the AvatarRow _until_ a cache update is received), then you should see only one request ***max*** per unknown user ID.

Finally, and most importantly, the displayed read receipt info is actually incorrect and/or incomplete. If you scroll through any larger public room (e.g., Element Web/Desktop, Matrix HQ, etc) you'll see a total mismatch between the read receipts displayed on Robrix and the read receipts displayed by Element in the same room. Not sure what you're doing to cause this, but please look into the correctness/accuracy of the read receipts. Perhaps they're not getting updated? 

Read receipts also seem to be completely _missing_ for quite a few messages: I see them in Element but not in Robrix. Please investigate; this is probably related to the above issue too.

Finally, address all the compiler warnings that your PR has added (the main branch currently has 5 warnings, which you can ignore).

2024-11-07 19:40 UTC, kevinaboos commented on src/shared/avatar.rs
> +    avatar: AvatarRef,
i think you missed my point that this should be a _method_ implemented on the `Avatar` type, with a typical WidgetRef-style wrapper that is implemented for `AvatarRef` and just calls this inner function. That is the canonical Makepad way of doing things.

2024-11-07 19:40 UTC, kevinaboos commented on src/shared/avatar.rs
> +    fn hit(&mut self, cx: &mut Cx, event: &Event, sweep_area: Area) -> Hit {
the docs and/or function name here need to be improved, because I can't understand what this function is doing or how I should be using it just by reading the docs alone (which is the goal).

2024-11-07 19:40 UTC, kevinaboos commented on src/shared/avatar.rs
> +    pub fn hit(&mut self, cx: &mut Cx, event: &Event, sweep_area: Area) -> Option<Hit> {
same comment here: 
the docs and/or function name here need to be improved, because I can't understand what this function is doing or how I should be using it just by reading the docs alone (which is the goal).

2024-11-07 19:40 UTC, kevinaboos commented on src/home/room_screen.rs
> +                    .avatar(id!(replied_to_message_content.reply_preview_avatar)),
the indentation was previously correct, please undo.

2024-11-07 19:40 UTC, kevinaboos commented on src/home/room_read_receipt.rs
> +    fn set_range(&mut self, cx: &mut Cx, total_num_seen: usize) {
I still don't understand _why_ we need this function ... see my other review comment within `fn set_avatar_row()`.

Having this as a separate function invites someone to accidentally invoke it without understanding what other steps need to be simultaneously undertaken, i.e., it's easy to mis-use this. 

All of this is just a fancy way of saying "use defensive programming techniques", in which you employ a design/implementation strategy that _prevents_ a developer from accidentally making mistakes (yourself included). That is one of Rust's design goals as well.

2024-11-07 19:40 UTC, kevinaboos commented on src/home/room_read_receipt.rs
> +        where T:Iterator<Item = (&'a OwnedUserId, &'a Receipt)> {
this function can be simplified in two ways.
1. There's no need for generics here. Just directly accept the IndexMap of read receipts, which will also allow you do to number 2 below.
2. Remove the `receipts_len` parameter, since that is completely unnecessary and error-prone, as it's separate from (and redundant with) the `IndexMap` of read receipts.

2024-11-07 19:40 UTC, kevinaboos commented on src/home/room_read_receipt.rs
> +        for button in self.buttons.iter_mut() {
isn't this a very expensive way to check for a hit? Surely we should just be checking the full area of the AvatarRow as a single "whole" entity, instead of checking each button. 

Unless, that is, you're going to allow each mini avatar in the AvatarRow to be individually-clickable ... which is fine, but I don't think you're doing that.

2024-11-07 19:40 UTC, kevinaboos commented on src/home/room_read_receipt.rs
> +        if self.total_num_seen > 5 {
extract this `5` into a const and place that const at the top of this file. You can name it `MAX_VISIBLE_AVATARS_IN_READ_RECEIPT_ROW` or something similar.

See the programming rule of [no magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)).

2024-11-07 19:40 UTC, kevinaboos commented on src/home/room_read_receipt.rs
> +            inner.set_range(cx, receipts_len);
set_range should not be a separate function, as that overcomplicates the API. You should directly set the `total_num_seen` within this `set_avatar_row()` fn based on the `len()` of the read receipts `IndexMap`, as that guarantees that the value will always be correct/accurate.

2024-11-07 19:40 UTC, kevinaboos commented on src/home/room_screen.rs
> +            avatar_row = <AvatarRow> {width: 40, height: 30, margin: { top: (12.0) }, hover_actions_enabled:true }
formatting fixes
```suggestion
            avatar_row = <AvatarRow> {
                width: 40,
                height: 30,
                margin: { top: (12.0) },
                hover_actions_enabled: true,
            }
```

2024-12-09 08:20 UTC, alanpoon commented on src/shared/avatar.rs
> +    avatar: AvatarRef,
Fixed

2024-12-09 08:27 UTC, alanpoon commented on src/shared/avatar.rs
> +    fn hit(&mut self, cx: &mut Cx, event: &Event, sweep_area: Area) -> Hit {
fixed

2024-12-09 10:31 UTC, alanpoon commented on src/home/room_read_receipt.rs
> +        where T:Iterator<Item = (&'a OwnedUserId, &'a Receipt)> {
fixed

2024-12-09 10:32 UTC, alanpoon commented on src/home/room_read_receipt.rs
> +        for button in self.buttons.iter_mut() {
Fixed

2024-12-09 10:34 UTC, alanpoon commented on src/home/room_read_receipt.rs
> +        if self.total_num_seen > 5 {
fixed

2024-12-09 10:36 UTC, alanpoon commented on src/home/room_read_receipt.rs
> +            inner.set_range(cx, receipts_len);
fixed

2024-12-10 08:39 UTC, alanpoon commented on src/home/room_read_receipt.rs
> +    fn set_range(&mut self, cx: &mut Cx, total_num_seen: usize) {
Removed

2024-12-19 23:41 UTC, kevinaboos requested changes
this is a code-only review; i haven't tested the runtime behavior again yet.

2024-12-19 23:41 UTC, kevinaboos commented on src/home/room_screen.rs
> +    HoverIn(Rect, String, f64),
use a structured enum variant for this, like so:
```suggestion
    /// The mouse is hovering over the ??? (see below)
    HoverIn {
        tooltip_pos: Rect,
        tooltip_text: String,
        tooltip_width: f64,
```

Two questions:
1. you wrote "over the reaction button", but I assume you meant "over the row of read receipt Avatars"?
2. If you already have the `Rect`, why do you need a separate `width` value for the tooltip?

2024-12-19 23:41 UTC, kevinaboos commented on src/utils.rs
> +/// assert_eq!(human_readable_list(vec!["Alice", "Bob", "Charlie"]), "Alice, Bob\n and Charlie");
i don't think the `\n` after "Bob" is correct?

2024-12-19 23:41 UTC, kevinaboos commented on src/utils.rs
> +pub fn human_readable_list(names: Vec<String>) -> String {
to be more useful, this should accept a slice of S where S: AsRef<str>, instead of a Vec.

2024-12-19 23:41 UTC, kevinaboos commented on src/sliding_sync.rs
> +    handle_sync_once(client.clone());
if possible, we should avoid doing this. This uses the old sync API, not sliding sync, so it will likely be massively slow, and generally a bad idea since it will kind of diminish the point of using sliding sync (to not overload the server with huge high-bandwidth requests)

2024-12-19 23:41 UTC, kevinaboos commented on src/sliding_sync.rs
> +    handle_sync_once(client.clone());
are you 100% positive this is actually necessary?

if so, let me know, and we can reach out to the Matrix SDK team to ask them why.

2024-12-19 23:41 UTC, kevinaboos commented on src/home/room_screen.rs
> +            item.avatar_row(id!(avatar_row)).set_avatar_row(cx, room_id, event_tl_item.event_id(), event_tl_item.read_receipts());
is there any reason we call this dozens of times in each individual case? can't we just invoke it once in a shared bit of code?

2024-12-19 23:41 UTC, kevinaboos commented on src/shared/avatar.rs
> +    ///    (for purposes of caching it to avoid future redraws).
as with all other widget functions, please move the detailed doc comments to the inner function, and then have these outer functions link to those. See how we do it in all other functions.

2024-12-20 04:23 UTC, alanpoon commented on src/utils.rs
> +/// assert_eq!(human_readable_list(vec!["Alice", "Bob", "Charlie"]), "Alice, Bob\n and Charlie");
fixed

2024-12-20 04:29 UTC, alanpoon commented on src/utils.rs
> +pub fn human_readable_list(names: Vec<String>) -> String {
fixed

2024-12-20 04:46 UTC, alanpoon commented on src/home/room_screen.rs
> +            item.avatar_row(id!(avatar_row)).set_avatar_row(cx, room_id, event_tl_item.event_id(), event_tl_item.read_receipts());
fixed

2024-12-20 06:59 UTC, alanpoon commented on src/shared/avatar.rs
> +    ///    (for purposes of caching it to avoid future redraws).
fixed

2024-12-22 14:12 UTC, alanpoon commented on src/sliding_sync.rs
> +    handle_sync_once(client.clone());
I have run out of ideas how to fix read receipts discrepancy without sync_once. Just adding client.event_handler does not work.

2024-12-26 21:23 UTC, kevinaboos commented on src/sliding_sync.rs
> +    handle_sync_once(client.clone());
ok, we'll keep it in for now.

2024-12-26 21:24 UTC, kevinaboos commented
is this ready for another review? i noticed you made some changes but didn't change the `waiting-on-*` label nor request another review from me

2024-12-28 04:15 UTC, alanpoon commented
> is this ready for another review? i noticed you made some changes but didn't change the `waiting-on-*` label nor request another review from me

Not ready at the moment, sync_once is throwing error. 'extensions.to_device.since' is invalid (should look like an int) (type=value_error). Initially I thought by moving it after sync service.start would resolve the issue, but it didn't. The backend is expecting url parameter "Since" to be timestamp, but it is sending string. I am not finding the same issue with a separate matrix test repository.

2024-12-28 08:31 UTC, kevinaboos commented
> sync_once is throwing error. 'extensions.to_device.since' is invalid (should look like an int) (type=value_error). Initially I thought by moving it after sync service.start would resolve the issue, but it didn't. The backend is expecting url parameter "Since" to be timestamp, but it is sending string. 

Yea that sounds like what I would expect, since we're not supposed to use that API because we're using sliding sync instead. I was surprised that it ever worked.

> I am not finding the same issue with a separate matrix test repository.

probably because you're not saving and restoring a session that was created via sliding sync, i presume?

2024-12-28 08:32 UTC, kevinaboos commented
I think you should reach out to the Matrix SDK developers on the matrix room for that, and ask them about the issue you mentioned here: https://github.com/project-robius/robrix/pull/162#discussion_r1894946412

There must be a way to get this to work correctly with sliding sync. At the very least, Element X probably has this feature working, so we could also reach out to them on the Element X matrix rooms.

2024-12-31 20:32 UTC, kevinaboos commented
@alanpoon i see you marked this as "blocked". Are you considering this blocked on Matrix SDK features? or you're waiting to hear back from the SDK dev team? (I haven't seen any conversations from you on the Matrix Rust SDK room...)

If so, kindly take a look at Element X's source code (either Android or iOS, whichever one you prefer) to see what they do to make read receipts work.

2025-01-01 00:48 UTC, alanpoon commented
> @alanpoon i see you marked this as "blocked". Are you considering this blocked on Matrix SDK features? or you're waiting to hear back from the SDK dev team? (I haven't seen any conversations from you on the Matrix Rust SDK room...)
> 
> If so, kindly take a look at Element X's source code (either Android or iOS, whichever one you prefer) to see what they do to make read receipts work.

I asked in the matrix chat room. https://matrix.to/#/!IlysflVuQZDIcVLkcg:matrix.org/$3VJtkdI0yxVnlAMzh42q7lPl1MtrUzz6KxUmibpLUtM?via=matrix.org&via=element.io&via=envs.net

It seems like sync_once does not throw error, after deleting the Robius's local data. Hence I am requesting another review.

Element X Android's code is ```
        client.getRoom(notifiableEvent.roomId)?.use { room ->
            room.subscribeToSync()

            // If the app is in foreground, sync is already running, so just add the subscription.
            if (!appForegroundStateService.isInForeground.value) {
                val syncService = client.syncService()
                syncService.startSyncIfNeeded()
                if (isRingingCallEvent) {
                    room.waitsUntilUserIsInTheCall(timeout = 60.seconds)
                } else {
                    room.waitsUntilEventIsKnown(eventId = notifiableEvent.eventId, timeout = 10.seconds)
                }
                syncService.stopSyncIfNeeded()
            }
        }
```
Their android's SDK is syncService.startSync, while rust is just SyncService.start(). So it can be hard to compare.

https://docs.rs/matrix-sdk-ui/0.7.0/matrix_sdk_ui/sync_service/struct.SyncService.html

2025-01-01 01:15 UTC, kevinaboos commented
> I asked in the matrix chat room. https://matrix.to/#/!IlysflVuQZDIcVLkcg:matrix.org/$3VJtkdI0yxVnlAMzh42q7lPl1MtrUzz6KxUmibpLUtM?via=matrix.org&via=element.io&via=envs.net

oh ok, great. I did not know about that room.

You should also ask the question in the [room dedicated to the Matrix Rust SDK itself](https://matrix.to/#/#matrix-rust-sdk:matrix.org), since this problem seems to be related to the SDK rather than sliding sync or the spec. Specifically, be sure to mention that we're using the new SyncService and that it seems strange/wrong that we'd need to completely bypass the sliding sync protocol in order to make a full `sync_once()` call.

> It seems like sync_once does not throw error, after deleting the Robius's local data. Hence I am requesting another review.

Ah ok, that's interesting. It's probably due to the fact that the sessions that get saved to disk (and subsequently restored), so if you try to restore a pure SlidingSync-based session but treat it as a traditional-sync session, then it's not going to work well. The inverse of that is also true.

I'd still like to _avoid_ having to call `sync_once()` simply because it is massively expensive and defeats the entire purpose of using sliding sync in the first place....

------------

> Element X Android's code is
> ```
>         client.getRoom(notifiableEvent.roomId)?.use { room ->
>             room.subscribeToSync()
> 
>             // If the app is in foreground, sync is already running, so just add the subscription.
>             if (!appForegroundStateService.isInForeground.value) {
>                 val syncService = client.syncService()
>                 syncService.startSyncIfNeeded()
>                 if (isRingingCallEvent) {
>                     room.waitsUntilUserIsInTheCall(timeout = 60.seconds)
>                 } else {
>                     room.waitsUntilEventIsKnown(eventId = notifiableEvent.eventId, timeout = 10.seconds)
>                 }
>                 syncService.stopSyncIfNeeded()
>             }
>         }
> ```
> 
> Their android's SDK is syncService.startSync, while rust is just SyncService.start(). So it can be hard to compare.

If you dig a bit deeper, you'll see that they're just directly calling `SyncService.start()` via Rust SDK bindings: https://github.com/element-hq/element-x-android/blob/55a5d45d4fb446a84dc96d4305b559f84bc68ee4/libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/sync/RustSyncService.kt#L38

So in summary, Element X appears to _not_ need to call the expensive bloated `sync_once()` function, as I suspected. Please investigate this further to see if we _truly_ must call `sync_once()`, because I definitely think it shouldn't be required (at least theoretically).

2025-01-01 01:33 UTC, kevinaboos commented
A final thought below:

> > It seems like sync_once does not throw error, after deleting the Robius's local data. Hence I am requesting another review.
> 
> Ah ok, that's interesting. It's probably due to the fact that the sessions that get saved to disk (and subsequently restored), so if you try to restore a pure SlidingSync-based session but treat it as a traditional-sync session, then it's not going to work well. The inverse of that is also true.

Based on this, we actually _cannot_ call `sync_once()` at all, as it will break Robrix's expectations of a pure-SlidingSync implementation. Thus, we need to find another way to forcibly synchronize the read receipt state of each room that gets opened (if that's the solution for this).

2025-01-01 01:50 UTC, kevinaboos commented
I also just confirmed that we do enable `track_read_marker_and_receipts()` when building each room's `Timeline` instance, so that's thankfully not the problem.

2025-01-02 07:43 UTC, alanpoon commented
> A final thought below:
> 
> > > It seems like sync_once does not throw error, after deleting the Robius's local data. Hence I am requesting another review.
> > 
> > 
> > Ah ok, that's interesting. It's probably due to the fact that the sessions that get saved to disk (and subsequently restored), so if you try to restore a pure SlidingSync-based session but treat it as a traditional-sync session, then it's not going to work well. The inverse of that is also true.
> 
> Based on this, we actually _cannot_ call `sync_once()` at all, as it will break Robrix's expectations of a pure-SlidingSync implementation. Thus, we need to find another way to forcibly synchronize the read receipt state of each room that gets opened (if that's the solution for this).

I've checked the element X android http request using emulator. It does also call /sync without `pos` parameter and with a timeout of 30 seconds. This suggests a sync_once api call. This request is missing in our current implementation. I don't think this will affect the performance as app handles the case of sync_once failing.

![element_x](https://github.com/user-attachments/assets/3565d3aa-b99c-4797-add3-b3a6887490f3)

The possible error of implementing sync_once,`'extensions.to_device.since' is invalid ` is likely a bug in the rust matrix-sdk-client since it is a parameter type error.

2025-01-02 18:15 UTC, kevinaboos commented
> I've checked the element X android http request using emulator. It does also call /sync without `pos` parameter and with a timeout of 30 seconds. This suggests a sync_once api call. This request is missing in our current implementation. I don't think this will affect the performance as app handles the case of sync_once failing.
> 
> ![element_x](https://private-user-images.githubusercontent.com/8205468/399639108-3565d3aa-b99c-4797-add3-b3a6887490f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NDE2NDIsIm5iZiI6MTczNTg0MTM0MiwicGF0aCI6Ii84MjA1NDY4LzM5OTYzOTEwOC0zNTY1ZDNhYS1iOTljLTQ3OTctYWRkMy1iM2E2ODg3NDkwZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDJUMTgwOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRjNTg0ZmUwMjQzY2VjMmI0ODA2NmIwMTkzZWU2ZWZmYTIwMTQ4OWNkYWI1ODE0NWJiOWY0ZDllYTI2NmZjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.twUu6ruMT9HDgS1egdeWkySx0xTfy37hdXJ4co12JEc)

Thanks for digging into it. I'm not disagreeing with you necessarily, but what your screenshot shows is a call to the SlidingSync `sync` endpoint (actually two of them, but yes). Note the `simplified_msc3575` part, which refers to simplified (native) SlidingSync. 

Is that the same as what `sync_once()` does, as in, does it also call the simplified_msc3575 `sync` endpoint? Please confirm this, because I thought it called the old original `sync` endpoint. 

> The possible error of implementing sync_once,`'extensions.to_device.since' is invalid ` is likely a bug in the rust matrix-sdk-client since it is a parameter type error.

I've received this error before, I don't think it's a bug but rather an error that occurs when you try to restore an old session that was generated with a previous version of the SDK or different sync configuration that isn't compatible with the current one.

2025-01-14 03:48 UTC, alanpoon commented
> > I've checked the element X android http request using emulator. It does also call /sync without `pos` parameter and with a timeout of 30 seconds. This suggests a sync_once api call. This request is missing in our current implementation. I don't think this will affect the performance as app handles the case of sync_once failing.
> > ![element_x](https://private-user-images.githubusercontent.com/8205468/399639108-3565d3aa-b99c-4797-add3-b3a6887490f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NDE2NDIsIm5iZiI6MTczNTg0MTM0MiwicGF0aCI6Ii84MjA1NDY4LzM5OTYzOTEwOC0zNTY1ZDNhYS1iOTljLTQ3OTctYWRkMy1iM2E2ODg3NDkwZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDJUMTgwOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRjNTg0ZmUwMjQzY2VjMmI0ODA2NmIwMTkzZWU2ZWZmYTIwMTQ4OWNkYWI1ODE0NWJiOWY0ZDllYTI2NmZjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.twUu6ruMT9HDgS1egdeWkySx0xTfy37hdXJ4co12JEc)
> 
> Thanks for digging into it. I'm not disagreeing with you necessarily, but what your screenshot shows is a call to the _SlidingSync `sync` endpoint_ (actually two calls, but yes). Note the `simplified_msc3575` part, which refers to simplified (native) SlidingSync.
> 
> Is that the same as what `sync_once()` does, as in, does it also call the simplified_msc3575 `sync` endpoint? Please confirm this, because I thought it called the old original `sync` endpoint.
> 
> > The possible error of implementing sync_once,`'extensions.to_device.since' is invalid ` is likely a bug in the rust matrix-sdk-client since it is a parameter type error.
> 
> I've received this error before, I don't think it's a bug but rather an error that occurs when you try to restore an old session that was generated with a previous version of the SDK or different sync configuration that isn't compatible with the current one.

You are right. Sync_once corresponds to client/v3/sync?timeout=30000 which is not found in element X android app.
Let me check again. 
![Screenshot 2025-01-14 at 11 41 35 AM](https://github.com/user-attachments/assets/325e70ee-2b70-4b1e-b735-657956874f9a)

2025-01-14 06:49 UTC, kevinaboos commented
> You are right. Sync_once corresponds to client/v3/sync?timeout=30000 which is not found in element X android app. Let me check again. ![Screenshot 2025-01-14 at 11 41 35 AM](https://private-user-images.githubusercontent.com/8205468/402796115-325e70ee-2b70-4b1e-b735-657956874f9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4Mzc2MjgsIm5iZiI6MTczNjgzNzMyOCwicGF0aCI6Ii84MjA1NDY4LzQwMjc5NjExNS0zMjVlNzBlZS0yYjcwLTRiMWUtYjczNS02NTc5NTY4NzRmOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTRUMDY0ODQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGZlMjFiZDFlNzA5ZjZkM2Q4YWZmN2JjODY3YjQzNzEzMWU5NWFlYTNhYjMwNmM2OGI4ZDdhZDc4Y2M4NjNkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Zj6WR4PcP1wriL8C85_oTJ_aPU8_HfQYRwrQOlIjbS4)

Thanks for confirming. Let me know if you find out any more info.

2025-01-14 10:17 UTC, alanpoon commented
> > You are right. Sync_once corresponds to client/v3/sync?timeout=30000 which is not found in element X android app. Let me check again. ![Screenshot 2025-01-14 at 11 41 35 AM](https://private-user-images.githubusercontent.com/8205468/402796115-325e70ee-2b70-4b1e-b735-657956874f9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4Mzc2MjgsIm5iZiI6MTczNjgzNzMyOCwicGF0aCI6Ii84MjA1NDY4LzQwMjc5NjExNS0zMjVlNzBlZS0yYjcwLTRiMWUtYjczNS02NTc5NTY4NzRmOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTRUMDY0ODQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGZlMjFiZDFlNzA5ZjZkM2Q4YWZmN2JjODY3YjQzNzEzMWU5NWFlYTNhYjMwNmM2OGI4ZDdhZDc4Y2M4NjNkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Zj6WR4PcP1wriL8C85_oTJ_aPU8_HfQYRwrQOlIjbS4)
> 
> Thanks for confirming. Let me know if you find out any more info.

I have found the function to sync the room's read receipts. https://docs.rs/matrix-sdk-ui/0.9.0/matrix_sdk_ui/room_list_service/struct.RoomListService.html#method.subscribe_to_rooms.

The `room_subscription` was previously in the http request payload.
![Screenshot 2025-01-14 at 4 56 22 PM](https://github.com/user-attachments/assets/f91c944f-fe91-4cc6-a749-54dd137bcc88)

2025-01-14 21:01 UTC, kevinaboos approved these changes
Thanks for digging into the issue with the lack of full room state synchronization! Very nice work figuring that out.

I've left a few minor comments. Once those are addressed, this PR will be ready to merge in.

2025-01-14 21:01 UTC, kevinaboos requested changes
oops, i mean to request changes, not approve. See above review.

2025-01-15 02:10 UTC, alanpoon commented on src/home/room_read_receipt.rs
> +                let tooltip_pos = if finger_event.abs.x > cx.default_window_size().x - TOOLTIP_LENGTH {
Removed

2025-01-15 02:12 UTC, alanpoon commented on src/home/room_screen.rs
> +            }
removed

2025-01-15 02:26 UTC, alanpoon commented on src/home/room_screen.rs
> +                margin: { right: 73 }
changed to 80

2025-01-15 10:35 UTC, alanpoon commented on src/home/room_screen.rs
> +                margin: { right: 73 }
Removed this margin

2025-01-16 08:33 UTC, alanpoon commented
Merged in main

2025-01-16 21:12 UTC, kevinaboos requested changes
The code structure looks all good to me. There are just a few UI issues:

1. The RoomScreen is only filling half of the height of the window, similar to your other PR. Probably the same issue with the room screen tooltip?
2. It takes a _really_ long time for the AvatarRow to actually show the profile pictures after the user profile request completes. I bet we're missing a UI Signal or something that would trigger a redraw of that AvatarRow, so please look into that.
3. The tooltip shows the correct total count of people that have seen the message, but then incorrectly lists only the first 5 names. We should either display the entire list of all user names, or if you want to show only 5, then you should say "Seen by 8 people: A, B, C, D, E, and 3 more". Otherwise the user will think there's an odd math mistake.

    Also, the word "people" is missing, i.e., it should be "Seen by 8 people: ...".
<img width="174" alt="image" src="https://github.com/user-attachments/assets/2f76e908-5704-4ae6-a89e-716680ef0f68" />

4. The right-side margin used for the read receipt's Avatar Row is causing a lot of horizontal empty space on the right side of the RoomScreen. We're now wasting like 80 or so pixels of space there, so please fix that. Here's a screenshot of what I'm referring to:
    <img width="814" alt="image" src="https://github.com/user-attachments/assets/c37f6b4e-b5d9-4ae5-89a0-53890b09c084" />

2025-01-16 21:16 UTC, kevinaboos commented
Ok I found the problem to (1) above -- you just needed to move the `room_screen_tooltip` inside of the `room_screen_wrapper` view, not beneath it. Probably just an accident.

<img width="700" alt="image" src="https://github.com/user-attachments/assets/532e071f-67f6-43e6-bc65-a616d57283e9" />

2025-01-21 05:59 UTC, alanpoon commented
> The code structure looks all good to me. There are just a few UI issues:
> 
> 1. The RoomScreen is only filling half of the height of the window, similar to your other PR. Probably the same issue with the room screen tooltip?
> 2. It takes a _really_ long time for the AvatarRow to actually show the profile pictures after the user profile request completes. I bet we're missing a UI Signal or something that would trigger a redraw of that AvatarRow, so please look into that.
> 3. The tooltip shows the correct total count of people that have seen the message, but then incorrectly lists only the first 5 names. We should either display the entire list of all user names, or if you want to show only 5, then you should say "Seen by 8 people: A, B, C, D, E, and 3 more". Otherwise the user will think there's an odd math mistake.
>    Also, the word "people" is missing, i.e., it should be "Seen by 8 people: ...".
> 
> <img alt="image" width="174" src="https://private-user-images.githubusercontent.com/1139460/404039305-2f76e908-5704-4ae6-a89e-716680ef0f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0Mzk0MjksIm5iZiI6MTczNzQzOTEyOSwicGF0aCI6Ii8xMTM5NDYwLzQwNDAzOTMwNS0yZjc2ZTkwOC01NzA0LTRhZTYtYTg5ZS03MTY2ODBlZjBmNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjFUMDU1ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTY0YzI4MWU3OThkMmRjNzQxZDU1ZjkxMjFiMjUxOGM3N2U3YjU2YTA1NTRlYWJhMjRmMDI1Yzg1YzA4MjY5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RmsixGq6U84gHq-6lADsg9ZBaMj1Q0cFePyrERZ5Fi4">
> 4. The right-side margin used for the read receipt's Avatar Row is causing a lot of horizontal empty space on the right side of the RoomScreen. We're now wasting like 80 or so pixels of space there, so please fix that. Here's a screenshot of what I'm referring to:
>    <img alt="image" width="814" src="https://private-user-images.githubusercontent.com/1139460/404040494-c37f6b4e-b5d9-4ae5-89a0-53890b09c084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0Mzk0MjksIm5iZiI6MTczNzQzOTEyOSwicGF0aCI6Ii8xMTM5NDYwLzQwNDA0MDQ5NC1jMzdmNmI0ZS1iNWQ5LTRhZTUtODlhMC01Mzg5MGIwOWMwODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjFUMDU1ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTY4ZWYwYTFlZjAwMGQ0N2FlY2QzMjZhNTRmMWFjZTZjYmM5NTI3NjI2NzgwOTE3NWUyNjg4Njk1OGQyOWQ5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OdIeuy7FK9lwuz5RNmT7SoFy6OLu9oEUb1wRIPo-p8c">

I am still troubleshooting Point 2. To see if the performance of loading the avatar

2025-01-21 07:02 UTC, alanpoon commented
> > The code structure looks all good to me. There are just a few UI issues:
> > 
> > 1. The RoomScreen is only filling half of the height of the window, similar to your other PR. Probably the same issue with the room screen tooltip?
> > 2. It takes a _really_ long time for the AvatarRow to actually show the profile pictures after the user profile request completes. I bet we're missing a UI Signal or something that would trigger a redraw of that AvatarRow, so please look into that.
> > 3. The tooltip shows the correct total count of people that have seen the message, but then incorrectly lists only the first 5 names. We should either display the entire list of all user names, or if you want to show only 5, then you should say "Seen by 8 people: A, B, C, D, E, and 3 more". Otherwise the user will think there's an odd math mistake.
> >    Also, the word "people" is missing, i.e., it should be "Seen by 8 people: ...".
> > 
> > <img alt="image" width="174" src="https://private-user-images.githubusercontent.com/1139460/404039305-2f76e908-5704-4ae6-a89e-716680ef0f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0Mzk0MjksIm5iZiI6MTczNzQzOTEyOSwicGF0aCI6Ii8xMTM5NDYwLzQwNDAzOTMwNS0yZjc2ZTkwOC01NzA0LTRhZTYtYTg5ZS03MTY2ODBlZjBmNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjFUMDU1ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTY0YzI4MWU3OThkMmRjNzQxZDU1ZjkxMjFiMjUxOGM3N2U3YjU2YTA1NTRlYWJhMjRmMDI1Yzg1YzA4MjY5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RmsixGq6U84gHq-6lADsg9ZBaMj1Q0cFePyrERZ5Fi4">
> > 4. The right-side margin used for the read receipt's Avatar Row is causing a lot of horizontal empty space on the right side of the RoomScreen. We're now wasting like 80 or so pixels of space there, so please fix that. Here's a screenshot of what I'm referring to:
> >    <img alt="image" width="814" src="https://private-user-images.githubusercontent.com/1139460/404040494-c37f6b4e-b5d9-4ae5-89a0-53890b09c084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0Mzk0MjksIm5iZiI6MTczNzQzOTEyOSwicGF0aCI6Ii8xMTM5NDYwLzQwNDA0MDQ5NC1jMzdmNmI0ZS1iNWQ5LTRhZTUtODlhMC01Mzg5MGIwOWMwODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjFUMDU1ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTY4ZWYwYTFlZjAwMGQ0N2FlY2QzMjZhNTRmMWFjZTZjYmM5NTI3NjI2NzgwOTE3NWUyNjg4Njk1OGQyOWQ5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OdIeuy7FK9lwuz5RNmT7SoFy6OLu9oEUb1wRIPo-p8c">
> 
> I am still troubleshooting Point 2. To see if the performance of loading the avatar

There is SignalToUi for enqueue_avatar_update already, so I don't think I can optimize it further.

2025-01-21 17:53 UTC, kevinaboos commented
> There is SignalToUi for enqueue_avatar_update already, so I don't think I can optimize it further.

Hmm, ok. Yeah, the only potential cause I could think of was a missing call to set the UI Signal, but if that's already there, then there might be a different cause for the delay. What I observed is a 10+ second delay between (1) a log statement that says the avatar/profile was fetched for a given user, and (2) the actual image being refreshed for the avatar.

Another cause of this _might_ be how we cache whether a given event was drawn in the timeline. We might need another variable that tracks the draw status of the read receipts _separately_ from that of the event's content and the event's user profile details.

In any case, we can make this improvement later and merge this in now, since the fundamental functionality appears to be working correctly.

2025-01-21 22:04 UTC, kevinaboos requested changes
Code looks good! I've tested everything locally and it works well.

However, the UI layout of the AvatarRow is a bit inconsistent for different message types. For example, the Avatars are not all vertically aligned, so it looks a bit weird.
There's also still a lot of wasted space on the right side of the RoomScreen.

I think you could fix both of these layout issues by setting the `x`-alignment of the AvatarRow to the far right side of its parent view in the room screen, and then using a right-margin of 10 or 20.

The final issue would be that the AvatarRow should be displayed towards the _bottom_ of each message, not towards the top of it. This is particularly noticeable on regular (non-Condensed) messages, like the ones from 8:59am, 10:02am, and 10:10am in this screenshot.

<img width="923" alt="image" src="https://github.com/user-attachments/assets/0ea85dc3-4e43-442f-8b05-eb4a4054a01f" />

2025-01-21 22:10 UTC, kevinaboos commented
Oh, and also feel free to ignore the positioning of the Message action bar (the small Reply button that pops up when you hover over a message). I am in the process of removing that, so you don't need to reserve any space for it on the right side of the room screen.

2025-01-22 06:12 UTC, alanpoon commented
> Code looks good! I've tested everything locally and it works well.
> 
> However, the UI layout of the AvatarRow is a bit inconsistent for different message types. For example, the Avatars are not all vertically aligned, so it looks a bit weird. There's also still a lot of wasted space on the right side of the RoomScreen.
> 
> I think you could fix both of these layout issues by setting the `x`-alignment of the AvatarRow to the far right side of its parent view in the room screen, and then using a right-margin of 10 or 20.
> 
> The final issue would be that the AvatarRow should be displayed towards the _bottom_ of each message, not towards the top of it. This is particularly noticeable on regular (non-Condensed) messages, like the ones from 8:59am, 10:02am, and 10:10am in this screenshot.
> 
> <img alt="image" width="923" src="https://private-user-images.githubusercontent.com/1139460/405399189-0ea85dc3-4e43-442f-8b05-eb4a4054a01f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1MTAzNzUsIm5iZiI6MTczNzUxMDA3NSwicGF0aCI6Ii8xMTM5NDYwLzQwNTM5OTE4OS0wZWE4NWRjMy00ZTQzLTQ0MmYtOGIwNS1lYjRhNDA1NGEwMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjJUMDE0MTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWRhMjNiMDRiZjFhNjA2ZDg3YmQzNzNjZGU4NDkxMWExNzQ0ZWM4NjY0ZTg0ODYzZWEyMzA4N2IyNTE2ZjNiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4AcJaS_iX-PNSeOlZrvLPum-tIB6N83gB18S12DmF0I">

Sped up the avatar loading, and right align the read receipt
![Screenshot 2025-01-22 at 2 12 03 PM](https://github.com/user-attachments/assets/8c53befe-2577-44d9-8ede-321a64b6e146)

2025-01-23 05:24 UTC, kevinaboos requested changes
Looking good, it's almost there!

It seems like there is a slight issue with the way you defined the new Views that wrap around the ReactionList and AvatarRow. It's causing weird whitespace gaps like this:
<img width="416" alt="image" src="https://github.com/user-attachments/assets/e9801ca7-c8c4-426f-b255-1c634186d554" />

and this: 
<img width="427" alt="image" src="https://github.com/user-attachments/assets/0e212282-7933-4ab3-9ead-69ab23237a39" />

Seems like it's mostly a problem with CondensedMessage, CondensedImageMessage, and SmallStateEvent (more so than regular Message and ImageMessage views, but they might also need adjustment).

In general, the AvatarRow should go at the very bottom right of an event view, and the Reaction list should go directly beneath the content of the event (like it was previously, before this PR).

I made a small commit that adjusted some things.

2025-01-23 15:59 UTC, alanpoon commented on src/utils.rs
> +pub const MAX_VISIBLE_NUMBER_OF_ITEMS: usize = 3;
fixed

2025-01-23 18:48 UTC, kevinaboos approved these changes
Fanstastic work, thanks so much! Can confirm that everything is working well.

2025-01-23 18:51 UTC, merged