Add Interactive icon button #115 for reaction
project-robius/robrix pull request #168
Opened 2024-10-01 15:05 UTC by alanpoon

https://github.com/project-robius/robrix/issues/115

https://github.com/user-attachments/assets/f0591221-303d-4f3d-bd38-fff279b8e407

1. Clicking the button sends toggle_reaction
2. Display a row of buttons for interactions

2024-10-01 19:46 UTC, kevinaboos requested changes
thanks, much appreciated!

please follow whitespace conventions, as it makes the code more readable. I added comments to some of the places where you're not doing it, but there are many more in `room_reaction_list.rs`.

2024-10-01 19:46 UTC, kevinaboos commented on src/home/room_screen.rs
> +    // html_reaction_view.set_text(&label_text);
remove since it's no longer in use

2024-10-01 19:46 UTC, kevinaboos commented on src/home/room_screen.rs
>          label_text = format!("{label_text}<i>:{}:</i> <b>{}</b> ", text_to_display, count);
remove since it's no longer in use

2024-10-01 19:46 UTC, kevinaboos commented on src/home/room_screen.rs
>      let mut label_text = String::new();
remove since it's no longer in use

2024-10-01 19:46 UTC, kevinaboos commented on src/home/room_reaction_list.rs
I'd recommend renaming this to something a bit more clear. The reaction list isn't per-room, it's per-event. So you could name it just "reaction_list" or "event_reaction" or something more accurate.

2024-10-01 19:46 UTC, kevinaboos commented on src/home/room_screen.rs
> +            .set_list(text_to_display_vec, room_id.to_owned(), event_id.to_owned());
I think it's a cleaner design if the `ReactionsList::set_list()` function accepts the `reactions: ReactionsByKeyBySender` object directly and then generates the list of reaction buttons within `set_list()`.

So, in other words, you should move the logic from `draw_reactions()` here into `set_list()` such that you don't have to generate the `text_to_display_vec` separately from the inner logic of `set_list()`.

2024-10-01 19:46 UTC, kevinaboos commented on src/home/room_screen.rs
> +    event_id: Option<&EventId>,
if you look at the [documentation of `Timeline::toggle_reaction()`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_ui/timeline/struct.Timeline.html#method.toggle_reaction), you're supposed to pass in the "unique_id" of the `TimelineItem`, not the event ID.

While they will generally be the same thing, let's make sure to follow the SDK docs precisely just to ensure we don't hit undefined behavior.

2024-10-30 06:27 UTC, kevinaboos requested changes
Thanks Alan, things are looking pretty good now!

There is still a key feature that we need, which seems to be missing (?):  two different colors for buttons.
* one color for emphasis, which will be used for the buttons that represent reactions the current user has sent themselves.
* a different color for non-emphasis, which will be used for buttons that represent reactions the user has not sent, i.e., reactions from others.

Also, can you provide a demo video / test case of this PR properly supporting wrapping the list of reaction buttons to a new line? I see that implemented in the `ReactionList::draw_walk()` fn but it has historically been difficult to implement properly. 

Another thought I had was:  can we reuse an existing Makepad widget instead of trying to roll our own list of buttons for the `ReactionList`?  Seems like this should be a fundamental widget type, since it's just a set of buttons that wrap.
If not, we should discuss this with Rik/Julian to see if your work here could be contributed to the upstream Makepad repo, since i'm sure others would want to use your code here for a wrappable list of buttons.

2024-10-30 06:27 UTC, kevinaboos commented on src/home/event_reaction.rs
> +    pub list: Vec<(String, usize)>,
the term `list` here is vague.

2024-10-30 06:27 UTC, kevinaboos commented on src/home/event_reaction.rs
nit: i'd vote naming this something like "event_reaction_list" to make it a bit clearer.

2024-10-30 06:36 UTC, alanpoon commented
> Thanks Alan, things are looking pretty good now!
> 
> There is still a key feature that we need, which seems to be missing (?): two different colors for buttons.
> 
> * one color for emphasis, which will be used for the buttons that represent reactions the current user has sent themselves.
> * a different color for non-emphasis, which will be used for buttons that represent reactions the user has not sent, i.e., reactions from others.
> 
> Also, can you provide a demo video / test case of this PR properly supporting wrapping the list of reaction buttons to a new line? I see that implemented in the `ReactionList::draw_walk()` fn but it has historically been difficult to implement properly.
> 
> Another thought I had was: can we reuse an existing Makepad widget instead of trying to roll our own list of buttons for the `ReactionList`? Seems like this should be a fundamental widget type, since it's just a set of buttons that wrap. If not, we should discuss this with Rik/Julian to see if your work here could be contributed to the upstream Makepad repo, since i'm sure others would want to use your code here for a wrappable list of buttons.

Here is the clip that features the wrap 
https://github.com/user-attachments/assets/e55f576b-7fe7-43e8-b02a-457e8768b12e

2024-10-30 08:14 UTC, kevinaboos commented
> Here is the clip that features the wrap
> https://github.com/user-attachments/assets/e55f576b-7fe7-43e8-b02a-457e8768b12e

awesome, very nice work! 

can you add some more left & right padding to each button? maybe `5` instead of `3`? Up to you, but it feels a bit tight to me.

2024-10-30 08:29 UTC, alanpoon commented
> > Here is the clip that features the wrap
> > https://github.com/user-attachments/assets/e55f576b-7fe7-43e8-b02a-457e8768b12e
> 
> awesome, very nice work!
> 
> can you add some more left & right padding to each button? maybe `5` instead of `3`? Up to you, but it feels a bit tight to me.

ok, thanks for the feedback. I might be making a generic wrap list button widget that is more composable.

2024-10-31 18:04 UTC, kevinaboos commented
> ok, thanks for the feedback. I might be making a generic wrap list button widget that is more composable.

Sounds good. but kindly save that for later. For now, all you need to do is address the above comments and then we can merge this in as-is. Thanks!

2024-10-31 23:12 UTC, alanpoon commented on src/home/event_reaction.rs
> +                target.redraw(cx);
@kevinaboos There's a bug in this line. Redrawing the child widget, redraws the entire ReactionList, causing un-terminating redrawing.

2024-11-01 01:06 UTC, kevinaboos commented on src/home/event_reaction.rs
> +                target.redraw(cx);
I'd reach out to @joulei or Rik for things like this.

2024-11-01 04:18 UTC, joulei commented on src/home/event_reaction.rs
> +                target.redraw(cx);
Yup we've been debugging this offline. I'll give it a proper review today.

2024-11-01 06:20 UTC, joulei commented on src/home/event_reaction.rs
> +                target.redraw(cx);
Alright so as a quick update, there's 2 issues:
1. There's already a constant redraw loop happening in Robrix around the `RoomScreen` regardless of this PR
2. This widget goes into a constant redraw loop when it has to draw multiple lines of reactions.

We'll keep investigating

2024-11-04 04:48 UTC, kevinaboos commented on src/home/event_reaction.rs
> +                target.redraw(cx);
Thanks for the update! Will hold off on merging until I hear back.

2024-11-07 03:31 UTC, kevinaboos commented
Blocked on Makepad problem: https://github.com/project-robius/robrix/pull/168#discussion_r1825467121

2024-11-13 06:34 UTC, joulei commented on src/home/event_reaction.rs
> +                target.redraw(cx);
Hey @alanpoon I'm coming back to this issue.

I think the easiest path forward is to simply remove the `target.redraw()` line here. Basically currently this is _attempting_ to redraw the latest item if it exceeded the width, however since you have a hardcoded offset here: `let width: f64 = rect.size.x - 50.0;`, I think you can safely skip redrawing the latest item, it will never truly exceed the available width.
I say _attempting_ because this code does not really re-draw the latest item in a new position, for that you'd have to draw the items absolutely positioned (using `draw_abs` method) and keep track of each item position. Therefore I think you can keep the current approach where you let the turtle handle positioning, and you simply insert a new turtle line when necessary.
Is that clear enough?

Also could you update this branch to the latest `main` and double-check? After doing that and removing the `target.redraw()` you can add a log to the `draw_walk` of `ReactionList` to double-check that no unnecessary redrawing is happening.
I mention updating the branch because at this point in time Robrix was doing a lot of constant redrawing that seems to have improved in current `main`.

2024-11-25 06:53 UTC, alanpoon commented on src/home/event_reaction.rs
> +                target.redraw(cx);
I've checked, I don't need the target.redraw() with newer branch and it works.

2024-11-27 08:20 UTC, alanpoon commented on src/home/event_reaction.rs
> +        looper: &ReactionsByKeyBySender,
fixed

2024-11-27 08:22 UTC, alanpoon commented on src/sliding_sync.rs
> +    ToggleReaction {
Added doc

2024-11-27 08:23 UTC, alanpoon commented on src/sliding_sync.rs
> +        unique_id: String,
Changed to TimelineEventItemId

2024-11-27 08:24 UTC, alanpoon commented on src/sliding_sync.rs
> +            receipt::ReceiptThread, relation::Annotation, room::{
Removed

2024-11-27 08:25 UTC, alanpoon commented on src/home/room_screen.rs
> +    unique_id: &str,
Fixed

2024-11-27 08:59 UTC, alanpoon commented on src/home/event_reaction.rs
changed to reaction_sender_count_list

2024-11-27 10:41 UTC, alanpoon commented on src/home/event_reaction.rs
> +                target.redraw(cx);
Still cannot, without target.redraw(), the last item will get cut off to the right. 
<img width="379" alt="Screenshot 2024-11-27 183809" src="https://github.com/user-attachments/assets/d7e775bb-721d-4bf9-9dc8-c77da936e7a3">

I think i might go for preserving where the new line needs to be drawn.

2024-11-28 07:04 UTC, alanpoon commented on src/home/event_reaction.rs
> +    pub list: Vec<(String, usize)>,
changed to event_reaction_list

2024-11-28 07:05 UTC, alanpoon commented on src/home/room_screen.rs
> +                    margin: {top: (5.0)}
fixed

2024-12-06 10:19 UTC, alanpoon commented
https://github.com/user-attachments/assets/d41fde3c-034b-41a3-b9b5-b0a28d921f6c

Added color emphasis and tooltip.

2024-12-09 04:13 UTC, aaravlu submitted a review, later dismissed

2024-12-09 04:13 UTC, aaravlu commented on src/home/room_screen.rs
> +        tooltip = <Tooltip> {
Maybe We can find a better naming than `tooltip`

2024-12-09 04:13 UTC, aaravlu commented on src/home/room_screen.rs
> +            let mut tooltip = self.tooltip(id!(tooltip));
Then here should be changed.

2024-12-09 04:13 UTC, aaravlu commented on src/home/room_screen.rs
> +                let seq = wr.reaction_list(id!(reaction_list));
Maybe I have not understood the meaning of creating a widget ref for each time the loop.

2024-12-09 05:41 UTC, alanpoon commented on src/home/room_screen.rs
> +                let seq = wr.reaction_list(id!(reaction_list));
it is iteration over the rows in the portal list. So wr is the widget ref for a row

2024-12-10 00:05 UTC, ZhangHanDong commented on src/home/event_reaction.rs
> +    event_reaction_list: Vec<(String, usize, String, bool, f64)>,
For a tuple with so many elements, it’s better to consider using a struct, although there is documentation, the readability is too poor. 

Also, can String be replaced with &str here?

2024-12-10 03:15 UTC, alanpoon commented on src/home/event_reaction.rs
> +    event_reaction_list: Vec<(String, usize, String, bool, f64)>,
Fixed the many elements in tuple issue with a struct. The makepad macro does not support lifetime parameter type. So it is difficult to replace String with &str.
<img width="161" alt="Screenshot 2024-12-10 111126" src="https://github.com/user-attachments/assets/87b8b502-f37d-4e5a-a4a1-459cfda1cad5">

2024-12-16 19:55 UTC, kevinaboos requested changes
Visually things look good. Code-wise, I have some questions.

Can you explain why we need the strange approach of drawing things twice -- once to determine width, and then again to un-hide the buttons? That seems like it wouldn't be necessary.

Kindly don't use `something.iter().for_each()`, that pattern is harder to read and causes more indentation than the regular for loop.

Also, please use triple slash `///` doc comments when you're writing comments above an item (field, function, struct, etc) instead of the regular `//` double slash plain code comments.

Since we need access to the currently-logged-in user, go ahead and add a dedicated function for that beneath `get_client()` in `sliding_sync.rs` that returns an `Option<OwnedUserId>`. We'll use that in other code contexts too.

2024-12-16 19:55 UTC, kevinaboos commented on src/home/event_reaction.rs
> +    // After the first draw, the buttons' will be stored in this vector
also there is a typo, a `'` after "buttons"

2024-12-16 19:55 UTC, kevinaboos commented on src/sliding_sync.rs
> +        reaction_key: String,
```suggestion
        reaction: String,
```

2024-12-23 02:59 UTC, alanpoon commented on src/home/event_reaction.rs
> +    width: f64
fixed

2024-12-23 03:30 UTC, alanpoon commented on src/home/room_screen.rs
> +    client_user_id: OwnedUserId
removed

2024-12-25 07:26 UTC, alanpoon commented on src/home/event_reaction.rs
> +                .for_each(|(id, widget_ref)| {
fixed

2024-12-25 07:31 UTC, alanpoon commented on src/home/event_reaction.rs
> +                            let rect = if e.abs.x > cx.default_window_size().x - 80.0{
https://github.com/user-attachments/assets/5788ae6e-0da0-45d2-8863-7463fd10076b

2024-12-25 07:36 UTC, alanpoon commented on src/home/event_reaction.rs
> +                            let rect = if e.abs.x > cx.default_window_size().x - 80.0{
https://github.com/user-attachments/assets/593a3dc0-c727-4160-936d-9d46a565e5fe

2024-12-26 05:47 UTC, ZhangHanDong commented on src/home/event_reaction_list.rs
> +                        submit_async_request(MatrixRequest::GetUserProfile {
There is an issue with the implementation here. Inside the component, the focus should only be on retrieving user information without concerning about the details of caching and requesting. However, this code currently undertakes two responsibilities: displaying the reaction list and managing user information. The reusability of the code is also poor.

You should handle submit_async_request inside get_user_profile, for example:

```rust

let user_profile = USER_PROFILE_CACHE.with_borrow(|cache| {
        cache.get(user_id).map(|entry| entry.user_profile.clone())
 });
match user_profile {
        Some(profile) => Some(profile),
        None => {
            // 当缓存未命中时,在这里触发异步请求
            submit_async_request(MatrixRequest::GetUserProfile { 
                user_id: user_id.to_owned(),
                room_id: None,  // 这里可以考虑是否需要传入 room_id
                local_only: false 
            });
            None  // 返回 None,等待异步更新
        }
    }
```

2024-12-26 06:05 UTC, ZhangHanDong commented on src/home/event_reaction_list.rs
> +                        draw_bg: { hide: 0.0 , color: (vec4(0.0, 0.6, 0.47, 1.0)) }
Color values (`vec4(0.0, 0.6, 0.47, 1.0)`) are scattered throughout the code, making it difficult to manage and reuse them uniformly. The best approach is to define them in the theme file (`shared/styles.rs`) and add comments to facilitate unified modification and maintenance.

2024-12-26 06:05 UTC, ZhangHanDong commented on src/home/event_reaction_list.rs
> +                        draw_bg: { hide: 0.0, color: (vec4(0.714, 0.73, 0.75, 1.0)) }
Same as above.

2024-12-26 21:04 UTC, kevinaboos requested changes
Can you answer my [previous question from Dec 16th here](https://github.com/project-robius/robrix/pull/168#pullrequestreview-2507066718) about why we need two draw passes to handle the width calcs for the individual reaction buttons in the reaction list? that seems quite inefficient. If that's the only way we can come up with to handle this, then you should reach out to either Julian or Rik to get more ideas on how we can avoid that.

Also, in that linked comment I mentioned using the new [`current_user_id()`](https://github.com/project-robius/robrix/blob/6cf61104952a30c756d66244ab78225e292b0222/src/sliding_sync.rs#L953), which is more efficient. Kindly use that where appropriate.

2024-12-27 05:19 UTC, alanpoon commented
> Can you answer my [previous question from Dec 16th here](https://github.com/project-robius/robrix/pull/168#pullrequestreview-2507066718) about why we need two draw passes to handle the width calcs for the individual reaction buttons in the reaction list? that seems quite inefficient. If that's the only way we can come up with to handle this, then you should reach out to either Julian or Rik to get more ideas on how we can avoid that.
> 
> Also, in that linked comment I mentioned using the new [`current_user_id()`](https://github.com/project-robius/robrix/blob/6cf61104952a30c756d66244ab78225e292b0222/src/sliding_sync.rs#L953), which is more efficient. Kindly use that where appropriate.

I've reached out to @joulei, initially I thought his advice of using the updated version of makepad works. But the last element's right edge in the row often exceeds the bounded area when resizing the window. In the end I wrote the solution to force fix it once and forever. 

I will change to use current_user_id.

2024-12-27 08:57 UTC, kevinaboos commented on src/sliding_sync.rs
> +                }
I have implemented the proper way to avoid redundant requests in the user profile cache as of PR #303, which was just merged in. You should now be able to use either of the two `user_profile_cache` functions: `with_user_profile()` and `get_user_profile_and_room_member()` for all of your user profile needs.

2024-12-27 09:00 UTC, kevinaboos commented
i have added new user cache behavior as you suggested, please pull down the latest changes from the `main` branch and merge them in here.

2024-12-27 11:39 UTC, joulei commented
I'm not seeing a straight forward way to distribute the buttons across different lines without having to redraw them.
In Makepad we don't have a way to know something's size until we draw it, in this case we have dynamically-sized labels which makes it even more difficult. 
I'm trying to find a way to can clean it up by only redrawing the last button (in a new line) if it exceeds the available width (we can check this at the beginning of draw_walk with `cx.peek_walk_turtle(walk).size`, and keep track of the acc drawn width). In theory that should work but I'm being unable to draw in two different positions within the same `draw_walk` call, investigating the cleanest workaround..

---
Notes:

- Once we have emoji support we could play around fixed sizes, you could say "ok a button takes at max 100 width: the emoji takes 80 and the number of reactions takes 20 (you can limit the number by writing +999 if needed or something like that).

- If performance is a concern we could implement things like a "show more" button that hides reactions after the first full width is taken, example from Element:
![Screenshot 2024-12-27 at 11 34 31 AM](https://github.com/user-attachments/assets/df81e9ee-6aa0-453d-bd26-454a3e9724c0)

I don't know if Matrix itself has any restrictions around reactions but Discord and Slack limit reactions to ~ 20. Example from Discord:
![image](https://github.com/user-attachments/assets/2e167ca3-9327-4075-9056-d3985a421a74)

For the most performant solution you could implement something like `PortalList` where you first "draw" the items, keep a draw state, and the shift their position before closing the turtle, but I wouldn't invest in that level of complexity for this.

2024-12-27 20:19 UTC, kevinaboos commented
> investigating the cleanest workaround, perhaps there's something to be done with draw steps..

ok thanks for looking into this. Do you have time to work on this now (shall I wait for your improvements before merging), or should i just go ahead and merge now?

> * Once we have emoji support we could play around fixed sizes, you could say "ok a button takes at max 100 width: the emoji takes 80 and the number of reactions takes 20 (you can limit the number by writing +999 if needed or something like that).

We can't do that because arbitrary strings are allowed as valid reactions; it doesn't just have to be a single emoji char. You can react with something like "hey there it's me, Kevin", haha.

> * If performance is a concern we could implement things like a "show all" button that hides reactions after the first full width is taken, example from Element:
>   ![Screenshot 2024-12-27 at 11 34 31 AM](https://private-user-images.githubusercontent.com/22042418/398927427-df81e9ee-6aa0-453d-bd26-454a3e9724c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMzA2MDEsIm5iZiI6MTczNTMzMDMwMSwicGF0aCI6Ii8yMjA0MjQxOC8zOTg5Mjc0MjctZGY4MWU5ZWUtNmFhMC00NTNkLWJkMjYtNDU0YTNlOTcyNGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIwMTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MWM4ZTZmODYyNjBmNTdkOTgyMGY2M2ZjZWEwYmVjMWE1YTExYzE2NTRkNjI1MjBhNTJkNTFmOTg3Mjc2YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gMi1Y0b4XHtrv0HlxavQWDOMYe8Ok4jONSYev1vFL1I)

I actually like that idea, but i think it's too much complexity for the very rare case of lots of reactions. Plus, if we have to handle the case of a single line width being exceeded in order to display a button, we might as well just handle that case properly and wrap onto the next line anyway; the current way of doing things also makes it easier on the user to view large sets of reactions. So yea, i'd vote to not do that.

2024-12-30 12:39 UTC, joulei commented
> ok thanks for looking into this. Do you have time to work on this now (shall I wait for your improvements before merging), or should i just go ahead and merge now?

So I've tried a couple of different approaches in the last few days to remove the extra redrawing but I haven't managed. I'll show Rik on Thursday to see if there are alternatives I'm missing.

**To illustrate:**
I've tried to optimize this by using draw steps, and only redrawing the last item (the one that exceeds the available width).
However we can't really "remove" the drawn item from the previous line without redrawing the line, or drawing invisible first just in case and then switching visibility (which requires redraw, and brings us back to the original implementation).

I've tried this:
- Use a DrawState wrap like we do for `FlatList`, `PortalList`, `FileTree`, etc.
- Being that DrawState on the first `draw_walk` call, drawing the items up until we reach end of available width
- ^ upon reaching this, return a `DrawState::make_step()` and updating the DrawState with the item that should be redrawn, what `y_line`, etc.
- On the next `draw_walk` call continue drawing from the last DrawState. Repeat above steps until we've drawn all items.

Add a draw state:
```rs
struct ReactionDrawState {
    current_index: usize,
    acc_width: f64,
    line_y: f64,
    start_new_line: bool,
}

pub struct ReactionList {
    // ...
    #[rust]
    draw_state: DrawStateWrap<ReactionDrawState>, // add this
}
```

Update `draw_walk`
```rs
fn draw_walk(&mut self, cx: &mut Cx2d, scope: &mut Scope, walk: Walk) -> DrawStep {
        if self.event_reaction_list.is_empty() {
            return DrawStep::done();
        }
        if self.draw_state.begin(cx, ReactionDrawState {
            current_index: 0,
            acc_width: 0.0,
            line_y: 0.0,
            start_new_line: false,
        }) {
            cx.begin_turtle(walk, self.layout);
            return DrawStep::make_step();
        }

        if let Some(state) = self.draw_state.get() {
            // let rect = cx.peek_walk_turtle(walk).size;
            let rect = cx.turtle().rect().size;
            let available_width = rect.x;

            // If we're starting a new line, reset the turtle position
            if state.start_new_line {
                cx.turtle_new_line();
                cx.turtle_mut().set_used(0.0, state.line_y);
                self.draw_state.set(ReactionDrawState {
                    current_index: state.current_index,
                    acc_width: 0.0,
                    line_y: state.line_y,
                    start_new_line: false,
                });
                return DrawStep::make_step();
            }

            let reaction_data = &self.event_reaction_list[state.current_index];
            
            // Create and configure the button
            let target = self.children.get_or_insert(cx, LiveId(state.current_index as u64), |cx| {
                WidgetRef::new_from_ptr(cx, self.item).as_button()
            });
            
            target.set_text(&format!("{} {}", reaction_data.emoji, reaction_data.total_num_react));
            
            // Apply styling
            let node_to_apply = if reaction_data.includes_user {
                live! {
                    draw_bg: { hide: 0.0, color: (vec4(0.0, 0.6, 0.47, 1.0)) }
                }
            } else {
                live! {
                    draw_bg: { hide: 0.0, color: (vec4(0.714, 0.73, 0.75, 1.0)) }
                }
            };
            target.apply_over(cx, node_to_apply);

            // Draw the button
            let _ = target.draw(cx, scope);
            // Get the actual width used after drawing
            let used = cx.turtle().used();
            
            // Check if this item exceeded available width
            if used.x > available_width && state.acc_width > 0.0 {
                // Save state to start a new line on next draw_walk
                self.draw_state.set(ReactionDrawState {
                    current_index: state.current_index,
                    acc_width: 0.0,
                    line_y: used.y,
                    start_new_line: true,
                });
                return DrawStep::make_step();
            }

            // Move to next item
            if state.current_index + 1 < self.event_reaction_list.len() {
                self.draw_state.set(ReactionDrawState {
                    current_index: state.current_index + 1,
                    acc_width: used.x,
                    line_y: state.line_y,
                    start_new_line: false,
                });
                return DrawStep::make_step();
            }
        }

        // Cleanup and finish
        cx.end_turtle();
        self.children.retain_visible();
        self.draw_state.end();
        DrawStep::done()
    }
```
This results on the exceeding item being drawn twice:
![image](https://github.com/user-attachments/assets/26f715ab-46ed-4688-8989-014365006dde)

**TL;DR** I haven't found a feasible alternative, I'll ask Rik for ideas but the current implementation might be the simplest working implementation for now. The closest problem I solved was in `StaggeredGrid` for Wonderous, however in that case having the items exceed the viewport first is acceptable because it's a scrollable view, in this we want to shift the item without ever drawing it exceeding the width.

2024-12-31 09:09 UTC, alanpoon commented on src/sliding_sync.rs
> +                }
fixed

2024-12-31 09:15 UTC, alanpoon commented
https://github.com/project-robius/robrix/pull/168#discussion_r1898106238
This requires a dynamic tooltip width and a callout arrow pointing downwards or upwards.

2024-12-31 20:09 UTC, kevinaboos commented
@alanpoon i see you marked this as blocked on makepad, but I think we should move forward without waiting on those fixes. Then, whenever the Makepad issues are improved, we can come back and improve the tooltip wrapping and multi-pass draw approach here.

@alanpoon are there any other pending changes you want to make to this PR before I do a final review pass and merge it in?

2025-01-01 00:55 UTC, alanpoon commented on src/home/room_screen.rs
> +            let room_id = &tl_state.room_id;
fixed

2025-01-01 01:27 UTC, alanpoon commented on src/home/event_reaction_list.rs
> +                        draw_bg: { hide: 0.0, color: (vec4(0.714, 0.73, 0.75, 1.0)) }
I don't think Live apply can apply definition from the theme file (shared/styles.rs)

2025-01-01 01:27 UTC, alanpoon commented on src/home/event_reaction_list.rs
> +    /// Handles hover out action
There is a separate function for hover_out

2025-01-01 01:53 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +    /// Handles hover out action
yea, sorry i was referring to your doc comment being inaccurate. The `hover_out()` function doesn't handle a hover-out action (like your comment says it does). It simply returns whether a hover-out action occurred in the given set of actions.

2025-01-01 01:54 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +                        submit_async_request(MatrixRequest::GetUserProfile {
this was completed 5 days ago, marking as resolved.

2025-01-02 07:56 UTC, alanpoon commented on src/home/event_reaction_list.rs
> +                        draw_bg: { hide: 0.0 , color: (vec4(0.0, 0.6, 0.47, 1.0)) }
Currently I am not seeing example of using live! macro with constant defined in shared/styles.rs. But I declared constant values in Vec4 for color.

2025-01-02 08:00 UTC, alanpoon commented on src/home/event_reaction_list.rs
> +    /// Handles hover out action
fix doc

2025-01-02 12:24 UTC, alanpoon commented on src/home/event_reaction.rs
> +                            let rect = if e.abs.x > cx.default_window_size().x - 80.0{
See https://github.com/project-robius/robrix/pull/168#issuecomment-2566271125

2025-01-02 12:25 UTC, alanpoon commented
> @alanpoon i see you marked this as blocked on makepad, but I think we should move forward without waiting on those fixes. Then, whenever the Makepad issues are improved, we can come back and improve the tooltip wrapping and multi-pass draw approach here.
> 
> @alanpoon are there any other pending changes you want to make to this PR before I do a final review pass and merge it in?

No more pending changes

2025-01-02 19:53 UTC, joulei commented
Sorry to interrupt after we said we'll fix it later, but I just learned (from Rik) that we can leverage Layout's `flow: RightWrap` for this, which will internally handle the new turtle lines.
We can simplify this implementation a lot by simply using a layout with `flow: RightWrap` when we begin the turtle:
```rs
    fn draw_walk(&mut self, cx: &mut Cx2d, scope: &mut Scope, walk: Walk) -> DrawStep {
        self.layout.flow = Flow::RightWrap; // these two are the important lines
        cx.begin_turtle(walk, self.layout);
        
        // Records the button widths after the first draw
        let mut prev_width: f64 = 0.0;
        for (index, reaction_data) in
            self.event_reaction_list.iter_mut().enumerate()
        {
            let target = self.children.get_or_insert(cx, LiveId(index as u64), |cx| {
                WidgetRef::new_from_ptr(cx, self.item).as_button()
            });
            target.set_text(&format!("{} {}", reaction_data.emoji, reaction_data.total_num_react));

            let _ = target.draw(cx, scope);
            let used = cx.turtle().used();
            reaction_data.width = used.x - prev_width;
            prev_width = used.x;
        }

        cx.end_turtle();
        self.children.retain_visible();
        DrawStep::done()
    }
```
This seems to work well in my tests.

2025-01-02 21:07 UTC, kevinaboos commented
Oh ok, great. I assumed we had already tried that (since I used `RightWrap` in other DSL elements) so I didn't suggest it. But thanks for bringing it up.

@alanpoon go ahead and give that a try. (or @joulei, feel free to commit your changes directly here, too)

2025-01-03 07:38 UTC, alanpoon commented
> Oh ok, great. I assumed we had already tried that (since I used `RightWrap` in other DSL elements) so I didn't suggest it; that's my bad. But thanks for bringing it up.
> 
> @alanpoon go ahead and give that a try. (or @joulei, feel free to commit your changes directly here, too)

Thanks Joulei, RightWrap works fine. I have implemented RightWrap.

2025-01-03 19:16 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +                    .for_each(|(id, widget_ref)| {
use a regular `for` loop, it will fix indentation and improve readability.

2025-01-03 19:21 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +            .for_each(|(_id, widget_ref)| {
same here,  use a regular `for` loop.

2025-01-03 19:29 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +        // Currently handling mouse-in effect using "event.hits(cx, widget_ref.area())" does not work.
i think the reason this doesn't work is because `ReactionList` doesn't actually own any drawable child views with actual area. I think that if you adopt the design change in my top-level comment, you can just use the existing Button infrastructure to _vastly_ simplify all of this code here: hovering in/out, clicking, etc.

Right now, the design is just _way_ too complex such that it'll be unmaintainable for future developers.

It's also quite expensive in terms of cyclomatic complexity (many nested loops) and due to how it runs a very expensive set of operations upon _every_ mouse movement event. We should avoid that as much as possible, and leveraging the existing button widget features should help us do so.

2025-01-03 19:36 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +                            reaction: key.as_str().to_string(),
this is incorrect. We need to keep the _original, unmodified_ reaction key content (because it can be any arbitrary string, not just a single emoji), and then use that exactly reaction key when sending the `ToggleReaction` request.
 
The conversion of an emoji character to an actual emoji shortcode is just a temporary hack to get around Makepad's lack of emoji support. That should only be done when we need to display the emoji.

2025-01-03 19:38 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +        let Some(client_user_id) = get_client().and_then(|c| c.user_id().map(|user_id| user_id.to_owned()) ) else { return };
we have the new `current_user_id()` function now

2025-01-03 19:40 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +        if let Some(mut instance) = self.borrow_mut() {
nit: use an early-return flow to reduce indentation of the rest of the function block and improve readability:
```suggestion
        let Some(mut instance) = self.borrow_mut() else { return };
```

2025-01-03 19:43 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +                            reaction: key.as_str().to_string(),
memory is "cheap", so we can store both the unmodified reaction key and the converted one (with shortcodes) in the `ReactionData` struct.

2025-01-03 19:48 UTC, kevinaboos commented on src/home/room_screen.rs
> +            portal_list.items_with_actions(actions).iter().for_each(| (_, wr) | {
use a regular `for` loop

2025-01-03 19:53 UTC, kevinaboos commented on src/utils.rs
> +        },
formatting nits:
```suggestion
pub fn human_readable_list<S>(names: &[S]) -> String
where
    S: AsRef<str>
{
    const MAX_NAMES: usize = 5;
    let mut result = String::new();
    match names.len() {
        0 => { }
```

2025-01-07 10:57 UTC, alanpoon commented on src/home/event_reaction_list.rs
> +            spacing: 20,
fixed

2025-01-07 10:57 UTC, alanpoon commented on src/home/event_reaction_list.rs
> +        self.layout.flow = Flow::RightWrap;
fix

2025-01-07 11:01 UTC, alanpoon commented on src/home/event_reaction_list.rs
> +        let Some(client_user_id) = get_client().and_then(|c| c.user_id().map(|user_id| user_id.to_owned()) ) else { return };
fixed

2025-01-07 11:11 UTC, alanpoon commented on src/home/room_screen.rs
> +            portal_list.items_with_actions(actions).iter().for_each(| (_, wr) | {
fixed

2025-01-07 19:48 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +                instance color_hover: (#fef65b)
yea sorry, i meant for `color_hover` which is a literal value. No parens needed there.

2025-01-07 20:55 UTC, kevinaboos requested changes
wow, major improvements! Code looks very nice now, and is a lot easier to follow and maintain.

I left some comments, but nothing too major.

2025-01-07 20:55 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +            tooltip_text.push_str(&format!("\nreacted with: {}", emoji_text));
do we actually _want_ to eagerly pre-generate all of the tooltip text here? I think this will result in a lot of wasted CPU cycles, since it's a relatively rare action for a user to hover over every reaction to every message.

Instead, we should just generate it on demand, i.e., when the user actually hovers over a reaction button.

2025-01-07 20:55 UTC, kevinaboos commented on src/home/room_screen.rs
> +        /// Calculated Y offset required such that the pointed arrow is pointed towards the center of the hovered widget.
```suggestion
        /// Calculated Y offset required such that the pointed arrow
        /// is pointed towards the center of the hovered widget.
```

2025-01-07 20:55 UTC, kevinaboos commented on src/home/room_screen.rs
> +    HoverOut,
add docs

2025-01-07 20:55 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +            tooltip_text.push_str(&format!("\nreacted with: {}", emoji_text));
however, what you _could_ do here is keep the call to `get_user_profile_and_room_member()` in order to request/fetch all of the user profiles for every reaction sender, which would ensure that they're available when the user actually does hover over the reaction button. That way, it's much more likely that we'll see full displayable usernames in the tooltip text rather than just the senders' user IDs.

Then, in the code that generates the tooltip text on demand (upon a HoverIn action), you can call `get_user_profile_and_room_member()` again, and it should properly return the full user profile.

2025-01-13 12:20 UTC, alanpoon commented on src/home/event_reaction_list.rs
> +            tooltip_text.push_str(&format!("\nreacted with: {}", emoji_text));
fixed

2025-01-13 16:59 UTC, joulei commented
@alanpoon could you help me understand the issue further? I think I'm not following 100%
I understand the issue with overlapping areas and I get what you're describing event propagation between the message and the tooltips. However, what's exactly the current issue?
You mentioned:

> Causing the message not highlighted when mouse over.

But I just tested this branch and both message hovers and tooltips seem to work fine to me. I'm sure I'm missing something though.

https://github.com/user-attachments/assets/54d476f7-f377-4f5a-b2e9-97a303843e2d

2025-01-14 03:09 UTC, alanpoon commented
> @alanpoon could you help me understand the issue further? I think I'm not following 100% I understand the issue with overlapping areas and I get what you're describing event propagation between the message and the tooltips. However, what's exactly the current issue? You mentioned:
> 
> > Causing the message not highlighted when mouse over.
> 
> But I just tested this branch and both message hovers and tooltips seem to work fine to me. I'm sure I'm missing something though.
> 
>  Screen.Recording.2025-01-13.at.1.58.52.PM.mov

Maybe you use the branch which implemented sweep lock. The expected behavior is to support both mouse over tooltip and also finger up event on the message. You are missing FingerUp event.hit on the message. https://github.com/alanpoon/robrix/blob/344c561475f92bcd5bdfee08ad696f4d9809d839/src/home/room_screen.rs#L4078
https://github.com/alanpoon/robrix/tree/interactive_icon_button4

Here is sweep lock behavior. 
https://github.com/user-attachments/assets/815bada2-01d9-46cf-8a06-773ae81a7324
It is complaining no matching field Hover and highlight.

2025-01-14 06:42 UTC, kevinaboos commented on src/home/event_reaction_list.rs
> +            tooltip_text.push_str(&format!("\nreacted with: {}", emoji_text));
looks great, thanks!

2025-01-14 06:44 UTC, kevinaboos reviewed
The code changes look great, thanks! I think you've satisfactorily addressed all of my comments.

Sorry for the issues regarding `hits()`, hopefully we can resolve that soon.

In any case, once we solve that issue, I will approve this PR and merge it in!

2025-01-14 06:47 UTC, kevinaboos commented
@alanpoon @joulei in case it's relevant, I also experienced issues with Facunda's recent PR #288. Sometimes the hover/mouse events don't get delivered properly to the popped-up context menu.

I wrote this on discord but haven't received a reply from him yet:

> One problem I've found is that after the context menu pops up, I can't consistently hover over it or even click on the Reply button. Most of the time, I have to first move the mouse to a different part of the window, and then move the mouse back to the open context menu in order for it to "trigger" properly, and then the hover & click actions will start working. Whenever you have a moment, I'd appreciate it if you could look into that.

2025-01-14 13:32 UTC, joulei commented
Thanks for the info @alanpoon and @kevinaboos. We're debugging this with Facu but we're still struggling to replicate it. 
I don't see the error logs you're seeing @alanpoon (in this branch) and the hover seems to work correctly for reaction tooltip, message, and also context menu. 
@kevinaboos if you could drop a video of the behaviour you're seeing with unreliable hover or click on reply button that could be helpful. (I know this has been a problem in many makepad apps, and even other platforms have similar issues, just can't replicate it right now)

2025-01-14 15:35 UTC, alanpoon commented
> Thanks for the info @alanpoon and @kevinaboos. We're debugging this with Facu but we're still struggling to replicate it. I don't see the error logs you're seeing @alanpoon (in this branch) and the hover seems to work correctly for reaction tooltip, message, and also context menu.
> 
> Edit: managed to replicate the issue with the context popup (reply button) sometimes not triggering the hover animation.

I have reverted Facu's code, at this commit c0fddf53273698e30f3efd80fc9e8831e0839cec. Now the hover effect of the reaction button is not working.

2025-01-14 19:00 UTC, joulei commented
I'll continue to debug without that commit revert, since almost everything works for me, with the exception of the hover of the popup context menu sometimes not hovering. 

Also, in case this is related, am I the only one with empty space at the bottom of the room (on this branch)
![image](https://github.com/user-attachments/assets/31e5bc58-6f88-4e8d-b092-e01ea8d3747d)

2025-01-16 07:19 UTC, kevinaboos commented
PR #324 fixed the issue with hits not being forwarded properly. Hopefully you don't have any more issues. 

So, now you should be able to undo all the hit-related changes, and we can merge this in.

2025-01-16 08:14 UTC, alanpoon commented
> PR #324 fixed the issue with hits not being forwarded properly. Hopefully you don't have any more issues.
> 
> So, now you should be able to undo all the hit-related changes, and we can merge this in.

Merged in main.

2025-01-16 20:30 UTC, kevinaboos commented
There are quite a few UI & UX issues still remaining. Have you tested this thoroughly? If not, please do so, since there are likely even more issues lurking under the surface.

Screenshot showing some issues:
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/7af0b3de-07d6-4da1-a247-0c1bc46d12e3" />

Some of the problems are:
* I also observe the half-sized RoomScreen that Julian saw.
* The color contrast for the reaction button, both the green color and the gray color, is really low/bad. It's nearly impossible to read.
* I can't tell when a reaction has been sent by a user. Please follow the same color/shading styles used by Element or Discord, they make it quite clear whether or not you have sent a reaction.
* Each reaction button needs to set its cursor to `Hand` such that the user is aware they can click on it. Right now, there's no way for the user to know that each reaction button is a clickable element.
* Lots of emoji are failing to be parsed. I'm not sure what you changed about my routine that parses the raw emoji into a text shortcode, but mine previously worked 100%, so you may just want to revert back to what I was doing previously.
   * Examples:
   ```
   src/home/event_reaction_list.rs:186:21 - Failed to parse emoji: 👍️
   src/home/event_reaction_list.rs:186:21 - Failed to parse emoji: ➕️
   ```

The tooltip is nice, but is split across too many lines, making it hard to read. It should only be split into two lines by default (with the first line being "UserName reacted with:"), and should only spill over to more than 2 lines if the text is really really long.
<img width="421" alt="image" src="https://github.com/user-attachments/assets/1e076042-9855-43ba-9f63-25a1463b46c6" />

2025-01-19 16:34 UTC, alanpoon commented
> There are quite a few UI & UX issues still remaining. Have you tested this thoroughly? If not, please do so, since there are likely even more issues lurking under the surface.
> 
> Screenshot showing some issues: <img alt="image" width="1392" src="https://private-user-images.githubusercontent.com/1139460/404027959-7af0b3de-07d6-4da1-a247-0c1bc46d12e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczMDQ2OTYsIm5iZiI6MTczNzMwNDM5NiwicGF0aCI6Ii8xMTM5NDYwLzQwNDAyNzk1OS03YWYwYjNkZS0wN2Q2LTRkYTEtYTI0Ny0wYzFiYzQ2ZDEyZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTlUMTYzMzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTA4MDZjYjY2MzNhYmJhNzRkZjc0MmQ5ZWE0N2Q3NjU1NDg1Y2VkNGE0YzA0MjMwYmQ5NmRhYTA5ZjAxMTc4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7UWNkzImXUHbiUwG3a8uS1dyv_ae1hfQ8qQdpsdNNt8">
> 
> Some of the problems are:
> 
> * ~I also observe the half-sized RoomScreen that Julian saw.~ Edit: I fixed this in [Display read receipts next to each message as a row of Avatars for users who have seen that message #162](https://github.com/project-robius/robrix/pull/162)
> * The color contrast for the reaction button, both the green color and the gray color, is really low/bad. It's nearly impossible to read.
> * I can't tell when a reaction has been sent by a user. Please follow the same color/shading styles used by Element or Discord, they make it quite clear whether or not you have sent a reaction.
> * Each reaction button needs to set its cursor to `Hand` such that the user is aware they can click on it. Right now, there's no way for the user to know that each reaction button is a clickable element.
> * Lots of emoji are failing to be parsed. I'm not sure what you changed about my routine that parses the raw emoji into a text shortcode, but mine previously worked 100%, so you may just want to revert back to what I was doing previously.
>   
>   * Examples:
>   
>   ```
>   src/home/event_reaction_list.rs:186:21 - Failed to parse emoji: 👍️
>   src/home/event_reaction_list.rs:186:21 - Failed to parse emoji: ➕️
>   ```
> 
> The tooltip is nice, but is split across too many lines, making it hard to read. It should only be split into two lines by default (with the first line being "UserName reacted with:"), and should only spill over to more than 2 lines if the text is really really long. <img alt="image" width="421" src="https://private-user-images.githubusercontent.com/1139460/404029069-1e076042-9855-43ba-9f63-25a1463b46c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczMDQ2OTYsIm5iZiI6MTczNzMwNDM5NiwicGF0aCI6Ii8xMTM5NDYwLzQwNDAyOTA2OS0xZTA3NjA0Mi05ODU1LTQzYmEtOWY2My0yNWExNDYzYjQ2YzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTlUMTYzMzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE2N2ViMTE4MjVmYWQyYmQ1M2Y3ODgzN2Q1ODQxZThhNGRiNGU5NzFmYWI2ZDA3YjMzMzRiYjE1NmRkZDNhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zokkMod4rxPkJ4aGx07voHw_JueI9w91nyX8kvwom04">

Here is updated version.
https://github.com/user-attachments/assets/679ab04e-e14f-4c09-8b36-7b6eab774fe8

2025-01-20 07:34 UTC, kevinaboos requested changes
Nice job redesigning the reaction buttons! They look very nice & professional now. 

I also made a small commit of my own to fix the alignment of the tooltip as well as make the font size slightly larger.

There are a few very small things I'd like you to fix before I merge this in.

First, please make the callout arrow longer, maybe like 30-50% longer.

Second, the positioning of the callout triangle is a bit inconsistent. I think the easiest way to fix this is to make it vertically centered regardless of how many lines of text there are in the tooltip, but if you don't like that design then we can discuss other options, such as aligning the triangle _vertically_ with the first (or last) line of text inside of the tooltip.

Here's an example of what I mean. It looks perfect for a 2-line tooltip, but it looks kind of bad for a 1-line tooltip or a 3-line tooltip:
<img width="391" alt="image" src="https://github.com/user-attachments/assets/ceb0e3e0-2307-41e0-8a66-de157ea441c4" />

<img width="501" alt="image" src="https://github.com/user-attachments/assets/4c9d7ecc-9c68-420c-b818-c5bf0b2ffb0f" />

<img width="371" alt="image" src="https://github.com/user-attachments/assets/1740a4ce-5bef-44c9-b400-47d5fe72efd0" />

2025-01-20 07:38 UTC, kevinaboos commented on src/app.rs
> +    /// The current window geometry.
FYI, Rik recently added a "get current window" function to the `Cx` API, but we haven't upgraded our makepad version yet, so we can't use it right now.

2025-01-20 10:21 UTC, alanpoon commented on src/home/room_screen.rs
> +            cx.widget_action(widget_uid, &scope.path, RoomScreenTooltipActions::HoverOut);
\When the tooltip is up, the timeline may jump. This may take away the hover out event to required to clear the tooltip. I've moved to the jumping view logic

2025-01-20 11:41 UTC, alanpoon commented
> Nice job redesigning the reaction buttons! They look very nice & professional now.
> 
> I also made a small commit of my own to fix the alignment of the tooltip as well as make the font size slightly larger.
> 
> There are a few very small things I'd like you to fix before I merge this in.
> 
> First, please make the callout arrow longer, maybe like 30-50% longer.
> 
> Second, the positioning of the callout triangle is a bit inconsistent. I think the easiest way to fix this is to make it vertically centered regardless of how many lines of text there are in the tooltip, but if you don't like that design then we can discuss other options, such as aligning the triangle _vertically_ with the first (or last) line of text inside of the tooltip.
> 
> Here's an example of what I mean. It looks perfect for a 2-line tooltip, but it looks kind of bad for a 1-line tooltip or a 3-line tooltip:
> 
> <img alt="image" width="391" src="https://private-user-images.githubusercontent.com/1139460/404780574-ceb0e3e0-2307-41e0-8a66-de157ea441c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczNjg3NzksIm5iZiI6MTczNzM2ODQ3OSwicGF0aCI6Ii8xMTM5NDYwLzQwNDc4MDU3NC1jZWIwZTNlMC0yMzA3LTQxZTAtOGE2Ni1kZTE1N2VhNDQxYzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjBUMTAyMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzczNzg3NGZhOWI5N2ZhMzVlNDVhMmZlNzc5ZGU3OTQ0NzE2ZDUyODc1YTE4ODQ1NDc1NzM5YTU2NWMxMTAzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fsYe206Q7RudpGsc7FCQGIBlvAvX1fxOOLSDK_rHxCw"> <img alt="image" width="501" src="https://private-user-images.githubusercontent.com/1139460/404778310-4c9d7ecc-9c68-420c-b818-c5bf0b2ffb0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczNjg3NzksIm5iZiI6MTczNzM2ODQ3OSwicGF0aCI6Ii8xMTM5NDYwLzQwNDc3ODMxMC00YzlkN2VjYy05YzY4LTQyMGMtYjgxOC1jNWJmMGIyZmZiMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjBUMTAyMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQxMWVhNGJlNDdkNjA4NzM0M2ZkZWE3MzFmYTJkMmYyNWZmMjJkNWU0ZjFmY2FkYzNjNDA2ODIwN2E0Mzc1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Db9DLfrDDrI_egIBeLNiq1_-0bUEsznRGMpjAfun_u0"> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/1139460/404780638-1740a4ce-5bef-44c9-b400-47d5fe72efd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczNjg3NzksIm5iZiI6MTczNzM2ODQ3OSwicGF0aCI6Ii8xMTM5NDYwLzQwNDc4MDYzOC0xNzQwYTRjZS01YmVmLTQ0YzktYjQwMC00N2Q1ZmU3MmVmZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjBUMTAyMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Y0NTkwNTgzMjFhZTlmMjcxNDUxN2RkNDY3OTVhNDVkMzAyMmY3NmQ5ZWQ5ZWUzMDI4M2FmZGU5Zjk5MTBlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gynyFiC8L1CYaZY9eNvTfmM49w1s7ZDdLeacbLOttso">

Align the callout to the first line of the tooltip
Enlarge the callout arrow
https://github.com/user-attachments/assets/8c360b29-bb49-4310-a53e-2f48412b84c5

2025-01-20 19:10 UTC, kevinaboos commented on src/home/room_screen.rs
> +            cx.widget_action(widget_uid, &scope.path, RoomScreenTooltipActions::HoverOut);
oh ok yea that makes sense, thanks for clarifying and moving it

2025-01-20 19:52 UTC, kevinaboos approved these changes
Excellent work, looks great! Thanks very much.

2025-01-20 19:54 UTC, merged