added _animation for fade away for typing_notice
project-robius/robrix pull request #179
Opened 2024-10-09 06:13 UTC by alanpoon

https://github.com/user-attachments/assets/f1e2f667-957d-4a8b-9625-c4b9cd0de007

Fixed 3rd task of this issue
https://github.com/project-robius/robrix/issues/155

2024-10-11 08:43 UTC, ZhangHanDong commented
@alanpoon 
The vertical height of the notification background is a bit too large, can it be adjusted to be narrower? 

Also, resolve the conflict.

2024-10-11 09:48 UTC, alanpoon commented
> @alanpoon The vertical height of the notification background is a bit too large, can it be adjusted to be narrower?
> 
> Also, resolve the conflict.

Done.

2024-10-11 19:03 UTC, kevinaboos requested changes
Nice job, looks really good! 

Can you also make it sliding upwards when showing it too? That way the animation is symmetric when being shown and when being hidden.

I also think it'd look nicer if the animation was a little bit faster (like 25% faster), but that's ultimately up to you.

2024-10-12 03:21 UTC, alanpoon commented
> Nice job, looks really good!
> 
> Can you also make it sliding upwards when showing it too? That way the animation is symmetric when being shown and when being hidden.
> 
> I also think it'd look nicer if the animation was a little bit faster (like 25% faster), but that's ultimately up to you.

- Added Sliding upwards when showing. 
- Sped up the animation
- Height of typing_notice made narrower

https://github.com/user-attachments/assets/8dbc8eb2-3e45-4c41-a2ab-7a26cc09f94c

2024-10-30 07:41 UTC, kevinaboos submitted a review, later dismissed
Looks great, thanks very much!

Please resolve conflicts and then I will merge it in.

2024-10-30 08:21 UTC, alanpoon commented
resolved conflict and merged main

2024-10-30 18:03 UTC, kevinaboos approved these changes

2024-10-30 18:03 UTC, merged

2024-11-19 08:06 UTC, alanpoon commented on src/home/room_screen.rs
> -                        typing_animation.stop_animation();
[typing animat](https://github.com/project-robius/robrix/issues/259)