Combine PR for Send read receipt #86 +jump button for scroll #131
project-robius/robrix pull request #206
Opened 2024-10-15 04:09 UTC by alanpoon

https://github.com/project-robius/robrix/pull/152#pullrequestreview-2339114824

1. Implemented: Start a 5-second timeout timer whenever scrolling stops, and then after the timer has reached its timeout deadline, send the read receipts for the last visible event.
2. Modified Send fully Receipt condition to be executed only after scrolling past Fully Read Marker
3. Added obtaining Fully read marker's event_id Request

Added Jump to Top view
Added Jump to bottom badge counter

https://github.com/user-attachments/assets/77bd3a20-75bd-4f45-9516-0b3da3c36dae

2024-10-30 08:13 UTC, kevinaboos requested changes
See my comments about the Jump to Top (JTT) button -- we're not yet ready to properly implement that, so I think it should be removed, or at least hidden until we can fix it.

Everything else looks fine, thanks!

2024-10-30 08:13 UTC, kevinaboos commented on src/home/room_screen.rs
> +        }
this loop is *incredibly* expensive, especially for large timelines. 

One way to optimize it would be to break out of the loop once you iterate past an event that has a timestamp that is earlier than that of the fully-read event. That way you don't endlessly iterate through the entire timeline if you don't find the first unread event.

 break out of

2024-10-30 08:13 UTC, kevinaboos commented on src/home/room_screen.rs
> +        }
i think this behavior is incorrect and likely confusing for the user. It doesn't scroll to the first unread message, but just randomly scrolls up to the top of the current timeline view. It's better to do nothing, as that would be less confusing.

Given that we cannot yet implement the proper behavior for this (as it requires changing focus modes of the timeline to jump up to a certain "focused" event), we should just disable the JTT button.

2024-10-30 08:13 UTC, kevinaboos commented on src/sliding_sync.rs
> +    fully_read_event: Option<OwnedEventId>
when does this ever get updated? It seems to only get set one time upon program boot when ALL_ROOM_INFO gets established, which means that it will be wrong any time afterwards. 

Doesn't this need to be updated more often? For example, if the user reads some earlier messages on another device or client (like their phone), this will no longer be accurate.

I think you might be able to achieve this by using the `Client` to register an event listener for events of a certain type, kind of like what I do to listen for incoming verification requests.

2024-11-04 03:15 UTC, alanpoon commented on resources/icon_jump_to_top.svg
removed. Forgot to remove

2024-11-04 03:18 UTC, alanpoon commented on src/sliding_sync.rs
> +
removed line

2024-11-04 03:18 UTC, alanpoon commented on src/sliding_sync.rs
> +    .and_then(|ri|ri.fully_read_event.clone())
format fixed

2024-11-04 03:20 UTC, alanpoon commented on src/sliding_sync.rs
> +        .and_then(|f|Some(f.content.event_id));
format fix

2024-11-04 03:35 UTC, alanpoon commented on src/sliding_sync.rs
> +    fully_read_event: Option<OwnedEventId>
> when does this ever get updated? It seems to only get set one time upon program boot when ALL_ROOM_INFO gets established, which means that it will be wrong any time afterwards.
> 
> Doesn't this need to be updated more often? For example, if the user reads some earlier messages on another device or client (like their phone), this will no longer be accurate.
> 
> I think you might be able to achieve this by using the `Client` to register an event listener for events of a certain type, kind of like what I do to listen for incoming verification requests.

This is the red line marker event id. I am following the occurrence of the red line marker. It seems that the red line marker will only appear once at the start. Once scroll past it, it will begin to send the fully read receipt for all the messages. This field is used to set scroll_pass_read_marker to true and then not required anymore.

2024-11-04 04:41 UTC, alanpoon commented on src/home/room_screen.rs
> +        }
Yes, current behavior is that the user has to manually press the JTT button again.

2024-11-04 09:08 UTC, alanpoon commented on src/home/room_screen.rs
> +        }
disabling the JTT button for such scenario will require additional code to check if read marker is in timeline. Easiest way is the to set a boolean when drawing the TimelineItemKind::Virtualr ReadMarker.

2024-11-04 11:37 UTC, alanpoon commented on src/home/room_screen.rs
>          if self.fully_read_timer.is_event(event).is_some() {
@kevinaboos Currently on windows this line keeps returning true even when I commented out "self.fully_read_timer = cx.start_interval(5.0);" I heard there is a bug in makepad's timer.

2024-11-04 13:50 UTC, alanpoon commented on src/home/room_screen.rs
> +        }
https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/ruma/events/fully_read/struct.FullyReadEventContent.html
Does not provide timestamp for the read marker.

2024-11-04 23:29 UTC, kevinaboos commented on src/home/room_screen.rs
>          if self.fully_read_timer.is_event(event).is_some() {
kindly file an issue on makepad's github repo then, such that we can contact Rik about it. thanks!

2024-11-04 23:30 UTC, kevinaboos commented on src/sliding_sync.rs
> +    fully_read_event: Option<OwnedEventId>
that doesn't sound right. This might _start_ at the "red marker", but then once you actually send a new read receipt, you must update this to point to that latest event that was just considered read.

2024-11-04 23:32 UTC, kevinaboos commented on src/home/room_screen.rs
> +        }
Sure, my point is that we need a lot of additional code infrastructure to support jumping up to a point before the timeline's known history. This is currently blocking several features:
* jumping to old messages via a matrix.to link
* jumping to old replies when clicking on a reply preview
* this feature here: jumping to the first unread message.

Kindly just disable the JTT button and remove it until we have that high-level functionality implemented, and _then_ we can reintroduce a "jump to first unread message" button that actually works correctly. It is simply impossible to implement the JTT button correctly right now.

2024-11-06 06:05 UTC, alanpoon commented on src/home/room_screen.rs
>          if self.fully_read_timer.is_event(event).is_some() {
Ignore this. Now, I am wrapping the timer with an Option

2024-11-06 10:05 UTC, alanpoon commented on src/sliding_sync.rs
> +
fixed

2024-11-06 10:07 UTC, alanpoon commented on src/home/room_screen.rs
> +        }
Removed logic, scroll pass read marker boolean is determined by before sending MatrixRequest::ReadReceipt. The event_id assertion is determined over there.

2024-11-06 10:09 UTC, alanpoon commented on src/sliding_sync.rs
> +    fully_read_event: Option<OwnedEventId>
Added ```set_fully_read_event``` function after successfully sending out read receipt.

2024-11-06 10:10 UTC, alanpoon commented on src/home/room_screen.rs
> +        }
JTT button removed.

2024-11-06 10:10 UTC, alanpoon commented on src/home/room_screen.rs
> +    scroll_pass_read_marker: bool,
Added doc

2024-11-06 10:12 UTC, alanpoon commented
Currently there's a bug in the portallist's is_at_end function which returns true even when the scroll is not at the bottom. Hence the JTB will not show.
https://github.com/makepad/makepad/issues/579

2024-11-07 03:18 UTC, kevinaboos commented
> Currently there's a bug in the portallist's is_at_end function which returns true even when the scroll is not at the bottom. Hence the JTB will not show. [makepad/makepad#579](https://github.com/makepad/makepad/issues/579)

oh that's odd. I know RIk just made a change to that, but it was supposed to fix things. hmm.

2024-11-09 05:36 UTC, kevinaboos commented
> Currently there's a bug in the portallist's is_at_end function which returns true even when the scroll is not at the bottom. Hence the JTB will not show. [makepad/makepad#579](https://github.com/makepad/makepad/issues/579)

I fixed this today.

2024-11-09 05:38 UTC, kevinaboos commented
I've properly implemented the "jump-to-bottom unread badge" feature in #247, so kindly build this PR off of that as a starting point.

2024-11-11 20:56 UTC, kevinaboos commented
I've redesigned how the jump to bottom button works to make it easier to use. See #250 for the details, or just checkout the `jump_to_bottom_button.rs` file.

2024-11-11 23:24 UTC, alanpoon commented
> I've redesigned how the jump to bottom button works to make it easier to use. See #250 for the details, or just checkout the `jump_to_bottom_button.rs` file.

ok, will look at it

2024-11-14 02:52 UTC, alanpoon commented
Curr

> I've redesigned how the jump to bottom button works to make it easier to use. See #250 for the details, or just checkout the `jump_to_bottom_button.rs` file.

Currently, the portal_list.smooth_scroll_to_end is not terminating

2024-11-15 23:31 UTC, alanpoon commented
@CodiumAI-Agent /review

2024-11-23 04:07 UTC, alanpoon commented on src/home/room_screen.rs
>          if self.fully_read_timer.is_event(event).is_some() {
Using timer.is_empty to check

2024-11-25 13:24 UTC, ZhangHanDong commented on src/sliding_sync.rs
> +                            log!("{}", e.to_string());
change to:

```rust
error!(
        "Failed to fetch fully read event for room {}: {:#}",
        room_id, e
    );
```

2024-11-25 14:46 UTC, alanpoon commented on src/home/room_screen.rs
> +        };
fixed

2024-11-25 14:46 UTC, alanpoon commented on src/sliding_sync.rs
> +                            log!("{}", e.to_string());
fixed

2024-11-25 21:22 UTC, kevinaboos commented
> Curr
> 
> > I've redesigned how the jump to bottom button works to make it easier to use. See #250 for the details, or just checkout the `jump_to_bottom_button.rs` file.
> 
> Currently, the portal_list.smooth_scroll_to_end is not terminating, let me investigate

I've fixed this as of last week; I rewrote the entire `smooth_scroll_to()` function here: https://github.com/makepad/makepad/pull/600

2024-11-25 22:32 UTC, kevinaboos requested changes
Nice, the code is looking better and is certainly a lot more efficient and easier to understand!

It's good that you're querying the user's latest fully read state when you show the room timeline for the first time. However, that approach will only catch changes to the user's read receipt once, when the room is first shown. Imagine the following scenario:
* The user opens a room in Robrix
* Robrix is open, but sitting idle on their computer
* The user opens another client, e.g., on their phone
* New messages arrive for that room
* The user sees those new messages and interacts with them on their phone

Then, when the user returns to Robrix, the latest fully read receipt for that room will be wrong/outdated, because it didn't get updated while the user was interacting with their phone.

I think we actually need to _subscribe_ to this state change such that we can know if it has changed on other devices. (We can do this in a future PR, but if it's easy then we should just do it now.)

2024-11-25 22:32 UTC, kevinaboos commented on src/sliding_sync.rs
> +                            .and_then(|f| Some(f.content.event_id));
```suggestion
                            .map(|f| f.content.event_id);
```

2024-11-25 22:32 UTC, kevinaboos commented on src/sliding_sync.rs
> +pub fn take_fully_read_event(room_id: &OwnedRoomId) -> Option<(OwnedEventId, MilliSecondsSinceUnixEpoch)> {
Please rename this function, since this isn't _taking_ the event, it's just getting it and then returning a copy of it.

In Rust terminology, to `take` something means to remove the existing value and return it, replacing the existing value with the default. So when you "take" an option, it will always be `None` afterwards.


```suggestion
pub fn get_fully_read_event(room_id: &OwnedRoomId) -> Option<(OwnedEventId, MilliSecondsSinceUnixEpoch)> {
```

2024-11-25 22:32 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    }
are you sure this is necessary?  the [docs of `Timeline::send_multiple_receipts()`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_ui/timeline/struct.Timeline.html#method.send_multiple_receipts) state that it will check if the receipts are actually newer than the existing ones before sending the update. 

> This uses `Room::send_multiple_receipts` internally, but checks first if the receipts point to events in this timeline that are more recent than the current ones, to avoid unnecessary requests.

I think we already had this discussion before, so did anything change? For example, did you observe this function not obeying its documentation, to where it would send older receipts accidentally?

2024-11-25 22:32 UTC, kevinaboos commented on src/shared/jump_to_bottom_button.rs
> +            self.label(id!(unread_messages_count)).set_text(&format!("{}", unread_message_count));
we should probably limit it to a certain number of events such that the label doesn't look ridiculous if there are 10000000+ unread events. 

We could do something like up to two digits (a max value of 99) or three digits (a max value of 999) until we just show `99+` or `999+`. Depends on how wide the label can be while still looking good. 

Use your best judgment.

2024-11-26 02:42 UTC, ZhangHanDong commented on src/sliding_sync.rs
> +                    }
Maybe this can be kept., but clear comments should be added to explain the reason for keeping it.

Because the cost of this check is very low, local checks can avoid unnecessary network requests, which can improve system robustness in some scenarios.

```rust
if let Some((_existing_event_id, existing_timestamp)) = &room_info.fully_read_event {
    // We perform this check at the client level to:
    // 1. Maintain local state consistency
    // 2. Reduce unnecessary network requests
    // 3. Provide an additional safety layer even though send_multiple_receipts() 
    //    has similar checks
    if timestamp < *existing_timestamp {
        continue;
    }
}
```

2024-11-26 20:11 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    }
my point was that the actual Matrix SDK already performs this check for us, so we don't need to do this at all. 

In fact, if this is removed, it seems like it's not even necessary for us to store the `fully_read_event` within the `RoomInfo` struct, and then we could fully remove all the complexity associated with that. 

Theoretically we shouldn't need to bother with this, since the Matrix SDK will handle all of that for us.

2024-11-27 02:49 UTC, alanpoon commented on src/home/room_screen.rs
> +                        }
This is not the fully read receipt, this is the normal read receipt. I can remove this.

2024-11-27 03:07 UTC, alanpoon commented on src/home/room_screen.rs
> +                                .map(|room| room.num_unread_messages())
I thought acquiring a lock in main UI thread is okay. num_unread_messages is not an async function, so there is no point to spawn an async handler.

2024-11-27 03:56 UTC, alanpoon commented on src/sliding_sync.rs
> +                    }
Removed the additional timestamp check. Previously I was using send_multiple_receipt for FullyReadReceipt, which does not return a boolean value indicating sent status. Now I am switching to send_single_receipt for FullyRead and confirmed send status returning false for already sent message.

2024-11-27 06:33 UTC, alanpoon commented on src/home/room_screen.rs
> +                        }
Currently app_got_focus on windows only works in the makepad's latest rik branch.

2024-11-27 19:50 UTC, kevinaboos commented on src/home/room_screen.rs
> +                        }
I think that the app having focus probably isn't sufficient to determine if a user has seen a message. They could step away from the computer for 10+ mins while hundreds of messages fly past, and we don't want to mark those as read. We should stick with your original approach of only marking messages as read upon an actual user interaction, e.g., scrolling/clicking/etc.

2024-11-27 19:51 UTC, kevinaboos commented on src/home/room_screen.rs
> +                                .map(|room| room.num_unread_messages())
> I thought acquiring a lock in main UI thread is okay.

I mean, it's "okay" until it's suddenly not okay, e.g., when you hit contention for a lock, your UI drops frames. We want to minimize that as much as possible. 

>  num_unread_messages is not an async function, so there is no point to spawn an async handler.

Right, we don't need to spawn an async function for it. I'm saying we should acquire that info (call that function) in the background async task and then pass that information to the main UI thread as part of the `TimelineUpdate::NewItems` variant (by adding a field to it).

2024-11-27 19:52 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    }
nice, that sounds like a good improvement!

2024-11-27 19:55 UTC, kevinaboos commented on src/shared/jump_to_bottom_button.rs
> +            self.label(id!(unread_messages_count)).set_text(&format!("{}", unread_message_count));
Nice, looks pretty good. The circular background might need to be an oval/ellipse, since we need more padding on the left and right of the `99+` string to make it look more professional and readable.

I think if you set the `width` of the parent view of the label to be `Fit`, with a small amount of left & right padding, that should do it.

2024-11-28 08:52 UTC, alanpoon commented on src/home/room_screen.rs
> +                        }
Removed these lines of code

2024-11-28 08:52 UTC, alanpoon commented on src/home/room_screen.rs
> +                                .map(|room| room.num_unread_messages())
Move client num_of_unread to async

2024-11-30 13:24 UTC, Demolemon11 requested changes

2024-11-30 13:24 UTC, Demolemon11 commented on src/sliding_sync.rs
> +                let (_, sender) = {
If we don't need `timeline_ref`, no need to clone the ref, just `let sender = ...`, IMHP.

2024-12-03 07:04 UTC, alanpoon commented on src/sliding_sync.rs
> +                let (_, sender) = {
fixed

2024-12-03 07:06 UTC, alanpoon commented
> Nice, the code is looking better and is certainly a lot more efficient and easier to understand!
> 
> It's good that you're querying the user's latest fully read state when you show the room timeline for the first time. However, that approach will only catch changes to the user's read receipt once, when the room is first shown. Imagine the following scenario:
> 
> * The user opens a room in Robrix
> * Robrix is open, but sitting idle on their computer
> * The user opens another client, e.g., on their phone
> * New messages arrive for that room
> * The user sees those new messages and interacts with them on their phone
> 
> Then, when the user returns to Robrix, the latest fully read receipt for that room will be wrong/outdated, because it didn't get updated while the user was interacting with their phone.
> 
> I think we actually need to _subscribe_ to this state change such that we can know if it has changed on other devices. (We can do this in a future PR, but if it's easy then we should just do it now.)

Added subscribe_to_updates mechanism to update the latest read receipt in multiple devices.

2024-12-16 20:56 UTC, kevinaboos requested changes
In general, I think this looks pretty good. I left a few small comments, but I have one major request: let's just remove the concept of the 5-second timer. It's too complicated and will probably just confuse users. Let's just send the read receipt based on the user's scrolling actions, which should also make the code simpler and more efficient.

I think removing the timer is also consistent with what power users expect. For example, sometimes I just want to quickly skim the latest messages from 10 different rooms and consider those as fully read. That process should only take me a few seconds, not over 50 seconds (5 seconds for each room).

-----------

Also, I still don't think that storing the latest read receipt event in the `ALL_ROOM_INFO` map is the correct way to do things. It is inefficient, requires undesirable locking, and it doesn't even seem to be necessary.

Thus, let's consider how we could improve this. It looks like that info is only used within the RoomScreen, and it is a form of per-room data. Since we're already sending TimelineUpdates to the RoomScreen widget from the backend update subscriber, why wouldn't we just keep that information directly within each room's UI state? That way, we avoid locking, we avoid the overhead of adding and updating that info within the `ALL_ROOM_INFO` hashmap, and we avoid the memory usage of storing it in multiple different places.

What do you think about that approach? If you like it, please make the changes to follow that design instead.

2024-12-16 20:56 UTC, kevinaboos commented on src/home/room_screen.rs
> +    /// Last displayed event will be sent as fully read receipt
pro-tip: doc comments like this get rendered into Html, so you need to format them as full sentences rather than just sentence fragments across line breaks.
```suggestion
    /// Timer used to send fully-read receipts for the current room.
    ///
    /// We start a short (5 second) timer when the user scrolls down,
    /// if `scrolled_past_read_marker` is true. Then, we send a fully-read receipt
    /// for the last displayed event in this room.
```

2024-12-16 20:56 UTC, kevinaboos commented on src/home/room_screen.rs
> +        if self.fully_read_timer.is_event(event).is_some() && !self.fully_read_timer.is_empty() {
can you explain (and add a comment) why it's necessary to check that the `fully_read_timer` is not empty?

Also, what does it mean for a timer to be non-empty?

2024-12-16 20:56 UTC, kevinaboos commented on src/home/room_screen.rs
> +                        continue;
why `continue` here? that seems odd, as we typically wouldn't want to skip anything else beneath this point.

2024-12-16 20:56 UTC, kevinaboos commented on src/shared/jump_to_bottom_button.rs
> +
this unread messages label is not centered horizontally with respect to the jump-to-bottom button. You can try `align: {x: 0.5}` here, but I think you'll also need more than that change to make it perfectly centered.

2024-12-16 20:56 UTC, kevinaboos commented on src/shared/jump_to_bottom_button.rs
> +
The right-side padding of `2.0` will also make things look off-center too.

2024-12-16 20:56 UTC, kevinaboos commented on src/sliding_sync.rs
> +    /// Request to fetch the fully read event in the given room's timeline.
```suggestion
    /// Request to fetch the user's latest fully-read event for the given room.
```

2024-12-16 20:56 UTC, kevinaboos commented on src/sliding_sync.rs
> +    GetNumOfUnReadMessages {
```suggestion
    GetNumberUnreadMessages {
```

2024-12-16 20:56 UTC, kevinaboos commented on src/sliding_sync.rs
> +    SubscribeToUpdates {
SubscribeToRoomUpdates
```suggestion
    SubscribeToRoomUpdates {
```

2024-12-16 20:56 UTC, kevinaboos commented on src/sliding_sync.rs
> +                        if let Err(e) = sender.send(TimelineUpdate::NewItems { new_items: Vec::new().into(), changed_indices: 0..1,
Do not re-use `TimelineUpdate::NewItems` for this purpose. That is really confusing, and I can guarantee that it will result in timelines being mysteriously cleared by accident in the future, especially since you're sending an empty vector for `new_items`.

If you want to send this information to the UI thread, just use a dedicated enum variant for it.

2024-12-16 20:56 UTC, kevinaboos commented on src/sliding_sync.rs
> +                                .get("event_id") {
this is unreadable without proper formatting
```suggestion
                            if let Some(latest_active) = serde_json::to_value(room.read_receipts())
                                .unwrap_or_default()
                                .get("latest_active")
                                .unwrap_or(&serde_json::Value::Null)
                                .get("event_id")
                            {
```

2024-12-16 20:56 UTC, kevinaboos commented on src/sliding_sync.rs
> +                        ),
```suggestion
                        Ok(sent) => log!("{} fully read receipt to room {room_id} for event {event_id}", 
                            if sent { "Sent" } else { "Already sent" }
                        ),
```

2024-12-16 20:56 UTC, kevinaboos commented on src/sliding_sync.rs
> +    /// A broadcast receiver for room updates.
incorrect comment, this is not a receiver, it is boolean.

2024-12-16 20:56 UTC, kevinaboos commented on src/home/room_screen.rs
> +        submit_async_request(MatrixRequest::SubscribeToUpdates { room_id: room_id.clone(), subscribe: true });
and do you ever unsubscribe from these updates?

2024-12-16 20:56 UTC, kevinaboos commented on src/sliding_sync.rs
> +                            if let Some(latest_active) = serde_json::to_value(room.read_receipts())
surely there is an easier way to accomplish this?

Check out the docs for both `Room` and `Timeline` -- there are several methods related to getting the latest read receipt for a given user.
Here's one to get you started: https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_ui/timeline/struct.Timeline.html#method.latest_user_read_receipt

for ex

2024-12-25 08:13 UTC, alanpoon commented on src/home/room_screen.rs
> +                        continue;
As I moved unread_messages_count into the timeline new item, I add new timeline item that only contains the correct unread_messages_count and default value for the rest of the other parameters. Those values will cause issue in the process_timeline_updates function.

2024-12-25 11:15 UTC, alanpoon commented on src/shared/jump_to_bottom_button.rs
> +
![Screenshot 2024-12-25 at 7 10 00 PM](https://github.com/user-attachments/assets/3dc30229-c372-4333-bbf4-a85e657fc74f)
![Screenshot 2024-12-25 at 7 10 43 PM](https://github.com/user-attachments/assets/d9a07565-3b7a-474b-bf72-331b008af02d)
![Screenshot 2024-12-25 at 7 11 24 PM](https://github.com/user-attachments/assets/655ea6ba-ff59-49fd-a6ca-97ea2fc0de22)
Unread_count adjustment fixed

2024-12-26 02:30 UTC, alanpoon commented on src/sliding_sync.rs
> +    /// A broadcast receiver for room updates.
fixed

2024-12-27 07:50 UTC, alanpoon commented on src/sliding_sync.rs
> +                            if let Some(latest_active) = serde_json::to_value(room.read_receipts())
changed to subscribe to own user's read receipt changed event

2024-12-27 20:57 UTC, kevinaboos requested changes
Visually, things are looking good. Just need to fix the center alignment of the unread messages badge with respect to the jump-to-bottom button icon.

See my comments about code structure, specifically regarding the way that you handle subscribing to the own user's read receipts changes. This can be improved and done in a way that doesn't require accessing/modifying global states in `ALL_ROOM_INFO`.

2024-12-27 20:57 UTC, kevinaboos commented on src/home/room_screen.rs
> +    /// The index of the first item in the timeline that is currently visible
this comment isn't quite accurate. It looks like the `prev_first_index` state only gets updated when a `TimelineUpdate::NewItems` update occurs in the background, and the timeline view must jump to the new item index. 

Your comment makes it sounds like this index will always be pointing to the first visible item, but that is not correct. Please fix.

2024-12-27 20:57 UTC, kevinaboos commented on src/home/room_screen.rs
> +    /// Any new message coming in will reset scrolled_past_read_marker to false
as I mentioned previously, doc comments need to be written using proper markdown formatting, as they'll be rendered into paragraphs. So you need to use periods `.` or add empty blank lines for paragraph separation, or use bullet points.

2024-12-27 20:57 UTC, kevinaboos commented on src/sliding_sync.rs
> +    let subscribe_to_owned_user_read_receipt_changed: std::sync::Arc<tokio::sync::Mutex<BTreeMap<OwnedRoomId, bool>>> = Arc::new(tokio::sync::Mutex::new(BTreeMap::new()));
"subscribe_to_owned_user_read_receipt_changed" should be "own_user" or "current_user"

but, as per my other comment, I don't think this variable is necessary at all.

2024-12-27 20:57 UTC, kevinaboos commented on src/sliding_sync.rs
> +                        Result<(OwnedEventId, MilliSecondsSinceUnixEpoch),  anyhow::Error> {
proper formatting for a multi-line function signature is this:
```suggestion
                    async fn fetch_fully_read_event(
                        room: &Room,
                        room_id: &OwnedRoomId,
                    ) -> Result<(OwnedEventId, MilliSecondsSinceUnixEpoch),  anyhow::Error> {
```

2024-12-27 20:57 UTC, kevinaboos commented on src/sliding_sync.rs
> +                        }
if this fails, we still need to display _something_ to the user indicating that there are new messages. In this case, we know that there are new messages, but we just don't know how many because this call failed. 

Thus, we should still send a `NewUnreadMessagesCount` timeline update, but use an `Option` or `Result` to indicate that the call failed. Then, in the UI thread, we just display an empty green dot (with no unread messages count label content) to indicate that there is an unknown number of new messages.

2024-12-27 20:57 UTC, kevinaboos commented on src/sliding_sync.rs
> +                });
the entire structure of this read receipt subscriber loop is way too complex. Please refactor it to follow the format of the typing notice subscriber, which is also done on a per-room basis and supports both subscribing and unsubscribing, so it's quite similar to this case.

In addition, as I've said before, I still don't see why we need to store the latest fully-read event in the `ALL_ROOM_INFO. You can just obtain it when opening/showing a timeline (when the subscriber is first started) and then send it to the timeline via a `TimelineUpdate`, just like all other states. To determine if the read receipt event has changed, you can also keep track of the latest fully-read event ID in the subscriber task (outside of the `while (update_receiver.next().await).is_some() { }` loop body), such that you can know whether it has changed without having to store and access global states behind a bunch of mutexes.

2024-12-27 20:57 UTC, kevinaboos commented on src/sliding_sync.rs
> +}
based on my other comment, these can be removed. We shouldn't need to store fully-read events in the global set of `ALL_ROOM_INFO`, and we also don't _want_ to because it's quite expensive to be updating global state that frequently.

2024-12-27 20:57 UTC, kevinaboos commented on src/home/room_screen.rs
> +                        if let Some(room_id) = &self.room_id {
here, we know that there are unread messages, but we just don't know how many. Thus, we should set the jump_to_bottom button's unread message badge to be visible, but with an empty label (such that it just shows an empty green circle). 
Then, once we receive the updated count of unread messages, we can update the label count. 

To accomplish this, we probably need to change `show_unread_message_badge()` to accept an `Option<u64>`:
* `Some(0)` means we know there are no unread messages, so hide the badge entirely and clear the count label.
* `Some(x) if x > 0` means we know the exact number of unread messages, so display both the badge and the count label.
* `None` means we know that there are unread messages, but we just don't know how many, so we show the badge but clear the count label.

You could also create a custom enum with 3 variants that would make it even more clear and easy to understand. (we should probably do this instead of abusing `Option` for this purpose)

2024-12-30 03:21 UTC, alanpoon commented on src/home/room_screen.rs
> +                        if let Some(room_id) = &self.room_id {
![Screenshot 2024-12-30 at 11 17 51 AM](https://github.com/user-attachments/assets/105f545e-f77b-42cf-a2cb-0f6d4388174d)
It seems that the empty green circle only occurs in the jump to top button to highlight the jump to top button. I don't think there is a good reason to account for unknown number of unread messages in the jump to bottom button.

2024-12-30 03:53 UTC, alanpoon commented on src/home/room_screen.rs
> +    /// Any new message coming in will reset scrolled_past_read_marker to false
fixed

2024-12-30 04:55 UTC, kevinaboos commented on src/home/room_screen.rs
> +                        if let Some(room_id) = &self.room_id {
well, yes, there is a good reason -- the same reason that I initially added the unread message badge for. When new messages come in, there is no way for the user to know about it unless we add this visual indicator. 

For example, if we do successfully receive new timeline items that are appended to the timeline (beneath the current viewport), but for some reason the request for the number of unread messages _fails_ randomly, then we won't ever be able to notify the user that new messages are available.

For that reason, it's important to show an empty green badge on the jump-to-bottom button, as it'll provide useful info to the user in the unlikely event that we cannot obtain the number of unread messages.

2024-12-30 07:12 UTC, alanpoon commented on src/home/room_screen.rs
> +    /// The index of the first item in the timeline that is currently visible
fixed

2024-12-30 07:17 UTC, alanpoon commented on src/sliding_sync.rs
> +                        }
Added "jump_to_bottom.show_unread_message_badge(cx, UnReadMessageCount::Unknown);" before                             submit_async_request(MatrixRequest::GetNumberUnreadMessages{ room_id: room_id.clone() });

2024-12-31 03:16 UTC, alanpoon commented on src/sliding_sync.rs
> +                });
I have removed get_fully_read_event, and send it to the timeline via a TimelineUpdate. But the typing notice subscribe has extra event drop handler. Subscribe to "own read receipt changed" does not have event drop handler.  I do not know how to follow the format of typing notice subscriber.

2024-12-31 03:16 UTC, alanpoon commented on src/sliding_sync.rs
> +}
removed

2024-12-31 03:21 UTC, alanpoon commented on src/home/room_screen.rs
> +                        if let Some(room_id) = &self.room_id {
Added UnReadMessageCount enum
/// The number of unread messages in the room
#[derive(Clone, Debug)]
pub enum UnReadMessageCount {
    /// Display green badge without text
    Unknown,
    /// Display green badge and text for the number of unread messages
    Known(u64)
}

2024-12-31 17:47 UTC, kevinaboos commented on src/sliding_sync.rs
> +                        }
perfect!

2024-12-31 17:49 UTC, kevinaboos commented on src/home/room_screen.rs
> +                        if let Some(room_id) = &self.room_id {
nice, good enum design

2024-12-31 17:57 UTC, kevinaboos commented on src/sliding_sync.rs
> +                });
I'll take a look at the options we have to unsubscribe, but as a last resort, you can always just store the `_to_updates_task` JoinHandle in the `RoomInfo` struct and then kill it manually via [`JoinHandle::abort()`](https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html#method.abort). There might be a better way though.

2024-12-31 19:57 UTC, kevinaboos requested changes
left some more comments.

It appears that you haven't yet addressed my previous requests [here](https://github.com/project-robius/robrix/pull/206#pullrequestreview-2524365931) and [here](https://github.com/project-robius/robrix/pull/206#discussion_r1898374941) to properly center-align the unread messages badge with the jump-to-bottom button. Please fix that, and then we can merge this in.

We can add the subscribe/unsubscribe functionality later if you can't solve it here in this PR. I have some solutions in mind.

2024-12-31 19:57 UTC, kevinaboos commented on src/home/room_screen.rs
> +    /// The previous first index of the portallist before timeline receives new item, scroll changes or timeline view jumps
```suggestion
    /// The index of the first item shown in the timeline's PortalList from *before* the last "jump".
    ///
    /// This index is saved before the timeline undergoes any jumps, e.g.,
    /// receiving new items, major scroll changes, or other timeline view jumps.
```

2024-12-31 19:57 UTC, kevinaboos commented on src/home/room_screen.rs
> +    /// Any new message coming in will reset the value to false.
you got closer, but here's what I mean by properly formatted paragraphs.
```suggestion
    /// Whether the user has scrolled past their latest read marker.
    ///
    /// This is used to determine whether we should send a fully-read receipt
    /// after the user scrolls past their "read marker", i.e., their latest fully-read receipt.
    /// Its value is determined by comparing the fully-read event's timestamp with the
    /// first and last timestamp of displayed events in the timeline.
    /// When scrolling down, if the value is true, we send a fully-read receipt
    /// for the last visible event in the timeline.
    ///
    /// When new message come in, this value is reset to `false`.
```

2024-12-31 19:57 UTC, kevinaboos commented on src/shared/jump_to_bottom_button.rs
> +pub enum UnReadMessageCount {
be consistent with naming: "Unread" is one word.
```suggestion
pub enum UnreadMessageCount {
```

2024-12-31 19:57 UTC, kevinaboos commented on src/shared/jump_to_bottom_button.rs
> +    /// Display green badge without text
the fact that it's green is just an implementation detail that may change.
```suggestion
    /// There are unread messages, but we do not know how many.
```

2024-12-31 19:57 UTC, kevinaboos commented on src/shared/jump_to_bottom_button.rs
> +    /// Display green badge and text for the number of unread messages
```suggestion
    /// There are unread messages, and we know exactly how many.
```

2024-12-31 19:57 UTC, kevinaboos commented on src/sliding_sync.rs
> +                        log!("Skipping pagination request for not-yet-known room {room_id}");
fix copy-paste error message here
```suggestion
                        log!("Skipping get number of unread messages request for not-yet-known room {room_id}");
```

2024-12-31 19:57 UTC, kevinaboos commented on src/sliding_sync.rs
> +                        .and_then(|c| c.get_room(&room_id)).map(|room| room.num_unread_messages())
you can do this way faster if you get the `timeline` from the `ALL_ROOM_INFO` in the above block, and then call `timeline.room().num_unread_messages()`.

no need to get the client and then get the room that way.

2024-12-31 19:57 UTC, kevinaboos commented on src/sliding_sync.rs
> +                            log!("Failed to send timeline update: {e:?} for NumOfUnReadMessages request for room {room_id}");
nit: use consistent word capitalization: "Unread", not "UnRead"

2024-12-31 19:57 UTC, kevinaboos commented on src/sliding_sync.rs
> -
can you restore the removed whitespace here and on Lines 1008 and 1342? those were intentional.

2024-12-31 19:57 UTC, kevinaboos commented on src/shared/jump_to_bottom_button.rs
> +
bump

2025-01-01 01:44 UTC, alanpoon commented on src/sliding_sync.rs
> +                            log!("Failed to send timeline update: {e:?} for NumOfUnReadMessages request for room {room_id}");
fixed

2025-01-01 01:45 UTC, alanpoon commented on src/sliding_sync.rs
> -
Could you check again for issue?

2025-01-01 01:55 UTC, kevinaboos commented on src/sliding_sync.rs
> -
sure, but you have some CI errors, kindly fix those first.

2025-01-01 02:23 UTC, alanpoon commented
> left some more comments.
> 
> It appears that you haven't yet addressed my previous requests [here](https://github.com/project-robius/robrix/pull/206#pullrequestreview-2524365931) and [here](https://github.com/project-robius/robrix/pull/206#discussion_r1898374941) to properly center-align the unread messages badge with the jump-to-bottom button. Please fix that, and then we can merge this in.
> 
> ~We can add the subscribe/unsubscribe functionality later if you can't solve it here in this PR. I have some solutions in mind.~
> 
> I will add the unsubscribing functionality myself in a future PR, so don't worry about it now. Let's move forward and get this PR finished up.

![Screenshot 2025-01-01 at 10 21 33 AM](https://github.com/user-attachments/assets/9bbe6f8d-f074-4e39-b97f-52dc562b7976)
Fixed center align issue

2025-01-02 20:39 UTC, kevinaboos approved these changes
Thanks very much! I'm pleased to say that this is finally ready to merge. I appreciate your patience and dedication to getting things right.

I did have to make some changes, please take a look to get a sense of the code style and type of improvements i was hoping for: https://github.com/project-robius/robrix/pull/206/commits/ab540fdc55ae8cbf4acc4813e39a8f1603b5cad6

2025-01-02 20:43 UTC, kevinaboos approved these changes

2025-01-02 20:45 UTC, merged

2025-01-03 02:37 UTC, alanpoon commented
> Thanks very much! I'm pleased to say that this is finally ready to merge. I appreciate your patience and dedication to getting things right.
> 
> I did have to make some changes, please take a look to get a sense of the code style and type of improvements i was hoping for: [ab540fd](https://github.com/project-robius/robrix/commit/ab540fdc55ae8cbf4acc4813e39a8f1603b5cad6)

Ok noted