Display a list of popup notifications in the top-right of the application window
project-robius/robrix pull request #211
Opened 2024-10-22 06:17 UTC by alanpoon

Fixes: https://github.com/project-robius/robrix/issues/121
Uses popup notification widget in makepad
<img width="671" alt="popup" src="https://github.com/user-attachments/assets/01f51016-e1cb-4af9-be51-e8f1abcb7dd9">

2024-10-22 06:35 UTC, alanpoon commented
<img width="208" alt="popup_white_background" src="https://github.com/user-attachments/assets/604ae033-22fa-42ce-bd97-a98f760ad419">
changed to white background, and added more top margin

2024-10-30 08:25 UTC, kevinaboos requested changes
very nice work! 

Looks like the top margin of the popup list could be increased a bit more in order to be even with (equal to) the right margin?

One quick thing -- kindly keep the status label there and restore all of the code that sends status updates, as that should still be used for persistent messages and data that we want to show.

Your nice new popup view should be used for errors and things that need to get the user's attention. After you do that, I'll merge this in and then use your nice `enqueue_popup_notification` in a few other places.

2024-10-30 08:25 UTC, kevinaboos commented on resources/close.svg
we already have a close button svg in use

2024-10-30 13:28 UTC, alanpoon commented
> very nice work!
> 
> Looks like the top margin of the popup list could be increased a bit more in order to be even with (equal to) the right margin?
> 
> One quick thing -- kindly keep the status label there and restore all of the code that sends status updates, as that should still be used for persistent messages and data that we want to show.
> 
> Your nice new popup view should be used for errors and things that need to get the user's attention. After you do that, I'll merge this in and then use your nice `enqueue_popup_notification` in a few other places.

- restored the status label  and all of the code that sends status updates
- increased top margin
<img width="184" alt="popupnew" src="https://github.com/user-attachments/assets/7f8fae6e-4a2b-4498-8808-a2d8644e395b">

2024-10-30 19:46 UTC, kevinaboos commented
@joulei @jmbejar doesn't Makepad (or perhaps Moly) already offer a list of in-app notification popups like this? Wondering if we can re-use them or if there's a difference in what Alan has implemented here.

2024-10-31 01:28 UTC, alanpoon commented
> @joulei @jmbejar doesn't Makepad (or perhaps Moly) already offer a list of in-app notification popups like this? Wondering if we can re-use them or if there's a difference in what Alan has implemented here.

Moly's implementation of popup notification overwrites the previous one. Maybe @Guocork can also help to review.

2024-10-31 06:36 UTC, kevinaboos commented
> Moly's implementation of popup notification overwrites the previous one. Maybe @Guocork can also help to review.

No worries. I spoke with Julian tonight and he said that your implementation here is the latest one, and we'll eventually upstream yours into makepad. 💪👍

2024-11-04 23:57 UTC, kevinaboos requested changes
just noticed that this PR inserts an action handler at the very top App level of action handling; that is way too expensive. Hopefully not necessary, but if it is, then we must redesign the popup list widget to avoid that requirement.

2024-11-04 23:57 UTC, kevinaboos commented on src/app.rs
> +        log!("Showing login view");
remove inaccurate log stmt
```suggestion
```

2024-11-04 23:57 UTC, kevinaboos commented on src/app.rs
> +        self.ui.popup_notification(id!(popup)).open(cx);
why are we opening the popup notification once at startup and then again upon _every_ action handled by the app? The latter is very _very_ expensive... hopefully that isn't necessary and can be removed (?)

2024-11-05 12:14 UTC, alanpoon commented on src/app.rs
> +        self.ui.popup_notification(id!(popup)).open(cx);
I am removing the one in the handle_actions. I am using the popup_notification in makepad, primarily for the its' self.draw_list.begin_overlay_reuse(cx). It is closed by default. I've tried to recreate my own popup_notification widget but to no avail. The close method won't be used. I am rendering based on the popup notification list.

2024-11-07 03:25 UTC, kevinaboos commented on src/app.rs
> +        self.ui.popup_notification(id!(popup)).open(cx);
this is the perfect use case for code comments. Please format your above message as a nice clean source code comment, and put it right above Line 187 such that everyone knows why we have to open a popup notification at the beginning of app startup.  Without a clarifying comment, the code is confusing.

2024-11-07 19:44 UTC, kevinaboos requested changes
Sorry to be a stickler about this, but you didn't actually address [my comment here](https://github.com/project-robius/robrix/pull/211#discussion_r1832000697) about adding code comments describing _why_ we are unconditionally opening a popup upon app startup. Please don't mark conversations as resolved until you actually do resolve the issue being discussed. Thanks.

2024-11-22 00:13 UTC, kevinaboos commented
@alanpoon  friendly bump on this -- it seems to be 99% ready, but just needs a small code comment and the merge conflicts resolved.

2024-11-22 04:05 UTC, alanpoon commented
> @alanpoon friendly bump on this -- it seems to be 99% ready, but just needs a small code comment and the merge conflicts resolved.

Thanks for informing. Done

2024-11-22 08:10 UTC, univerz commented on src/shared/popup_list.rs
> +        }
i tried it in my project & had to add a redraw in case nothing else triggered it.

```suggestion
        }
        cx.redraw_all();
```

2024-11-22 09:41 UTC, joulei commented on src/shared/popup_list.rs
> +        }
I'd be very much against this, `cx.redraw_all()` will redraw the entire UI, we should only use that when absolutely necessary.
Can we find to get this working by just redrawing `PopupList`?

2024-11-25 02:53 UTC, alanpoon commented on src/shared/popup_list.rs
> +        }
changed to cx.redraw_area

2024-11-25 20:29 UTC, kevinaboos requested changes
Unfortunately, while testing this PR, I observe noticeably slower performance on this branch than on `main`, even when no popups are shown.

I think this problem is related to the general design philosophy of the popup list, which is that the widget is "always open". I believe we'll need to completely re-think how this is implemented such that there is _no runtime cost_ when there are no items being shown. And when popups _are_ shown, we shouldn't have significant overhead imposed on the entire UI just to show a simple floating popup. 

A potentially related problem is that because of where the popup list is defined (at the very top of the app, where it unfortunately has to be placed), its event handler gets invoked for every single action that propagates through the entire system. That is very expensive and likely at least _part_ of the cause for the performance drop. 

I think we should take a look at how Moly (previously Moxin) implements their popup (though it is a single popup and not a list of popups), which is defined here: https://github.com/moxin-org/moly/blob/a82d297b155fa64efd2cdb5d6b14c89148a1c70b/src/app.rs#L123-L127
I'm not sure if they face a similar performance degradation; that same problem might actually be present in Moly too, so maybe it's not that useful to follow their approach. @joulei might know more. 

------------------
Other top-level comments: 
* Only show popups for errors or other things that the user _must_ know about, and would not otherwise be able to determine.
  * For example, all of the status messages about being logged in should _not_ warrant a popup being shown, as it is very obvious from the state of the UI that the user has logged in successfully.
  * If you're able to implement an automatic dismissal of the popup after a given time period, then we can use the popup list for more user-facing messages, such as the login. Otherwise, it's really annoying for a user to have to manually clear all of these popups that will always show up upon login, especially when they're unnecessary and don't tell the user anything that they don't already know.
* We will very shortly need additional functionality for this popup list to be useful. If you want to save that for later, that's fine, but we might also want to consider implementing it right now in this PR so that we don't have to do a bunch of refactoring later. That's up to you. Here's some of the additional functionality we'll need:
  * Auto-dismissing popups, as mentioned above
  * Popups with arbitrary content in their view (e.g., buttons, links, etc) rather than just a simple String message
  * The ability to update the content of an existing popup message.
  * A different way of displaying popups on mobile. This can be as simple as centering them on the top of the app window and having them take up 90% of the app window width, much like a regular notification. Display popups on the top right of a mobile app will look strange.

2024-11-26 16:04 UTC, alanpoon commented on src/shared/popup_list.rs
> +        while let Some(message) = POPUP_NOTIFICATION.pop() {
This segqueue pop could be performance bottleneck. Refcell is faster. 
<img width="476" alt="refcell" src="https://github.com/user-attachments/assets/ce3e04e0-8673-4977-b8cd-088013486b35">

2024-11-26 22:49 UTC, kevinaboos commented on src/shared/popup_list.rs
> +        while let Some(message) = POPUP_NOTIFICATION.pop() {
that seems highly unlikely to be the root cause. I think it's more likely that a Makepad-level design problem is the cause, e.g., how the popup list is implemented and drawn, or how actions/events are handled by it.

Also, how can you have a multi-threaded RefCell? That's fundamentally unsafe; it would have to be a full Mutex with atomic locking to be safe in a multithreaded context.

2024-12-27 13:41 UTC, joulei reviewed
Mhh, I'm not seeing an obvious performance drop (UI jankiness, slower at switching rooms, etc) on this branch compared to `main`, @kevinaboos do you have a screen record where I can see that?
That said, I'm leaving comments (separate to this one) on a few small issues that could add up in the long run.

**Here are some _rough_ numbers from PopupList on my m2 (release build)**:
- `draw_walk`:
    Avg time: 37 microseconds
- `handle_actions`:
    Range: 1-29 microseconds
    Most actions take 1-4 microseconds
    One spike (when opening the first room) to 29 microseconds
- `handle_event` (the section processing the notifications):
    Range: 1-9 microseconds (0.001-0.009ms)
    Most processing takes 1 microsecond
    Biggest spike to 9 microseconds

I don't think action handling should be a problem here, everything visible on the screen is processing every single event and action. This would be just one more widget that does that. We're not creating actions here that would be propagating endlessly either.
If this was an issue, perhaps making the `PopupList` invisible and only making it visible whenever there are notifications to display could show an improvement. Perhaps this widget could be "dumber" where you make it visible from outside and push notifications to it through `PopupListRef`. However you'd still need to check for notifications in App.
Again it seems to take ~ 1 microsecond to check for notifications on every event, but if that was a problem perhaps this should be more "on demand" rather than poll-based.

**Constant redrawing**
One thing I see going on is constant redrawing of this widget, however currently there's constant redrawing of almost everything in Robrix. Simple mouse movements trigger redrawing of a lot of things, even if those things are not being hovered or directly affected.
We're currently investigating on some Makepad tools to make debugging of these unnecessary redraws easier. In the past I've found a few custom widgets in Robrix going into redraw loops or unnecessarily redrawing on any event, but they were usually quite obvious, that's not always the case.

I think we should fix the unnecessary redrawing happening throughout the UI and then come back to this. It's quite hard to debug otherwise.

2024-12-27 13:41 UTC, joulei commented on src/shared/popup_list.rs
> +    }
Here we could check if the popups list is empty, and if so do an early return of `DrawStep::done()`, avoiding the unnecessary `begin_turtle()`. Otherwise this stacks a bunch of empty turtles on each draw.

2024-12-27 13:41 UTC, joulei commented on src/shared/popup_list.rs
> +        cx.redraw_area(self.area());
NIT: you can simplify this with a `self.redraw(cx);`

2024-12-27 13:41 UTC, joulei commented on src/shared/popup_list.rs
> +    }
Here we're not removing the popup from the `self.popups`, we should do so otherwise it'll leak memory for each view that goes unused.

2024-12-27 21:01 UTC, kevinaboos commented
Ok thanks for double checking everything. In that case, once @alanpoon addresses your comments to optimize the pop-up list further, I'll merge it in. 

> I think we should fix the unnecessary redrawing happening throughout the UI and then come back to this. It's quite hard to debug otherwise.

Agreed. It's likely that the performance hiccups I observed were coincidental, and not the fault of this PR. I'm actually blissfully unaware of unnecessary redraws happening, so yes, we should absolutely fix that whenever possible.

2024-12-27 21:09 UTC, kevinaboos commented
> perhaps making the `PopupList` invisible and only making it visible whenever there are notifications to display could show an improvement.

yeah, i think this is a good idea too. @alanpoon

2025-01-02 09:28 UTC, alanpoon commented on src/shared/popup_list.rs
> +        cx.redraw_area(self.area());
fixed

2025-01-02 11:52 UTC, alanpoon commented on src/shared/popup_list.rs
> +    }
fixed

2025-01-02 12:00 UTC, alanpoon commented
> Mhh, I'm not seeing an obvious performance drop (UI jankiness, slower at switching rooms, dragging tab, scrolling messages, etc) on this branch compared to `main`, @kevinaboos do you have a screen record where I can see that? That said, I'm leaving comments (separate to this one) on a few small issues that could add up in the long run.
> 
> **Here are some _rough_ numbers from PopupList on my m2 (release build)**:
> 
> * `draw_walk`:
>   Avg time: 37 microseconds
> * `handle_actions`:
>   Range: 1-29 microseconds
>   Most actions take 1-4 microseconds
>   One spike (when opening the first room) to 29 microseconds
> * `handle_event` (the section processing the notifications):
>   Range: 1-9 microseconds (0.001-0.009ms)
>   Most processing takes 1 microsecond
>   Biggest spike to 9 microseconds
> 
> I don't think action handling should be a problem here, everything visible on the screen is processing every single event and action. This would be just one more widget that does that. We're not creating actions here that would be propagating endlessly either. If this was an issue, perhaps making the `PopupList` invisible and only making it visible whenever there are notifications to display could show an improvement. Perhaps this widget could be "dumber" where you make it visible from outside and push notifications to it through `PopupListRef`. However you'd still need to check for notifications in App. Again it seems to take ~ 1 microsecond to check for notifications on every event, but if that was a problem perhaps this should be more "on demand" rather than poll-based.
> 
> **Constant redrawing** One thing I see going on is constant redrawing of this widget, however currently there's constant redrawing of almost everything in Robrix. Simple mouse movements trigger redrawing of a lot of things, even if those things are not being hovered or directly affected. We're currently investigating on some Makepad tools to make debugging of these unnecessary redraws easier. In the past I've found a few custom widgets in Robrix going into redraw loops or unnecessarily redrawing on any event, but they were usually quite obvious, that's not the case at the moment.
> 
> I think we should fix the unnecessary redrawing happening throughout the UI and then come back to this. It's quite hard to debug otherwise.

Thanks for finding the bug. When the popup notification widget is not closed, there is constant redrawing when the mouse move. I have added Actions to close and open the popup notification widget respectively.

2025-01-02 21:09 UTC, kevinaboos commented
> Thanks for finding the bug. When the popup notification widget is not closed, there is constant redrawing when the mouse move. I have added Actions to close and open the popup notification widget respectively.

Very nice! Glad you were able to fix it; I will test it soon to see if the UI jank & stutters are resolved.

2025-01-02 23:41 UTC, kevinaboos requested changes
Nice job fixing the performance issues! I can confirm there is a lot less UI stuttering now; we'll fix the general problem of excessive redraws later.

I did leave a few comments about how to further simplify the design of a popup notification by reducing its state, so please try those design changes.

The only other major issue is that the _layout_ of current popup notification is rather wasteful. I think the main problem is that the button itself occupies all of the vertical space below it, meaning that the popup text label is a lot narrower than it should be, which causes it to wrap to the next line a lot sooner than it should. Here's a screenshot showing what I mean:
<img width="214" alt="image" src="https://github.com/user-attachments/assets/66dfea41-5444-4fbf-a8f3-58f8f19c4f76" />

All of this space is wasted:
<img width="214" alt="image" src="https://github.com/user-attachments/assets/b5312f29-c829-4aa5-a4b8-92786b3a2ec2" />


Kindly redesign the button layout to avoid that wasted space.

-------------

We should also maintain consistency in the appearance of the `X` close button used across different views in Robrix. Let's use the same close button icon and design that is used in the user profile sliding pane, which is a bit more minimal and has a clearer hover-in action already built into it. See below:

<img width="289" alt="image" src="https://github.com/user-attachments/assets/679c403c-8d6a-498c-890b-0819f0c5ac6e" />


The code for that button is here: https://github.com/project-robius/robrix/blob/5fd345315e3ec09d70e23e950fda60a12990d08d/src/profile/user_profile.rs#L303-L318

You can copy it but reduce the padding a bit so it appears smaller, which will make it fit better into the popup notification list.

-------------

Separately, we can also make the popup list a little bit wider, as it's currently too small. However, you must ensure that it doesn't exceed the width of the window (including margin + padding).

2025-01-02 23:41 UTC, kevinaboos commented on src/shared/popup_list.rs
> +        }
this sequence of many separate loop iterations and allocations seems rather expensive. Is there a way to improve this? Here are some ideas, but you can also think of others:
* use one of Rust's existing methods to mutate a list while iterating over it: `retain`, `drain`, `extract_if`, etc
* try to combine and reduce the number of separate states in `PopupList`. Currently you have both `popups` and `popup_data`, but that doesn't seem to be strictly necessary. I think you could combine `popup_data` into `popups` by creating and populating the view directly with the text content rather than storing them separately.
  * This design would also work better in the future when we want to enable any arbitrary content to be shown within a popup, not just simple text.

2025-01-02 23:41 UTC, kevinaboos commented on src/shared/popup_list.rs
> +        }
the second bullet point there would also simplify the draw routine too, as a bonus.

2025-01-02 23:41 UTC, kevinaboos commented on src/shared/popup_list.rs
> +            room_status_label = <Label> {
why is this called `room_status_label`? seems like an odd name choice since it has nothing to do with rooms.

2025-01-02 23:41 UTC, kevinaboos commented on src/app.rs
> +            }
nit: you can combine the `match` and `if` statement:
```suggestion
            match action.downcast_ref() {
                Some(PopupNotificationAction::Open) => {
                    self.ui.popup_notification(id!(popup)).open(cx);
                }
                Some(PopupNotificationAction::Close) => {
                    self.ui.popup_notification(id!(popup)).close(cx);
                }
                _ => {}
            }
```

2025-01-15 03:48 UTC, alanpoon commented on src/shared/popup_list.rs
> +            room_status_label = <Label> {
fixed

2025-01-15 05:57 UTC, alanpoon commented on src/shared/popup_list.rs
> +        }
fixed

2025-01-17 00:20 UTC, kevinaboos requested changes
Code looks good, just left a few small comments.

One larger issue is that the Message widget's action bar is currently being displayed _over_ the popup notification list. See screenshot here:
<img width="930" alt="image" src="https://github.com/user-attachments/assets/3b95b6eb-e112-4e26-9f5f-5ea5cb0cb8b1" />

I don't _think_ that's the fault of your popup notification widget, but double check and let me know. It's probably caused by the action bar widget.

2025-01-17 03:38 UTC, alanpoon commented on src/shared/popup_list.rs
> +    /// when it is closed by the user. The list will be redrawn after pushing a new popup.
fixed

2025-01-17 06:01 UTC, alanpoon commented on src/shared/popup_list.rs
> +                align: {x: 0.98}
fixed

2025-01-17 06:02 UTC, alanpoon commented on src/app.rs
> +}
fixed

2025-01-17 09:35 UTC, univerz commented
> When the popup notification widget is not closed, there is constant redrawing when the mouse move. I have added Actions to close and open the popup notification widget respectively.

would it be possible to solve this without leaking this functionality to parent widget?

2025-01-17 23:07 UTC, kevinaboos commented
> One larger issue is that the Message widget's action bar is currently being displayed _over_ the popup notification list. See screenshot here: <img alt="image" width="930" src="https://private-user-images.githubusercontent.com/1139460/404077893-3b95b6eb-e112-4e26-9f5f-5ea5cb0cb8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcxNTU0MzYsIm5iZiI6MTczNzE1NTEzNiwicGF0aCI6Ii8xMTM5NDYwLzQwNDA3Nzg5My0zYjk1YjZlYi1lMTEyLTRlMjYtOWY1Zi01ZWE1Y2IwY2I4YjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTdUMjMwNTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGYyNzNjYjFkMGJmNjBiMDIwMWIyNDFjNDA4MGNjN2RkM2I5Nzk5NDM1ZTJlN2MxNGFkMGE2YTVhNjAxNTc3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PX6w_M_VmsFHI0xJNVAJYRwtkSTm5FU6Yf5BGOi0Q1k">
> 
> I don't _think_ that's the fault of your popup notification widget, but double check and let me know. It's probably caused by the action bar widget.

as I suspected, this isn't your fault -- the action bar also utilizes the same PopupNotification widget from Makepad, so we'll need to change that.

2025-01-17 23:08 UTC, kevinaboos commented
> > When the popup notification widget is not closed, there is constant redrawing when the mouse move. I have added Actions to close and open the popup notification widget respectively.
> 
> would it be possible to solve this without leaking this functionality to parent widget?

probably, but it might require some redesigning of how actions work. In general we need to review all the redraws that Robrix is doing since apparently it's overkill atm, but that'll have to wait until Feb.

2025-01-17 23:12 UTC, kevinaboos submitted a review, later dismissed
Looks good, thanks very much for your hard work on this feature! I'm approving it now but will make some slight tweaks before merging.

2025-01-18 00:55 UTC, kevinaboos approved these changes

2025-01-18 00:58 UTC, kevinaboos approved these changes

2025-01-18 00:58 UTC, merged