WIP the desktop ui for room details pane (room info, room members) #119
project-robius/robrix pull request #213
Opened 2024-10-25 07:38 UTC by tyreseluo

2024-10-29 08:29 UTC, tyreseluo commented
![QQ截图20241029162638](https://github.com/user-attachments/assets/c21a030c-5a35-4452-91f5-ed6843e60cbe)

2024-10-31 08:48 UTC, tyreseluo commented
https://github.com/user-attachments/assets/2c3e18a3-6c04-4191-ae3b-7745cf090183

2024-10-31 10:05 UTC, tyreseluo commented
https://github.com/user-attachments/assets/a66ddcda-4081-451a-8d15-95babcbdf69e

2024-10-31 19:20 UTC, kevinaboos requested changes
Thanks, great start! I've left a review at your request even though the PR is marked as a draft.

From a UI design perspective, I feel like this is a bit clunky because it uses a lot of vertical space, which is particularly egregious on small screens. However, we should reach out to an actual UI designer for better ideas & informed opinions, like Sebastian from Makepad. 
However, it's ok for now since it enables us to test the actual UX functionality & behavior.

2024-10-31 19:20 UTC, kevinaboos commented on resources/icon_leave_room.svg
let's choose a different icon. this does not look like a "leave room" icon to me, it barely even looks like an open door... it's too abstract.

2024-10-31 19:20 UTC, kevinaboos commented on resources/icon_members.svg
please place this and all icon files in the proper subdirectory within `resources/`.

2024-10-31 19:20 UTC, kevinaboos commented on src/home/room_screen.rs
> +            }
for these, don't you actually want to _toggle_ the room info/members pane, instead of unconditionally _showing_ it?

That is, if the room_info tab button is clicked when the room info tab is _already open_, the user would likely expect that pane to be closed.

2024-10-31 19:20 UTC, kevinaboos commented on src/home/room_screen.rs
> +
this isn't quite correct. We _only_ want to have the underlying view handle the event if it doesn't require visibility AND none of the panes are currently shown. You've changed it to handle the event unconditionally.

2024-10-31 19:20 UTC, kevinaboos commented on src/lib.rs
> +mod room;
please use a more descriptive name. `room` is widely used in the Matrix SDK itself and isn't a good name for this. 

`room_info_sliding_pane` would be my recommendation.

2024-10-31 19:20 UTC, kevinaboos commented on src/room/room_info_pane.rs
> +    }
i assume this is still a WIP?

2024-12-19 07:19 UTC, closed without merging