Search bar: Add changed,clicked functions and close icon, close event to search bar #123
project-robius/robrix pull request #214
Opened 2024-10-27 08:07 UTC by tyreseluo

2024-10-30 21:11 UTC, kevinaboos requested changes
I'm confused by a few things in this PR.

1. What is the purpose of this PR? there's no description, and the title is lengthy but not quite detailed enough. 
2. As a follow-up to the above, this doesn't seem to actually implement the search functionality. So it'd be pretty confusing for users to see a new search bar that they can interact with but doesn't actually do anything.... unless there is another PR that is designed as a pairing to this?
3. The search timer idea is unusual, to say the least. The action of searching should happen automatically upon typing (i.e., when the typed text changes), which you can determine by checking for actions on the actual `TextInput` widget.

2024-10-30 21:11 UTC, kevinaboos commented on src/shared/search_bar.rs
> +    ResetSearch,
Action enums like this require a `None` variant in order to work properly with Makepad's action system (primarily `as_widget_action()`), so you need to add a `None` variant and then you can derive `DefaultNone` instead of `Default` on the enum.

2024-10-30 21:11 UTC, kevinaboos commented on src/shared/search_bar.rs
> +    search_timer: Timer,
what is the purpose of a timer here?

2024-10-31 01:30 UTC, tyreseluo commented
That's my problem I didn't describe it clearly, I meant an enhancement to the search bar component. Add Action and clicked events and close icon.

2024-10-31 01:32 UTC, tyreseluo commented
For the room search issue https://github.com/project-robius/robrix/issues/123, I separated it and will be submitting a new PR.

2024-10-31 01:33 UTC, tyreseluo commented on src/shared/search_bar.rs
> +    ResetSearch,
ok

2024-10-31 02:06 UTC, tyreseluo commented on src/home/rooms_sidebar.rs
> +        }
Focused enhancement, not required here

2024-10-31 19:24 UTC, kevinaboos requested changes
ok nice, now I understand what the scope of this PR is. It looks good, just one small nit about unnecessary changes to the `rooms_sidebar.rs` file.

2024-10-31 19:24 UTC, kevinaboos commented on src/home/rooms_sidebar.rs
both of the changed lines in this file seem unnecessary; can they be removed so this file does not appear in the changelist?

2024-10-31 19:24 UTC, kevinaboos commented on src/shared/search_bar.rs
> +}
Since this is the main public API for actions emitted by the search bar, please add some good documentation to both the top-level enum and the first two variants.

2024-11-01 01:42 UTC, tyreseluo commented on src/shared/search_bar.rs
> +}
ok, i will do that, thanks!

2024-11-01 02:50 UTC, kevinaboos approved these changes

2024-11-01 02:50 UTC, merged