Room list search bar
project-robius/robrix pull request #232
Opened 2024-11-04 08:53 UTC by tyreseluo

Fixes: https://github.com/project-robius/robrix/issues/123

2024-11-07 05:42 UTC, kevinaboos requested changes
The code structure itself looks good. I'd recommend that you think deeply about what kind of filter criteria we would want to accept (I left some suggestions), and also what kind of sorting criteria the user might care about, for example, by recency, alphabetical by name, etc. Then you need to consider how you could jointly consider different filter criteria _and_ various sorting preferences.

2024-11-07 05:42 UTC, kevinaboos commented on src/home/rooms_sidebar.rs
> +                empty_message: "Search by room name"
There are multiple criteria we can search for, right? not only the room name?
```suggestion
                empty_message: "Search for rooms..."
```

2024-11-07 05:42 UTC, kevinaboos commented on src/home/rooms_sidebar.rs
> +pub enum RoomsSideBarFilter {
I think you're conflating filter kinds with room categories.... these are two separate things. 

The filter categories would be things like:
* search by room name
* search by room ID
* search by room member (user name and/or user ID)
* search by anything (any keywords match)
* etc

You _could_ also have additional filter kinds for  "is_direct" or "is_room" (not direct), but those wouldn't be expressible as enum variants because you'd only be able to select one. They would have to be bitflags/bitsets such that you could select multiple filter criteria at once. Or, alternatively, you could add a series of booleans to a "filter type" struct. The design is up to you, but try to think deeply about the possible valid combinations of filter kinds and search terms.

The buttons for

2024-11-07 05:45 UTC, kevinaboos commented on src/home/rooms_list.rs
> +            room_name.as_ref().map_or(false, |n| n.contains(&keywords))
this is okay for now as a rudimentary search, but in the future we'd want to fuzzy match the room name, room ID, room members, etc against one or more of the keywords (rather than just a straight-up "contains keywords" conditional)

2024-11-07 06:22 UTC, kevinaboos commented on src/home/rooms_sidebar.rs
> +pub enum RoomsSideBarFilter {
Other possible filter dimensions include whether a room is marked as a favorite, whether a user has left a room, joined a room, or is just invited to a room, etc.

The list of built-in filter functions are here; perhaps you could just re-use most of them. But note that we do _not_ want to use them with the `RoomListDynamicEntriesController` because that modifies the actual room_list_service's list of rooms, which I don't want to deal with.

https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_ui/room_list_service/filters/index.html#functions

2024-11-07 06:30 UTC, tyreseluo commented on src/home/rooms_sidebar.rs
> +pub enum RoomsSideBarFilter {
yep. I got it. So i will do that and then change this issue's label. Thanks

2024-11-25 21:03 UTC, kevinaboos commented
is this actually blocked on Makepad? if so, what feature of Makepad is missing?  I can't think of anything in Makepad that is preventing us from implementing a basic search bar.

2024-11-26 02:33 UTC, tyreseluo commented
oh, ok,i guess I'm lagging. i will do again.

2024-11-26 23:15 UTC, kevinaboos commented
no worries, I didn't mean to imply that you were lagging. I was just curious if we actually needed more features from Makepad or not.

2024-12-18 08:15 UTC, closed without merging