Display verification status as a badge atop the user profile icon #241
project-robius/robrix pull request #244
Opened 2024-11-08 04:09 UTC by Demolemon11

This pr is still not in your expectation. I just want to show you on my progress. : )

- You can see struct `SDock` & its `Widget` trait in this pr. Just let me know if you think it's not suitable.
- I shall learn how to put these svgs in proper position.

So this still is a draft. : )

2024-11-08 11:29 UTC, Demolemon11 commented
[Screencast from 2024-11-08 19-22-14.webm](https://github.com/user-attachments/assets/98200fcb-f3d5-41b5-9b44-822a655e765a)
As you can see, it's not perfect:
- What should be transparent is not transparent, instead, what should not be transparent is transparent. What should I do to correct it?
- How can I centre the svg? I have debuged this for a long time, but failed.

2024-11-11 22:39 UTC, kevinaboos requested changes
Nice job so far! Visually, the effect looks great, and that's almost exactly what I was hoping for. 

Responding to your questions:

> What should be transparent is not transparent, instead, what should not be transparent is transparent. What should I do to correct it?

Hmm, not exactly sure what you mean by this, because everything looks correct to me?

> How can I centre the svg? I have debuged this for a long time but no idea.

The verification badge icon looks to be properly positioned, as it should ideally be on the upper right corner of the user profile image. So it looks like you're doing things correctly already, not sure why you would want to center it.

---------------------

Now that I see the visual effect, I think we should probably switch to a different design for the icon. Instead of an outline of a shield that is transparent in the middle, we should switch to a shield icon that has a solid color fill (green/red/gray), with a solid-white inner checkmark / exclamation point / question mark, as that will be is easier for the user to read.


---------------------

While the visual design is good, the code itself needs some improvement. I have left inline comments about that. 
The main problem is that we should be using Makepad's Actions feature to inform the SDock widget about changes in Verification state. Actions are perfect for any scenario where you need to deliver a "message" to another widget. You definitely should not be using a shared `RwLock` for this purpose, as we do not want the main UI thread to ever have to acquire any locks.

2024-11-11 22:39 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +                    <Filler> {}
please fix indentation spacing here to match all other code

2024-11-11 22:39 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +    verification_state: Option<matrix_sdk::encryption::VerificationState>,
The `Option` wrapper is unnecessary here -- we always start out in the `Unknown` state. 

When applying this suggestion, also be sure to import `matrix_sdk::encryption::VerificationState`.

```suggestion
    #[rust(VerificationState::Unknown)] verification_state: VerificationState,
```

2024-11-11 22:39 UTC, kevinaboos commented on src/verification.rs
> +                Handle::current().spawn(request_verification_handler(client, request));
this is an incorrect merge conflict resolution -- you should have selected my changes that appear on the left (the `if let Some(request)` code, which is the newer code).

2024-11-11 22:39 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +        self.verification_state = Some(*VERIFICATION_STATE.read().unwrap());
think about what is happening here. On _every single event_, you are locking the `VERIFICATION_STATE` RwLock, acquiring its inner state, and then setting that value into `self.verification_state`. That is very very expensive. 

See my other comments about redesigning this to use Actions instead. Once you do that, you won't need a shared RwLock at all.

2024-11-11 22:39 UTC, kevinaboos commented on src/verification.rs
> +            *VERIFICATION_STATE.write().unwrap() = state;
Ok, here is where a major redesign needs to happen.

Instead of using a shared `RwLock` to "pass" the verification state from this background async task to the main UI thread, you should use _**actions**_ for this. 

The main idea is to use the `Cx::post_action()` function to send a custom action type to the SDock widget (or any widget that wishes to handle that). Here's how you can do so.

First, define a new action enum:
```rust
/// Add your docs here
#[derive(Clone, Debug, DefaultNone)]
pub enum VerificationStateAction {
    Update(VerificationState),
    None,
}
```

Then, here on this line of code, you will do this:
```rust
Cx::post_action(VerificationStateAction::Update(state);
```

Then, in the SDock widget code, add a handler for this action:
```rust
impl Widget for SDock {
    fn handle_event(&mut self, cx: &mut Cx, event: &Event, scope: &mut Scope) {
        self.view.handle_event(cx, event, scope);
        if let Event::Action(actions) = event {
            for action in actions {
                if let Some(VerificationStateAction::Update(state)) = action.downcast_ref() {
                    // Here, you should update the view state directly, which is much faster
                    // than re-doing it in draw_walk() every time.
                    match state {
                        VerificationState::Unknown => {
                            log!("Verification state is unknown");
                            self.view(id!(profile.text_view.verification_yes)).set_visible_and_redraw(cx, false);
                            self.view(id!(profile.text_view.verification_no)).set_visible_and_redraw(cx, false);
                            self.view(id!(profile.text_view.verification_unk)).set_visible_and_redraw(cx, true);
                        }
                        VerificationState::Verified => {
                            log!("Verification state is verified");
                            self.view(id!(profile.text_view.verification_yes)).set_visible_and_redraw(cx, true);
                            self.view(id!(profile.text_view.verification_no)).set_visible_and_redraw(cx, false);
                            self.view(id!(profile.text_view.verification_unk)).set_visible_and_redraw(cx, false);
                        }
                        VerificationState::Unverified => {
                            log!("Verification state is unverified");
                            self.view(id!(profile.text_view.verification_yes)).set_visible_and_redraw(cx, false);
                            self.view(id!(profile.text_view.verification_no)).set_visible_and_redraw(cx, true);
                            self.view(id!(profile.text_view.verification_unk)).set_visible_and_redraw(cx, false);
                        }
                    };

                    ...
```

When you implement things in this way, we achieve multiple benefits!
1. there is no need for any state to be shared between the main UI thread and the background task, which is generally a bad design choice.
2. the main UI thread doesn't need to constantly re-acquire the shared RwLock and repeatedly set the value of `self.verification_state`, which is massively inefficient.
3. We re-use the existing infrastructure that is intended for this exact scenario:  passing information to a widget.
4. We avoid expensive logic in the `draw_walk()` fn --- instead of setting the verification badge views on _every single_ call to `draw_walk()`, we only do it when the state actually _changes_, which is very infrequent (and therefore much more efficient!)

2024-11-12 02:00 UTC, Demolemon11 commented
> Now that I see the visual effect, I think we should probably switch to a different design for the icon. Instead of an outline of a shield that is transparent in the middle, we should switch to a shield icon that has a solid color fill (green/red/gray), with a solid-white inner checkmark / exclamation point / question mark, as that will be is easier for the user to read.

This is equal to `What should be transparent is not transparent, instead, what should not be transparent is transparent.`, my english is not good.

2024-11-12 04:20 UTC, Demolemon11 commented
**No idea for reason that it became this:**

[Screencast from 2024-11-12 12-15-55.webm](https://github.com/user-attachments/assets/2dae966c-5ba5-49e0-af7c-7651434d5d9d)


Just Discarded `SDock` and enable `<Profile>` as the struct.

I checked my code several times and don't think there's anything wrong in logic.

2024-11-12 11:45 UTC, Demolemon11 commented
It seems that there is a bug:
https://github.com/project-robius/robrix/blob/f4ffba56d97aa887d74f9ffd426aab007580cc19/src/home/spaces_dock.rs#L192-L193
The `verification_state` will be changed to its default value `VerificationState::Unverified` once window was resized.
I also tried to set `#[rust(VerificationState::Unverified)] ` to `#[rust(VerificationState::Unknown)] `, just in the expectation, the icon become the `?` with gray.


Here are videos:
[Screencast from 2024-11-12 19-09-02.webm](https://github.com/user-attachments/assets/07c705fe-5ead-4a9d-a1b9-634eac9e3e32)

I will send the log video to wechat cahnnel because it is a little large.

2024-11-12 21:15 UTC, kevinaboos commented
> > Now that I see the visual effect, I think we should probably switch to a different design for the icon. Instead of an outline of a shield that is transparent in the middle, we should switch to a shield icon that has a solid color fill (green/red/gray), with a solid-white inner checkmark / exclamation point / question mark, as that will be is easier for the user to read.
> 
> This is equal to `What should be transparent is not transparent, instead, what should not be transparent is transparent.`, my english is not good.

oh ok, great, then we agree! Sorry for the misunderstanding.

2024-11-12 21:18 UTC, kevinaboos commented
> It seems that there is a bug:
> 
> https://github.com/project-robius/robrix/blob/f4ffba56d97aa887d74f9ffd426aab007580cc19/src/home/spaces_dock.rs#L192-L193
> 
> 
> The `verification_state` will be changed to its default value `VerificationState::Unverified` once app window was resized to mobile layout.
> I also tried to set `#[rust(VerificationState::Unverified)] ` to `#[rust(VerificationState::Unknown)] `, also in the expectation, the icon become the `?` with gray.
> Here is the screenshot: [Screencast from 2024-11-12 19-09-02.webm](https://github.com/user-attachments/assets/07c705fe-5ead-4a9d-a1b9-634eac9e3e32)
> 
> I will send the log video to wechat cahnnel because it is a little large.

Well yes, this isn't a bug, it's just a missing part of your current implementation in this PR so far. This behavior is expected, since you haven't dealt with that case yet. 

To fix this, you need to make sure the state of the verification badge is preserved when transitioning between the Desktop and Mobile views. If you're unsure how this works, I'd recommend reaching out to Julian, who wrote that code initially (or perhaps another intern can help you out).

2024-11-13 00:17 UTC, Demolemon11 commented
Thanks very much!

2024-11-13 11:56 UTC, alanpoon commented on src/home/spaces_dock.rs
> +        }
You should not set visibility here in draw_walk

2024-11-21 02:17 UTC, alanpoon commented on src/home/spaces_dock.rs
> +        }
Maybe I am not understanding the need to store the verification_state field in Profile struct.

2024-11-21 03:38 UTC, Demolemon11 commented on src/home/spaces_dock.rs
> +        }
You are right, that is unnecessary

2024-11-21 08:07 UTC, alanpoon commented on src/home/spaces_dock.rs
> +
Sorry, push this back into the draw_walk function

2024-11-21 08:07 UTC, alanpoon commented on src/home/spaces_dock.rs
> +        self.redraw(cx);
remove this line

2024-11-21 08:10 UTC, alanpoon commented on src/home/spaces_dock.rs
> +
Put back verification_status field into the Profile. Compare app_state.verification_state and the Profile inside the draw_walk function, if it is the same, return the function early.

2024-11-22 05:33 UTC, alanpoon commented on src/app.rs
> +}
Use #[derive(Debug)] instead of the paragraph

2024-11-22 05:43 UTC, alanpoon commented
Looks ok now. You can just do some code cleanup. Revert back all those non-related changed.

2024-11-22 05:49 UTC, Demolemon11 commented
Thanks very much!

2024-11-22 07:25 UTC, ZhangHanDong commented
From the code, it seems that the feature of displaying corresponding text on mouse hover has not been implemented yet ?

```
Then, when the user hovers over the badge/profile picture, we should display a tooltip that states the verification status, which is either "Verification unknown", "Unverified", or "Verified".
```

2024-11-22 09:07 UTC, ZhangHanDong commented on src/verification.rs
> +            Cx::post_action(VerificationStateAction::Update(state));
typo: verficiation -> verification

2024-11-22 09:20 UTC, ZhangHanDong commented on src/verification.rs
>              //       such that we can display the verification state as an icon badge
Should this todo comment be removed?

2024-11-22 09:22 UTC, ZhangHanDong commented on src/verification.rs
> +            Cx::post_action(VerificationStateAction::Update(state));
If the match validation is successful, can we exit the while loop?
```rust
if matches!(state, VerificationState::Verified) {
    break;
}
```

2024-11-25 11:39 UTC, Demolemon11 commented on src/verification.rs
> +            Cx::post_action(VerificationStateAction::Update(state));
In my poor opinion, maybe we should not exit though it is successful. 
One client can manage the other client's verification state at any time as long as it's running.

2024-11-25 20:54 UTC, kevinaboos requested changes

2024-11-25 20:54 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +            width: Fit, height: Fit
fix indentation for this and all of the following lines.

2024-11-25 20:54 UTC, kevinaboos commented on src/app.rs
> +    pub verification_state: VerificationState,
verification state does not need to be a part of the top-level app state. Instead, it should be moved directly into the widget that this state will actually be used by, which in this case is the Profile widget.

2024-11-25 20:54 UTC, kevinaboos commented on src/app.rs
> +    pub verification_state: VerificationState,
ah, I see that it is already there in the Profile widget. So why does it need to be duplicated here?

2024-11-25 20:54 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +            self.redraw(cx);
you shouldn't redraw in a draw_walk(), that will break the draw flow (as far as I understand things).

2024-11-25 20:54 UTC, kevinaboos commented on src/app.rs
> +            }
this should be moved into the `Profile`'s event handler. No reason do this at the very top level of the app.

2024-11-25 20:54 UTC, kevinaboos commented on src/app.rs
> +}
unnecessary, remove.

2024-11-25 20:54 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +            self.redraw(cx);
Instead of doing this logic in the draw routine, which runs _every single time_ that this widget needs to be drawn, you only need to perform this logic when the verification state _changes_, which would be in the event/action handler of this widget (once you move that stuff here, as recommended by my previous comments). 

So basically, in the `Profile` widget's action handler, you will handle the `VerificationStateUpdate` action and then update the view content there, like so (this code is not exact, just a general idea):
```rust
impl MatchEvent for Profile {
    fn handle_action(&mut self, _cx: &mut Cx, action:&Action) {
        if let Some(VerificationStateAction::Update(state)) = action.downcast_ref() {
            self.verification_state = *state; // you're already doing this, so that's good
            
            // Update visibility states
            let (yes_visible, no_visible, unk_visible) = match self.verification_state {
                VerificationState::Unknown => (false, false, true),
                VerificationState::Unverified => (false, true, false),
                VerificationState::Verified => (true, false, false),
            };
            
            self.view(id!(icon_yes)).set_visible(yes_visible);
            self.view(id!(icon_no)).set_visible(no_visible);
            self.view(id!(icon_unk)).set_visible(unk_visible);
            
            self.redraw(cx);
        }
    }
}
```

2024-11-25 20:54 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +    fn handle_action(&mut self, _cx: &mut Cx, action:&Action) {
This function isn't getting called. That's because in the `Profile` widget's `handle_event()` function, you have to explicitly call `match_event()`.

2024-11-25 20:54 UTC, kevinaboos commented on src/verification.rs
> +            Cx::post_action(VerificationStateAction::Update(state));
Yes, please do that. You should definitely break out of the loop once we have reached the Verified state. I believe we discussed that already in one of my previous review rounds.

2024-11-25 20:54 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +            if self.view(id!(verification_icon)).area().rect(cx).contains(e.abs) {
There is an existing `tooltip` widget in Makepad that you can use for this purpose. You don't need to create and use your own view with a label.

https://github.com/makepad/makepad/blob/rik/widgets/src/tooltip.rs

2024-11-25 20:54 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +                    VerificationState::Verified => {"Verified"}
This is a good start, but it doesn't really provide much more information to the user than the bare icon does. Let's add some more detail.

```suggestion
                    VerificationState::Unknown => {"Verification state is unknown."},
                    VerificationState::Unverified => {"This device is unverified. To view your encrypted message history, please verify it from another client."},
                    VerificationState::Verified => {"This device is fully verified."}
```

2024-11-26 02:22 UTC, Demolemon11 commented on src/app.rs
> +    pub verification_state: VerificationState,
Done.

2024-12-06 06:01 UTC, Demolemon11 commented
[Screencast from 2024-12-06 14-00-34.webm](https://github.com/user-attachments/assets/6356d3ca-a548-4324-9c18-705258340064)

2024-12-16 21:03 UTC, kevinaboos commented
> Screencast.from.2024-12-06.14-00-34.webm

Is this the latest behavior? You just posted a video with no comment, so I'm not sure what the point is.

If you're trying to illustrate that changing the adaptive view layout causes the verification state to be reset, then yes, you're correct. That just means you haven't properly handled the transfer of that widget state from the desktop UI instance of that widget to the mobile UI instance of that widget, or vice versa.

Please fix that, and then we can merge this PR in. 👍

2024-12-17 02:37 UTC, aaravlu commented
> Is this the latest behavior? You just posted a video with no comment, so I'm not sure what the point is.
> 
> If you're trying to illustrate that changing the adaptive view layout causes the verification state to be reset, then yes, you're correct. That just means you haven't properly handled the transfer of that widget state from the desktop UI instance of that widget to the mobile UI instance of that widget, or vice versa.

Thanks for reviewing. 
The screenshot above wants to show the tooltip when user cursor is hovering the icon.
Verification state being resetted is a bug indeed, but is seems that the bug is not belong to this pr.
Lmt if any style of the tooltip is not suitable.

2024-12-17 02:52 UTC, kevinaboos commented
> The screenshot above wants to show the tooltip when user cursor is hovering the icon.
> Lmt if any style of the tooltip is not suitable.

Ok, if that's the point, then yes, I'd say to not use a transparent tooltip (that's very unusual) and just keep it simple and standard with a solid background. Also, the tooltip should be shown to the right of the verification badge icon, vertically aligned with the badge icon itself.

> Verification state being resetted is a bug indeed, but the bug is not belong to this pr, is seems that some people is fixing it in makepad. 

While it is technically possible for AdaptiveView to deal with this, I don't know if it ever will do that. Instead of relying on Makepad, you should explicitly obtain the current verification state when the widget is first loaded. You can do this by implementing the `after_new_from_doc` function from the `LiveHook` trait, which gets called by Makepad right after a Widget has been created.

You can get the verification state by doing:
```rust
    let current_verification_state = client.encryption().verification_state.get();
```

2024-12-17 06:07 UTC, aaravlu commented
[Screencast from 2024-12-17 13-44-40.webm](https://github.com/user-attachments/assets/ecbc5286-04cb-4c0d-85d2-3ac31dfbe0b8)
As you can see, for the mobile layout, I found the the widget `Profile`(`U`) is not a linear change at the bottom spacedock when resizing the window while keeping app in mobile layout.
I try my best to simulate a relative position to "follow the the widget `Profile`(`U`)".
Lmk if there are any other better way to make the tooltip follow widget `Profile`(`U`).

2024-12-17 22:32 UTC, kevinaboos commented
> [Screencast from 2024-12-17 13-44-40.webm](https://github.com/user-attachments/assets/ecbc5286-04cb-4c0d-85d2-3ac31dfbe0b8) As you can see, for the mobile layout, I found the the widget `Profile`(`U`) is not a linear change at the bottom spacedock when resizing the window while keeping app in mobile layout. I try my best to simulate a relative position to "follow the the widget `Profile`(`U`)". Lmk if there are any other better way to make the tooltip follow widget `Profile`(`U`).

I'm not sure how to fix that, but it looks quite good for now!

2024-12-17 23:05 UTC, kevinaboos requested changes
Things are looking quite good! Just left a few small comments.

2024-12-17 23:05 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +    unk: String,
the whole struct can just be replaced with 3 static strs...

2024-12-17 23:05 UTC, kevinaboos commented on src/home/spaces_dock.rs
> +                    sdf.circle(c.x, c.x, r.x);
these comments don't really make much sense, and they don't seem to clarify anything (for me, at least). Either improve them or simply remove them.

2024-12-17 23:05 UTC, kevinaboos commented on src/shared/verification.rs
> +            align: { x: 0.43, y: 1. }
can you explain this `x` alignment here? it's pretty weird to see an alignment value other than 0, 0.5, or 1.0.

2024-12-18 01:50 UTC, aaravlu commented on src/shared/verification.rs
> +            align: { x: 0.43, y: 1. }
Yeah, I will leave some comments.

2024-12-18 01:51 UTC, aaravlu commented on src/home/spaces_dock.rs
> +                    sdf.circle(c.x, c.x, r.x);
Ok, These comments willl be removed.

2024-12-18 02:02 UTC, aaravlu commented on src/shared/verification.rs
> +    VerificationNoticeDesktop = <TooltipBase> {
Yeah! 
As you can see, I also changed the internal attributes like `padding` & `align` in `<VerificationNoticeMobile>`. Simply call `show_with_options()` without changing attributes to set absolutely position would not work current way for mobile layout.

Thus, I am thinking how about using an `<AdaptiveView>` , then putting `<VerificationNoticeDesktop>` & `<VerificationNoticeMobile>` in it?

2024-12-18 02:23 UTC, kevinaboos commented on src/shared/verification.rs
> +    VerificationNoticeDesktop = <TooltipBase> {
Nah, no need for that here. An AdaptiveView isn't what we want here, since we don't want the content to differ based on view size. The need to do that right now is just based on the shortcomings of the current makepad tooltip support; in the future, the tooltip widget should handle all of that automatically.

2024-12-18 02:24 UTC, kevinaboos commented on src/shared/verification.rs
> +    VerificationNoticeDesktop = <TooltipBase> {
To clarify, I was suggesting that you just create a single `VerificationNotice` view, and then set the properties of it (padding, align, etc) accordingly in the `Profile::handle_event()` function. That's faster and easier to understand than creating two separate views and hiding/showing one of them.

2024-12-18 02:30 UTC, aaravlu commented on src/shared/verification.rs
> +    VerificationNoticeDesktop = <TooltipBase> {
NP!

2024-12-18 04:58 UTC, aaravlu commented on src/shared/verification.rs
> +    VerificationNoticeDesktop = <TooltipBase> {
All fixed so far.

2024-12-18 08:23 UTC, kevinaboos approved these changes
Looks great now, thanks very much!

By the way, in the future it'd be nice if you could provide more detailed commit messages than just "Fix", as it makes it easier for me to understand what changed in each commit. See some of my commit messages if you need examples/inspiration. Thanks!

2024-12-18 08:24 UTC, merged