Don't show message text input bar if the user cannot send messages in a room #231
project-robius/robrix pull request #253
Opened 2024-11-13 02:19 UTC by Demolemon11

Probably everything is supposed to follow you. If you think red as bg is not suitable, tell me :)
[Screencast from 2024-11-13 10-15-14.webm](https://github.com/user-attachments/assets/1e60437e-c100-4cf1-8cb9-fd84d1e7ccc5)

2024-11-13 02:29 UTC, tyreseluo commented on src/home/room_screen.rs
> +                //         width: Fill, height: Fit
The commit has extra comments

2024-11-13 02:31 UTC, Demolemon11 commented on src/home/room_screen.rs
> +                //         width: Fill, height: Fit
> The commit has extra comments

Done.

2024-11-14 19:40 UTC, kevinaboos requested changes

2024-11-15 02:38 UTC, Demolemon11 commented
[Screencast from 2024-11-15 10-34-45.webm](https://github.com/user-attachments/assets/8af2d262-f634-4cdc-b11f-71dab01320e6)

I will never give up, please review:)

2024-11-15 09:16 UTC, alanpoon commented
https://github.com/user-attachments/assets/cc8531eb-d67e-4773-a288-f8c3fa40a4c6

Here are some issues I found:
- Currently this banner "you don't have permission" is applying to all rooms when the user is muted in a room. 
- The error message not handled when the user sends out message when he is muted in a room after he joins the room

2024-11-15 12:10 UTC, alanpoon commented
This is a wrong implementation of user ban. 

1. When loading the room, you should be using checking room member's power level.
2. User Ban is timeline event: "m.room.power_levels" https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/ruma/events/enum.AnyStateEventContent.html#variant.RoomPowerLevels

My advice is to always check the behavior of the [element.io ](https://app.element.io/) for the correct api to use. Use two accounts,  both in the same room. One mutes the other, you should already see the message text input bar hidden for the muted user. Hence there is no "can_send" checks in between.

2024-11-18 11:20 UTC, Demolemon11 commented
> /
> 
> / 2. User Ban is timeline event: "m.room.power_levels" https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/ruma/events/enum.AnyStateEventContent.html#variant.RoomPowerLevels
> 
> My advice is to always check the behavior of the [element.io ](https://app.element.io/) for the correct api to use. Use two accounts, both in the same room. One mutes the other, you should already see the message text input bar hidden for the muted user. Hence there is no "can_user_send_message" checks in between.

"Mut" can now be hot updated now.

2024-11-18 13:33 UTC, ZhangHanDong commented
@CodiumAI-Agent /review

2024-11-18 14:18 UTC, Demolemon11 commented on src/home/room_screen.rs
> +            self.check_self_has_send_permission();
Putting it in `show_timeline()` cannot work properly.
He cannot receive mut update in time in the room if user he self was mutted & unmutted again & again frequently.


So I put it here, just tell me if not suitable: )
https://github.com/project-robius/robrix/blob/b700faad885a73329655de5a70601a2c998d89db/src/home/room_screen.rs#L1438

2024-11-18 14:52 UTC, CodiumAI-Agent commented
**[Persistent review](https://github.com/project-robius/robrix/pull/253#issuecomment-2483058827)** updated to latest commit https://github.com/project-robius/robrix/commit/b700faad885a73329655de5a70601a2c998d89db

2024-11-18 15:03 UTC, ZhangHanDong commented
@Demolemon11 

**Core requirements:**

- ✅ Correctly implemented the visibility logic for the message input control
- ✅ Implemented permission checks and controlled the UI based on the results 
- ✅ Implemented clear prompts for when messages cannot be sent

**Implementation details:**

- ✅ Used Room:can_user_send_message() to check permissions 
- ✅ Displays a prompt instead of the input box when permissions are insufficient

**Suggestions for improvement:**

- ❌ Lacks a subscription mechanism for permission changes 
- ❌ Lacks unsubscribe logic when leaving the room 
- ❌ Only checks permissions once when opening the room, without periodic checks

**Code improvement suggestions:**

- Using i64 type for permission values is not intuitive. Please refactor the permission status to a clearer enum type.
- Missing documentation comments for permission status, please add them.
- Permission check logic is scattered in multiple places, please centralize the management of permission-related logic.
- Lacks an event listening mechanism for permission changes.
- Please add complete error handling.
- Need to set a reasonable time interval for permission checks.
- Need to optimize the timing of state updates.

2024-11-19 18:30 UTC, kevinaboos commented on src/home/room_screen.rs
> +            self.check_self_has_send_permission();
well yes, putting it in `show_timeline()` is the _first_ step in getting things to work; that alone isn't sufficient, but it is necessary.

As other reviewers have mentioned, you would _also_ need to subscribe for updates to a user's power levels (in a background task) and then send updates from that background task to the RoomScreen to inform it of any changes to a user's power level.

Doing it that way is the efficient way, not querying the user permission on every single event. Considering that user power level changes are quite rare, you're redoing a lot of work that will be wasted 99.999% of the time because power levels wouldn't have changed.

2024-11-19 23:53 UTC, kevinaboos commented
> **Suggestions for improvement:**
> 
> * ❌ Lacks a subscription mechanism for permission changes

this can be done in a future PR, too, if you want to keep this one simple/manageable. Multiple smaller PRs are preferred over one big PR.

> * ❌ Lacks unsubscribe logic when leaving the room

Same comment as above.

> * ❌ Only checks permissions once when opening the room, without periodic checks

I think this is the same thing as the first point. As I mentioned in one of my earlier comments, a subscription mechanism that asynchronously `await`s updates to a user's power levels is much better than periodically checking it from the main UI thread, since updates to user power levels are very infrequent.

2024-11-20 15:28 UTC, alanpoon commented on src/sliding_sync.rs
> +                submit_async_request(MatrixRequest::CheckUserSendPermission { room_id: room_id.clone() });
You should not be throwing away ```user_power_level_event``` information from the server and make another async call to the backend server.

Here is println for ```user_power_level_event```.
Mute
{ content: RoomPowerLevelsEventContent { ban: 50, events: {"m.room.avatar": 50, "m.room.canonical_alias": 50, "m.room.encryption": 100, "m.room.history_visibility": 100, "m.room.name": 50, "m.room.power_levels": 100, "m.room.server_acl": 100, "m.room.tombstone": 100}, events_default: 0, invite: 50, kick: 50, redact: 50, state_default: 50, users: {"@ruitoalpha:matrix.org": -1, "@ruitobeta:matrix.org": 100}, users_default: 0, notifications: NotificationPowerLevels { room: 50 } }, prev_content: Some(RoomPowerLevelsEventContent { ban: 50, events: {"m.room.avatar": 50, "m.room.canonical_alias": 50, "m.room.encryption": 100, "m.room.history_visibility": 100, "m.room.name": 50, "m.room.power_levels": 100, "m.room.server_acl": 100, "m.room.tombstone": 100}, events_default: 0, invite: 50, kick: 50, redact: 50, state_default: 50, users: {"@ruitoalpha:matrix.org": 0, "@ruitobeta:matrix.org": 100}, users_default: 0, notifications: NotificationPowerLevels { room: 50 } }) 

Unmute
{ content: RoomPowerLevelsEventContent { ban: 50, events: {"m.room.avatar": 50, "m.room.canonical_alias": 50, "m.room.encryption": 100, "m.room.history_visibility": 100, "m.room.name": 50, "m.room.power_levels": 100, "m.room.server_acl": 100, "m.room.tombstone": 100}, events_default: 0, invite: 50, kick: 50, redact: 50, state_default: 50, users: {"@ruitoalpha:matrix.org": 0, "@ruitobeta:matrix.org": 100}, users_default: 0, notifications: NotificationPowerLevels { room: 50 } }, prev_content: Some(RoomPowerLevelsEventContent { ban: 50, events: {"m.room.avatar": 50, "m.room.canonical_alias": 50, "m.room.encryption": 100, "m.room.history_visibility": 100, "m.room.name": 50, "m.room.power_levels": 100, "m.room.server_acl": 100, "m.room.tombstone": 100}, events_default: 0, invite: 50, kick: 50, redact: 50, state_default: 50, users: {"@ruitoalpha:matrix.org": -1, "@ruitobeta:matrix.org": 100}, users_default: 0, notifications: NotificationPowerLevels { room: 50 } }) }

So when the user's power level is -1, he is muted.

2024-11-21 08:34 UTC, alanpoon commented
<img width="692" alt="another_room" src="https://github.com/user-attachments/assets/97940384-a0fb-4196-9939-7cd68651bcb6">
<img width="644" alt="buggy" src="https://github.com/user-attachments/assets/3100f60e-531a-436f-86ee-c4e2ce751d2e">

The Permission banner based subscription of the power level change works. 
1. For the Power change message, add "from Default to Custom (-1)" Following Element.io
2. The Permission banner is buggy. It went into another room.

2024-11-26 02:06 UTC, ZhangHanDong commented on src/home/room_screen.rs
> +                }
DRY.

```rust
let (bottom_input, no_permisson) =  if can_post {   (true, false) } else {  (false, true) };

bottom_input.set_visible(bottom_input);
no_send_permisson_notice.set_visible(no_permisson);

```

2024-11-26 02:09 UTC, ZhangHanDong commented on src/home/room_screen.rs
> +                        text: "You don't have permission to post to this room"
This kind of text should be able to extract a constant for easy reuse, or for internationalization.

2024-11-26 02:11 UTC, ZhangHanDong commented on src/home/room_screen.rs
> +                        color: #EFEFEF
Hardcoded colors like this should also be placed as constants, and comments should be added to indicate what color it is.

2024-11-26 02:11 UTC, ZhangHanDong commented on src/home/room_screen.rs
> +                            color: #111111
Ditto

2024-11-26 02:13 UTC, ZhangHanDong commented on src/sliding_sync.rs
> +    let mut can_user_post_message = true;
Returning true by default may lead to permission errors.

2024-11-26 02:13 UTC, ZhangHanDong commented on src/sliding_sync.rs
> +        },
Too many nested if statements should be refactored.

2024-11-26 02:14 UTC, ZhangHanDong commented on src/sliding_sync.rs
> +        _ => { }
Error cases are not handled.At least the error should be loged.

```rust
error!( ... )
```

2024-11-26 02:17 UTC, ZhangHanDong commented on src/sliding_sync.rs
> +        },
Code just only reference.

```rust

match event_content {
        FullStateEventContent::Original { content, .. } => {
            let client = CLIENT.get().ok_or(Error::NoClient)?;
            let user_id = client.user_id().ok_or(Error::NoUserId)?;
            let power = content.users.get(user_id).copied().unwrap_or(0);
            Ok(power >= 0)
        },
        _ => Ok(false) 
    }
```

2024-11-26 02:19 UTC, ZhangHanDong commented on src/home/room_screen.rs
> +                bottom_input = <View> {
Is using message_input better than bottom_input? Naming should convey semantic meaning.

2024-11-26 02:25 UTC, ZhangHanDong commented on src/home/room_screen.rs
> +    PostPermission(bool)
Here, it would be better to consider using a state `enum` instead of `bool`. This makes it easier to expand permission states later.

The following code is for reference only.

```rust
#[derive(Debug, Clone)]
enum PostPermissionState {
    Loading,
    Allowed,
    Denied { reason: String },
    Error { message: String },
}
```

2024-11-26 02:39 UTC, Demolemon11 commented on src/home/room_screen.rs
> +                bottom_input = <View> {
No, you can also send location in the future,  so I don't think `message_input` is suitable.

2024-11-26 02:45 UTC, Demolemon11 commented on src/sliding_sync.rs
> +    let mut can_user_post_message = true;
How do you like returning an enum?

2024-11-26 02:46 UTC, Demolemon11 commented on src/sliding_sync.rs
> +    let mut can_user_post_message = true;
There are 3 state of send permisson: -1 ,0, 100

2024-11-26 02:47 UTC, Demolemon11 commented on src/home/room_screen.rs
> +    PostPermission(bool)
Maybe -1, 0, 100 can map to this enum

2024-11-26 03:26 UTC, ZhangHanDong commented on src/home/room_screen.rs
> +    PostPermission(bool)
Why do you think of using numbers instead of enum? Why do you think Rust introduced enum?

2024-11-26 09:31 UTC, Demolemon11 commented on src/sliding_sync.rs
> +        _ => { }
I used incorrect error type, it will be fixed later

2024-11-27 01:45 UTC, Demolemon11 commented on src/home/room_screen.rs
> +                            color: #111111
Sorry, what do you mean, I'm not sure?

2024-11-28 05:50 UTC, ZhangHanDong commented on src/home/room_screen.rs
> +    NO_POST_PERMISSIOM_NOTICE = "You don't have permission to post to this room."
`PERMISSIOM` -> `PERMISSION`

2024-11-28 10:48 UTC, Demolemon11 commented on src/home/room_screen.rs
> +    NO_POST_PERMISSIOM_NOTICE = "You don't have permission to post to this room."
Ok, Sorry for my careless while thanks to your review!

2024-11-29 02:56 UTC, alanpoon commented on src/sliding_sync.rs
> +use anyhow::{bail, Result};
revert unneccessary changes

2024-11-29 04:07 UTC, Demolemon11 commented on src/sliding_sync.rs
> +use anyhow::{bail, Result};
It seems that my editor auto format it.

2024-12-16 21:17 UTC, kevinaboos requested changes
your name choices for functions and variables are quite inconsistent. You have all of the following:
* CheckUserPostPermission
* check_user_post_permission
* CanUserPost
* can_user_post
* no_send_permission_notice
* NO_POST_PERMISSION_NOTICE
* "user send permission"

There are too many different names here for what is all the same thing. In this case, let's follow what the Matrix SDK does. Specifically, they use the phrase "can user send message", so let's use variants of that phrase everywhere else, instead of all the different names/phrases that I listed above from your current code.

2024-12-16 21:17 UTC, kevinaboos commented on src/home/room_screen.rs
> +        let no_send_permission_notice = self.view(id!(no_send_permission_notice));
these are very rarely used, so you should only query them in the specific code block where they're used, i.e., in the `TimelineUpdate::CanUserPost` block.

2024-12-16 21:17 UTC, kevinaboos commented on src/home/room_screen.rs
> +                    no_send_permission_notice.set_visible(no_send_permission_notice_visible)
don't overcomplicate things.
```suggestion
                    bottom_input.set_visible(can_user_post);
                    no_send_permission_notice.set_visible(!can_user_post)
```

2024-12-16 21:17 UTC, kevinaboos commented on src/home/room_screen.rs
> +        let no_send_permission_notice = self.view(id!(no_send_permission_notice));
(you may need to change the code to `self.view.view(...)` in order for the borrow checker to work properly)

2024-12-16 21:17 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    let can_user_post = room.can_user_send_message(user_id, matrix_sdk::ruma::events::MessageLikeEventType::Message).await.unwrap_or(true);
Why would you assume `true` in `unwrap_or(true)`? Seems like the default case should be false, right?

2024-12-17 02:49 UTC, aaravlu commented on src/sliding_sync.rs
> +                    let can_user_post = room.can_user_send_message(user_id, matrix_sdk::ruma::events::MessageLikeEventType::Message).await.unwrap_or(true);
You are right.

2024-12-17 02:54 UTC, aaravlu commented on src/home/room_screen.rs
> +        let no_send_permission_notice = self.view(id!(no_send_permission_notice));
Yeah!

2024-12-17 23:33 UTC, kevinaboos requested changes
thanks for the naming fixes, things are much better now. Just a few more minor comments.

2024-12-17 23:33 UTC, kevinaboos commented on src/sliding_sync.rs
> +    /// Sends user permission's checking once user entered room.
This comment isn't quite what we want to write here. You should write what this type of request actually does, not how you use it in only one part of the code.
```suggestion
    /// Sends a request checking if the currently logged-in user can send a message to the given room.
    ///
    /// The response is delivered back to the main UI thread via a `TimelineUpdate::CanUserSendMessage`.
```

2024-12-17 23:33 UTC, kevinaboos commented on src/home/room_screen.rs
> +            submit_async_request(MatrixRequest::CheckCanUserSendMessage { room_id })
no need to make this a separate function. Just move this one line to Line 1873 above.

2024-12-17 23:33 UTC, kevinaboos commented on src/sliding_sync.rs
> +                submit_async_request(MatrixRequest::CheckCanUserSendMessage { room_id: id })
```suggestion
                submit_async_request(MatrixRequest::CheckCanUserSendMessage { room_id: room_id.clone() })
```

2024-12-17 23:33 UTC, kevinaboos commented on src/sliding_sync.rs
> +                let Some(user_id) = client.user_id() else { continue };
I recently added a new function to more efficiently get the current user ID:
```suggestion
                let Some(user_id) = current_user_id() else { continue };
```

2024-12-17 23:33 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    let can_user_send_message = room.can_user_send_message(user_id, matrix_sdk::ruma::events::MessageLikeEventType::Message).await.unwrap_or(false);
improve formatting here to make it more readable
```suggestion
                    let can_user_send_message = timeline.room().can_user_send_message(
                        user_id,
                        matrix_sdk::ruma::events::MessageLikeEventType::Message,
                    )
                    .await
                    .unwrap_or(false);
```

2024-12-18 08:18 UTC, kevinaboos requested changes
You missed a few things from my last review; make sure you're reading each comment in detail, and using GitHub's commit/batch suggestion feature whenever you agree with my suggested code change.

Also, can you post a video proving that your code here actually does catch a changed permission? That is, I'd like to see a screen recording in which you:
* in Robrix with user account A, open a room that is owned/admin'd by user account B.
* in a different client with user account B, change the permissions of user account A for that room to be either "can post" or "cannot post"
* show that Robrix with user A has changed the view of the input bar on the bottom
* in the different client, change user A's permissions again back to what they originally were
* show that Robrix has changed its view of that room back to the original.

2024-12-18 08:18 UTC, kevinaboos commented on src/home/room_screen.rs
> +            submit_async_request(MatrixRequest::CheckCanUserSendMessage { room_id })
look at the existing lines of code directly beneath this -- they're already getting the room_id. That's why I explicitly mentioned that you should put the `submit_async_request(...)` line after that, and that you _only_ need that line  --- not the if conditional.

2024-12-18 08:18 UTC, kevinaboos commented on src/home/room_screen.rs
> +                    //Set the visibility of the corresponding component for both cases.
code comments shouldn't just simply restate what the code is doing. They should explain why something is happening or what is happening in very complex circumstances where the behavior of the code isn't immediately obvious.

Here, you can just remove this comment because it's very obvious what the next two lines are doing.

2024-12-18 08:18 UTC, kevinaboos commented on src/home/room_screen.rs
> +    CanUserSendMessage (bool)
missing documentation.

2024-12-18 08:18 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    let can_user_send_message = room.can_user_send_message(
you can combine these two lines. My previous suggestion explicitly did that, not sure why you didn't accept it as-is.

2024-12-19 02:56 UTC, aaravlu commented
[Screencast from 2024-12-19 10-52-25.webm](https://github.com/user-attachments/assets/1301a99b-6e89-4968-9b44-09b5e0db50c6)
Thanks for review.

It seems there is a bug: `input_bar` reshow after resizing to mobile layout.
I guess the reason is lack of permission inspection while fixing it.

2024-12-19 05:06 UTC, kevinaboos commented
> result: [Screencast from 2024-12-19 10-45-35.webm](https://github.com/user-attachments/assets/a0705afa-ab96-4f77-b61a-9dea99650233)

Very nice, looks great! 

> 
> bug: [Screencast from 2024-12-19 10-52-25.webm](https://github.com/user-attachments/assets/1301a99b-6e89-4968-9b44-09b5e0db50c6) Thanks for review.
> 
> It seems there is a bug: `input_bar` reshow after resizing to mobile layout. I guess the reason is lack of permission inspection. Should I fix it in this pr?

Yeah that's the same issue as the issue you had with the verification badge not persisting across mobile <--> desktop UI changes. The state of the widget gets reset. 

You can fix it in a future PR or now, your choice.

2024-12-19 07:00 UTC, kevinaboos approved these changes
I'll approve this now. If you want to fix the issue mentioned above in this PR, just let me know, and I'll wait to merge it. If you want to fix it in a later PR, let me know and I can merge this one now.

2024-12-19 07:31 UTC, merged

2024-12-19 08:07 UTC, kevinaboos commented
Thanks, yeah those two should be easy enough to fix. The overflow of the permission message text can be fixed by setting its `width: Fill` and `wrap: Word`.