Add basic robrix rust CI config,no conflict with current project.
project-robius/robrix pull request #275
Opened 2024-11-24 07:51 UTC by tyreseluo

Now, we have basic ci config, it include two jobs `check` and `clippy`. 

The current configuration will not conflict with what we already have in our current project.

We should gradually liberalize the corresponding code styles and some CI/CD rules, while submitting separate PRs for minor changes.

If large-scale code style changes are made, this can lead to increased project volume and some potential dangers.

So @kevinaboos @ZhangHanDong  , what are your opinions??

2024-11-25 08:35 UTC, ZhangHanDong commented
lgtm

2024-11-26 02:27 UTC, tyreseluo commented on .github/workflows/main.yml
> +      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
Just dependencies and checkout code to  ensure that  Check Clippy and Clippy can work.

2024-11-26 02:27 UTC, tyreseluo commented on .github/workflows/main.yml
> +      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev libxdo-dev
same as above.

2024-11-26 23:12 UTC, kevinaboos commented on .github/workflows/main.yml
> +      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
right, that's what I'm asking about. Are those necessary? Are you saying that clippy requires these dependencies in order to function properly?

I only ask because I have never seen these dependencies be required to run clippy in any Actions workflow before. Clippy is a standalone project (well, it's now part of Rust) that only requires a Rust toolchain installation via rustup. In general they seem unrelated, but admittedly I'm not 100% sure libayatana-appindicator is.

2024-11-26 23:24 UTC, tyreseluo commented on .github/workflows/main.yml
> +      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
I'll recheck to see if we really need the configuration inside the ci.Alex gave me a basic rust ci common configuration.

2024-11-27 21:52 UTC, kevinaboos commented
@tyreseluo in #281 I fixed all of the standard clippy lints, so you should be able to enable all lints in the CI pass and deny any that fail. 

Same for cargo check, we should deny warnings.

2024-11-27 21:53 UTC, kevinaboos commented on .cargo/config.toml
> +    "-A", "clippy::all",
see my latest comment, as of #281 being merged in, we don't need to pass `-A` to allow anything specific at all.

2024-11-27 21:53 UTC, kevinaboos requested changes

2024-11-27 21:53 UTC, kevinaboos commented on Cargo.toml
> +return_self_not_must_use = "warn"
now that #281  has been merged, please replace this list with the upstream list of lints that are already in `Cargo.toml`. Thanks.

2024-11-27 21:55 UTC, kevinaboos commented on .github/workflows/main.yml
> +      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
here is confirmation from the clippy docs themselves stating that these dependencies are not needed: https://doc.rust-lang.org/clippy/continuous_integration/github_actions.html

2024-11-28 02:07 UTC, tyreseluo commented
oh, god, so quicky! You are right. We don't need too much deps ci config, just check and clippy.

2024-11-28 05:53 UTC, kevinaboos requested changes
Thanks for the various fixes. There are just a few small things that need fixing before it's ready to merge.

2024-11-28 05:53 UTC, kevinaboos commented on .github/workflows/main.yml
> +    RUSTFLAGS: "-A warnings"
We want to *deny* warnings, not allow them.

2024-11-28 05:53 UTC, kevinaboos commented on .github/workflows/main.yml
> +    rust_nightly: nightly-2024-10-20
We shouldn't hardcode a nightly version here. We already have a rust toolchain file that achieves the same purpose, which any invocation of Rust, clippy, or associated tools should detect and use.

2024-11-28 06:10 UTC, tyreseluo commented
ok, `dtolnay/rust-toolchain@master` action will automatically read the configuration from rust-toolchain.toml.
And since the previous typos have been merged, I've added the typos job as well.

2024-11-28 08:40 UTC, kevinaboos approved these changes
Thanks, looks great!

2024-11-28 08:40 UTC, merged