Search bar of the rooms list top
project-robius/robrix pull request #298
Opened 2024-12-23 05:08 UTC by tyreseluo

## Related PRs

Implement search bar at the top of the rooms list #123 

## PR content

- Added `RoomDisplayFilterBuilder` based on `RoomDisplayFilter` to create filters with a specific set of filter types and sorting capabilities, It is very easy to extend the `RoomsListEntry` structure with field filters such as `tags`, `latest` and so on!
- The current default search rule is to match by room_name only.

## Problems

- The height of the room preview has not been resolved yet, resulting in it currently only being set to `height: 50`, which causes the index value to be incorrect, you can reproduce this by removing the height from the `room_preview`, and increasing the solid height will not cause a problem.

2024-12-23 13:22 UTC, ZhangHanDong commented on src/home/rooms_list.rs
> +                RoomDisplayFilterType::RoomId => unreachable!(),
This point is no longer `unreachable!()`. You have added the `matches_room_id` method, right?

2024-12-23 13:31 UTC, tyreseluo commented on src/home/rooms_list.rs
> +                RoomDisplayFilterType::RoomId => unreachable!(),
The previous `pre_match_filter_check()` function has already handled the case of a room_id starting with `! ` for room_id. This allows us to preprocess cases that start with special symbols, such as user ids that start with `@` and room aliases that start with `#`, beforehand.

2024-12-23 14:08 UTC, ZhangHanDong commented on src/home/rooms_list.rs
> +    }
The code can be more concise.

```rust
fn pre_match_filter_check(keywords: &str) -> Option<(&str, char)> {
    keywords.chars().next().and_then(|c| match c {
        '!' | '@' => Some((keywords, c)),
        _ => None
    })
}
```

2024-12-23 14:11 UTC, ZhangHanDong commented on src/home/rooms_list.rs
> +                    _ => false,
Since the @ search function has not been implemented yet, this prefix should not be judged. If the user enters @, then let them search by name; otherwise, nothing can be searched now, which is bad for user experience.

![Screenshot 2024-12-23 at 21 53 59](https://github.com/user-attachments/assets/e8ebbcd8-3199-419a-ab84-df129a55005e)


```rust
                    '@' => {
                        let clean_prefix_kw = keywords.strip_prefix('@').unwrap_or(keywords);
                        Self::matches_room_name(room, clean_prefix_kw)
                    },
```

![Screenshot 2024-12-23 at 21 54 09](https://github.com/user-attachments/assets/a93f0d25-8de9-409e-95a5-15a99911d7bd)

2024-12-23 14:38 UTC, ZhangHanDong commented on src/home/rooms_list.rs
> +}
Every search requires traversing the entire `all_rooms` `HashMap`, which can have performance implications when the number of rooms is large. If a sorting function is provided, we need to sort the filtered results, which involves multiple HashMap lookups (`.get()`) and comparison operations.

Based on the above reasons, optimization is possible. It is suggested to refer to the following code modification:

```rust

    fn handle_actions(&mut self, cx: &mut Cx, actions: &Actions, _scope: &mut Scope) {
        for action in actions {
            if let RoomsViewAction::Search(keywords) = action.as_widget_action().cast() {
                // Build the search filter. We keep this part unchanged as it has minimal overhead
                let (filter, sort_fn) = RoomDisplayFilterBuilder::new()
                    .set_keywords(keywords)
                    .by_all()
                    .build();
                self.display_filter = filter;

                // Clear and pre-allocate capacity for the display list to avoid multiple 
                // memory reallocations when adding elements
                self.displayed_rooms.clear();
                self.displayed_rooms.reserve(self.all_rooms.len());

                // Different optimization strategies are needed based on whether 
                // a sorting function is provided
                if let Some(sort_fn) = sort_fn {
                    // Create a temporary reference mapping to avoid repeated HashMap lookups
                    // during the sorting process. This significantly improves performance
                    // when dealing with large room lists
                    let filtered_rooms: Vec<(&OwnedRoomId, &RoomsListEntry)> = self.all_rooms
                        .iter()
                        .filter(|(_, room)| (self.display_filter)(room))
                        .collect();

                    // Sort the filtered references. This approach prevents unnecessary
                    // cloning and HashMap lookups during the comparison operations
                    let mut sorted_rooms = filtered_rooms;
                    sorted_rooms.sort_by(|(_, room_a), (_, room_b)| {
                        sort_fn(room_a, room_b)
                    });

                    // Perform a single clone operation on the final sorted results
                    // rather than cloning during intermediate steps
                    self.displayed_rooms.extend(
                        sorted_rooms.into_iter()
                            .map(|(room_id, _)| room_id.clone())
                    );
                } else {
                    // When no sorting is required, we can directly filter and collect
                    // the results. Using extend avoids creating an intermediate Vec
                    // and minimizes memory allocations
                    self.displayed_rooms.extend(
                        self.all_rooms
                            .iter()
                            .filter(|(_, room)| (self.display_filter)(room))
                            .map(|(room_id, _)| room_id.clone())
                    );
                }

                // Update the status message using String's into method to avoid
                // unnecessary string allocations
                self.status = if self.displayed_rooms.is_empty() {
                    "No rooms found matching search.".into()
                } else {
                    format!("Found {} rooms matching search.", self.displayed_rooms.len())
                };

                // Trigger a UI redraw to reflect the updated room list
                self.redraw(cx);
            }
        }
    }

```

2024-12-26 21:20 UTC, kevinaboos requested changes
I left a few comments, the main one being about how we should use `bitflags` to hold the filter set rather than a `HashSet` of enums.

there are quite a few variants for configuring the filter mechanism, but AFAICT, you only ever use `by_all`.... right? What are the others for, and when should they be used?

2024-12-26 21:20 UTC, kevinaboos commented on src/home/room_preview.rs
> +        width: Fill, height: 50.
this won't work, as I currently have the `FullPreview` height set to 60, which means the view will get clipped. Please remove this.

2024-12-26 21:20 UTC, kevinaboos commented on src/home/room_preview.rs
> +        // to change the displayed content (and its layout) based on the available space in the sidebar.
undo

2024-12-26 21:20 UTC, kevinaboos commented on src/home/rooms_list.rs
> +                self.displayed_rooms.reserve(self.all_rooms.len());
this creates two unnecessary allocation actions. Instead of using `self.displayed_rooms` directly, just create a separate local object and then assign it to `self.displayed_rooms` at the end of this block.

2024-12-26 21:20 UTC, kevinaboos commented on src/home/rooms_list.rs
> +    All,
i don't understand what `All` means here, and same for "filter `by_all`".  Can you explain what this means?

2024-12-26 21:20 UTC, kevinaboos commented on src/home/rooms_list.rs
> +    All,
ah, perhaps you meant "matches _any_ kind of room info", e.g., the room name, ID, alias, tags, etc.

In that case, this should be the "default", and the `None` variant should be removed.

2024-12-26 21:20 UTC, kevinaboos commented on src/home/rooms_list.rs
> +type SortFn = Box<dyn Fn(&RoomsListEntry, &RoomsListEntry) -> Ordering>;
this should be called `BoxedSortFn`, or you should remove the Box wrapper from this type def and then add it later where it is actually used, e.g., in Line 229 you could do `sort_fn: Option<Box<SortFn>>`. Up to you.

2024-12-26 21:20 UTC, kevinaboos commented on src/home/rooms_list.rs
> +pub enum RoomDisplayFilterType {
this shouldn't be an enum, it should be a bitflags set, right?

That way you can store it very efficiently (currently it would fit within a `u8`) and also check it more efficiently than a `HashSet`.

2024-12-29 14:32 UTC, tyreseluo commented on src/home/room_preview.rs
> +        // to change the displayed content (and its layout) based on the available space in the sidebar.
yep, I don't know why they appear to be changed, it was there in the original code.

2024-12-29 15:07 UTC, tyreseluo commented on src/home/room_preview.rs
> +        width: Fill, height: 50.
ok, I have deleted this line, but currently there is an issue that when searching for text when deleting, it needs to be re-rendered (at least to trigger an event so that when you move the mouse, the correct room list appears), and I'm trying to find out the cause of this issue.

2024-12-29 15:10 UTC, tyreseluo commented
## PR revision content
- PR Changes to the content of the review.
- Currently refactoring a previous duplicate of a similar method, and the type of RoomDisplayFilterType.

2024-12-30 04:18 UTC, kevinaboos commented on src/home/room_preview.rs
> +        width: Fill, height: 50.
ok, can you just do a redraw of the rooms list any time the search terms are changed?

I assume you'd have to do that anyway even when typing new characters, so deleting characters shouldn't be any different, right?

2024-12-30 04:33 UTC, tyreseluo commented on src/home/room_preview.rs
> +        width: Fill, height: 50.
that's right, but shouldn't typing new characters and reducing characters be an action sent automatically and then handled in WidgetMatchEvent self.redraw(cx).I'll check if it's my rendering logic triggering the issue?

2024-12-30 04:47 UTC, kevinaboos requested changes
Code looks generally fine, except for a few small issues I detailed in my comments.

2024-12-30 04:47 UTC, kevinaboos commented on src/home/room_preview.rs
> -        // (and its layout) based on the available space in the sidebar.
why is this removed? undo.

2024-12-30 04:47 UTC, kevinaboos commented on src/home/rooms_list.rs
> +                TagName::Favorite => search_tag == "favourite",
should probably add the american english spelling "favorite" too

2024-12-30 04:47 UTC, kevinaboos commented on src/home/rooms_list.rs
> +                RoomDisplayFilterType::RoomTags if filter_types.contains(RoomDisplayFilterType::RoomTags) => Self::matches_room_tags(room, keywords),
the point of using bitflags here is that it would more easily let you search for _multiple_ conditions. But by using a `match` statement here, you're only enabling _one condition_ to be searched for. 
For example, if `RoomId` AND `RoomName` are both set, this code will only search for a matching `RoomId`.

Instead, if you need to have four separate `if` conditionals for each one of these possibilities. A single `match` statement can't represent this logic. As a bonus, if you do this, you won't need the following special code block for `All`.

2024-12-30 04:47 UTC, kevinaboos commented on src/home/rooms_list.rs
> +                .build();
indentation fix

```suggestion
                    .set_keywords(keywords)
                    .set_filter_types(RoomDisplayFilterType::All)
                    .build();
```

2024-12-30 04:47 UTC, kevinaboos commented on src/home/rooms_list.rs
> +            if let RoomsViewAction::Search(keywords) = action.as_widget_action().cast() {
since you also use this `RoomsViewAction::Search` type for a cleared/reset search action, you should probably have a fastpath at the top of this conditional (right after this line of code) that handles the case where `keywords` is empty.

2024-12-30 04:47 UTC, kevinaboos commented on src/home/rooms_list.rs
> +                    format!("Found {} rooms matching search.", self.displayed_rooms.len())
don't forget to handle the case of `1` matching room. 

I'd recommend something like:
* "Found 0 matching rooms."
* "Found 1 matching room."
* "Found 5 matching rooms."

2024-12-30 04:48 UTC, kevinaboos commented on src/home/room_preview.rs
> +        width: Fill, height: 50.
ah yea, it appears that the search bar does already emit actions upon any `changed()` text. Weird.

2025-01-03 02:06 UTC, merged

2025-01-03 02:06 UTC, kevinaboos commented
one thing we need to do is set the text color of the search bar to be darker when it is not empty. Can you tackle that in a follow-up PR?

2025-01-03 02:08 UTC, tyreseluo commented
ok, I will do that.