Permissions are not updated in a timely manner after successfully accepting an invitation to a direct room
project-robius/robrix pull request #305
Opened 2024-12-27 11:59 UTC by aaravlu

2024-12-27 12:04 UTC, aaravlu commented
[Screencast from 2024-12-27 19-56-49.webm](https://github.com/user-attachments/assets/a1ebc81f-2154-46b1-a163-2f51b9bd830c)

2024-12-27 19:49 UTC, kevinaboos commented
> Screencast.from.2024-12-27.19-56-49.webm

looks like things still don't work? i can't quite tell what this screen recording is trying to show.... it looks like you join a room but then it still shows that you don't have permissions to send a message?

2024-12-27 19:55 UTC, kevinaboos requested changes
Based on your screen recording, i think this PR accidentally breaks the latest_event calculation code.

Instead of this new approach where you separate out avatar handling from "can send message" handling, please move it all into a single `update_latest_event()` function (like i had before), which will ensure that all of the various possible relevant event kinds are handled upon every change to the latest event (which can occur in multiple places). I think the following 5 things are of interest to us:
* room name
* room avatar
* room power levels
* membership change
* latest event text preview

2024-12-27 19:55 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    submit_async_request(MatrixRequest::CheckCanUserSendMessage { room_id: room_id.clone() })
why would you need to submit a separate async request for this? Can't you just determine it directly from the room power levels information available right here in this event?

2024-12-27 19:55 UTC, kevinaboos commented on src/sliding_sync.rs
> +fn update_avatar_for_latest_event(
undo this name change, it is incorrect and misleading since it does way more than just the avatar.

2024-12-28 02:52 UTC, aaravlu commented
> looks like things still don't work? 

It works. I apologize for not clarifying the screenshot.
I have already used account `aaravlu` set room 302 send permission to 100 so that account `demolemon` cannot send message in the room and invite `demolemon` to this room.
It directly show the cannot send notice in `demolemon`'s screen after accepting the invitation without reselecting room 302 manually.

2024-12-28 02:54 UTC, kevinaboos commented
> > looks like things still don't work?
> 
> It works. I apologize for not clarifying the screenshot.
> 
> I have already used account `aaravlu` to set room 302 send permission to 100 so that account `demolemon` cannot send message in the room, and then `aaravlu` invited `demolemon` to this room. It directly show the cannot send notice in `demolemon`'s screen after accepting the invitation without reselecting room 302 manually.

oh i see, that makes more sense then. It appeared to be the opposite. Thanks for clarifying

2024-12-28 03:45 UTC, aaravlu commented on src/sliding_sync.rs
> +                    submit_async_request(MatrixRequest::CheckCanUserSendMessage { room_id: room_id.clone() })
Done.

2024-12-28 03:46 UTC, aaravlu commented on src/sliding_sync.rs
> +fn update_avatar_for_latest_event(
Done.

2024-12-30 04:14 UTC, kevinaboos requested changes
Getting closer, but you missed some of [what I said here](https://github.com/project-robius/robrix/pull/305#pullrequestreview-2524349250): 

> Instead of this new approach where you separate out avatar handling from "can send message" handling, please move it all into a single `update_latest_event()` function (like i had before), which will ensure that all of the various possible relevant event kinds are handled upon every change to the latest event (which can occur in multiple places). I think the following 5 things are of interest to us:
> * room name
> * room avatar
> * room power levels
> * membership change
> * latest event text preview

2024-12-30 04:14 UTC, kevinaboos commented on src/sliding_sync.rs
> +            if let Some(MembershipChange::InvitationAccepted) = room_membership_change.change() {
shouldn't we only re-check if the user can send a message in this room  _if the membership change was for the current user_? 

I think you can check that quite easily using our `current_user_id()` function and [the `user_id()` function in `RoomMembershipChange`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_ui/timeline/struct.RoomMembershipChange.html)

2024-12-30 05:44 UTC, aaravlu commented on src/sliding_sync.rs
> +                        let (room_avatar_changed, can_user_send_message) = update_latest_event(room_id.clone(), &new_latest);
Yes.

2024-12-30 05:52 UTC, aaravlu commented on src/sliding_sync.rs
> +                        let (room_avatar_changed, can_user_send_message) = update_latest_event(room_id.clone(), &new_latest);
Done.

2024-12-30 05:54 UTC, aaravlu commented on src/sliding_sync.rs
> +                        let (room_avatar_changed, can_user_send_message) = update_latest_event(room_id.clone(), &new_latest);
Done.
I added a parameter to `update_latest_event`.

2024-12-30 05:54 UTC, aaravlu commented on src/sliding_sync.rs
> +            if let Some(MembershipChange::InvitationAccepted) = room_membership_change.change() {
Done.

2024-12-30 05:59 UTC, aaravlu commented
> Getting closer, but you missed some

Yeah. now they are in one function.
We currently handle room name, avatar, membership and power levels changes.
Lmk if there's anything else you want.

2024-12-31 04:54 UTC, kevinaboos approved these changes
Looks good now! Thanks for your great work here!

2024-12-31 04:55 UTC, merged