Cleanup latest event handling and use more accurate conditionals
project-robius/robrix pull request #309
Opened 2024-12-31 06:03 UTC by kevinaboos

This PR contains some general cleanup & improvements that are follow-ups to PR #305. 

* When inspecting content from a new latest event that changed room power levels, we now look for not just an invitation being accepted but also for a general room Join action.
* When checking a user's power level to see if they can send a message, we now check against the current power levels required to send a message, not the room's default level. We only use the default power level as a backup.

2024-12-31 06:11 UTC, kevinaboos commented
@aaravlu after merging in your latest PR #305, I noticed some minor issues with it. I've attempted to address them here in this PR and have requested your review. 

Can you kindly test it out with all of the previous use cases you tested PR#305 with? )(just to make sure that I didn't break anything)

Thanks!

2025-01-01 03:17 UTC, aaravlu commented
Yes, exactly right.

There are two case but I only handled `Users are invited into the room`: 

User-initiated room joining
Users are invited into the room

And there are three message types while I only handled the `content.events_default`: 

org.matrix.msc1767.message
m.room.message
`content.events_default`

2025-01-01 03:25 UTC, aaravlu requested changes

2025-01-01 03:25 UTC, aaravlu commented on src/sliding_sync.rs
> +                    if let Some(sender) = timeline_update_sender {
IMHO, in the branch `AnyOtherFullStateEventContent::RoomPowerLevels`, the `timeline_update_sender` is always a `Some` currently, maybe we can `unwrap()` it directly.
I wrap it manually here: 
https://github.com/project-robius/robrix/blob/16fc9e33ee66fd585976bf3d172a62634eb7bc2f/src/sliding_sync.rs#L1891

2025-01-02 05:01 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    if let Some(sender) = timeline_update_sender {
If you were able to guarantee it's always `Some`, then we wouldn't need to wrap it in an Option at all. Since we cannot guarantee that, we shouldn't unwrap.

This is a general rule: unwrap and other panicking functions should be avoided if at all possible.

2025-01-02 05:01 UTC, merged

2025-01-02 05:33 UTC, aaravlu commented on src/sliding_sync.rs
> +                    if let Some(sender) = timeline_update_sender {
For `other.content()`, there three branches: 
`AnyOtherFullStateEventContent::RoomName`

`AnyOtherFullStateEventContent::RoomAvatar`

`AnyOtherFullStateEventContent::RoomPowerLevels`

This function finally run one of the branches so that `timeline_update_sender` is always `Some` when function run branch `AnyOtherFullStateEventContent::RoomPowerLevels` and is always  `None` for the other two: `AnyOtherFullStateEventContent::RoomName`, `AnyOtherFullStateEventContent::RoomAvatar`.

Thus, I thinks `unwrap()` it here is always safe.

2025-01-02 19:04 UTC, kevinaboos commented on src/sliding_sync.rs
> +                    if let Some(sender) = timeline_update_sender {
the only way that we should accept that rationale is if you also accompanied it with a code refactoring that removed the `Option` wrapper (which is possible, but not worth the effort at this point).